### ISSUE TITLE
PlainChildren and Infinite Scroll Behavior

### ISSUE THREAD

**Issue by SudharsanSukumar** [thebuilder/react-intersection-observer#102]
Hi,

Right now I'm using this package for infinite scroll. I have a list of items and place an observed div at the bottom and load more items when onChange is called and inView is true. When render is called, more items are added and I place the observed element at the bottom of the list again if there are more items to load.

I noticed that if I scroll down very quickly, onChange isn't called which stops the loading of more items until the user scrolls up and then back down.

I was thinking this behavior could be due to my implementation I described where technically the inView for that element hasn't really changed? Though because of a React rerender I would have expected it to be reevaluated.

If this isn't a bug, is there a way to get the current inView status? Or is there a better way for me to implement this?

Thanks,
Dharsan

**Comment by thebuilder** [comment]
I think i'd need to see how you are handling `onChange` and updating the view. There could potentially be an issue with how the state is updated. 

A solution could be to change the `key` prop for the `<Observer>` after an update, to ensure it's recreated.

To get the `inView` value outside `onChange` you'd have to use the render props method. It will call your function with the current value of inView.

**Comment by SudharsanSukumar** [comment]
I tried your second option but it registered as inView multiple times and loaded too many items.

I ended up setting the key prop and it seems to have worked. I actually didn't now that's how you force recreation, great idea! 

Thanks for this package it's fantastic and allows us to do a whole bunch of really cool things super easily!

Thanks,
Dharsan

**Comment by thebuilder** [comment]
The render prop is called on all renders, so it would be up to you to determine if the value actually changed. Hence it would be better to use the `onChange` since it does that for you. :)
