### ISSUE TITLE
Could observe one element only once

### ISSUE THREAD

**Issue by thearnica** [thebuilder/react-intersection-observer#119]
Simple problem - as long you are tracking `elements` via `INSTANCE_MAP.set(element, instance)` - one element could be associated with one one instance.

If, but any reason, 2 different observers observe one element - only one would work - the top one.

**Comment by thebuilder** [comment]
Do you have an example of how that could be achieved? You'd have to give the same `ref` to two different observers?

**Comment by thearnica** [comment]
Yep. In my case I have 2 "levels" of Observers, let call it "block level" and "element level", to produce something like "waterfall" animation - "internal" observer should not fire until "parent" block will "enough" visible.
But sometimes, due to BEM for example, top level block and inner element is the same DOM element.
Result - it keeping be invisible.

**Comment by thebuilder** [comment]
This seems like an edge case, that is related to the DOM structure of your component. I'm guessing you could solve it by ensuring you don't use the same element for both observers?

It would require a complete rewrite of the Intersection handler in `react-intersection-observer` to support this, since it's built around the concept of an element having a single observer instance.

**Comment by thearnica** [comment]
If you could not support it yet - what about printing some debug information when someone starts observing already observed node?
To be honest - it was quite hard to understand why some parts of my application does not works, while everything else works well :)

**Comment by thebuilder** [comment]
That's fair. I'll add and `invariant` log message if the element is already used. 👍

**Comment by thebuilder** [comment]
I just published a version that throws an error if you try to observe the same element twice. Give it a try!
