### ISSUE TITLE
Proposal: disabled prop

### ISSUE THREAD

**Issue by raRaRa** [thebuilder/react-intersection-observer#132]
I would like to propose a new prop `disabled` that disables the observation temporarily. This would be ideal for server-side rendering, where you don't want the server to render elements that are in view, since that should only happen client-side.

**Comment by thebuilder** [comment]
Instead of setting a `disable` property, you could skip rendering the component. Something like:

```jsx
import Observer from 'react-intersection-observer'

const Component = ({enabled}) => enabled ? (
  <Observer>
    {({ inView, ref }) => (
      <div ref={ref}>
        <h2>{`Header inside viewport ${inView}.`}</h2>
      </div>
    )}
  </Observer>
) : null

export default Component
```

Keep in mind, that if you skip rendering on the server, that you can't change the rendering output untill the client has rehydrated.

**Comment by raRaRa** [comment]
Well, I would like to render the component, but without the animation classes. Currently I'm doing a hack to check if `react-snap` (which pre-renders all pages) is rendering. 

So I'm doing checks all over the place like this: `[style.moveInShape]: inView && !isReactSnap,`

`react-snap` uses `puppeteer` and I believe it triggers `inView`.

**Comment by raRaRa** [comment]
I noticed there's another repo with the exact same name here: https://github.com/researchgate/react-intersection-observer that supports the `disabled` prop. What's the main difference between this repo and the one under researchgate? Looks very similar (sorry, I should probably open another ticket for this question)

**Comment by thebuilder** [comment]
They have their own implementation of a solution, but I think you will still run into the [rehydration](https://reactjs.org/docs/react-dom.html#hydrate) issue if you use `disabled`.

**Comment by thebuilder** [comment]
Sorry, you might not actually get an issue rehydration since it doesn't trigger till it recieves a `ref` node. I still think the way you are doing it with `inView && !isReactSnap` makes sense.

You'd just move the `isReactSnap` to a disabled prop, but you'd still need it.
