### ISSUE TITLE
inView is always true in Chrome

### ISSUE THREAD

**Issue by jahvi** [thebuilder/react-intersection-observer#139]
I'm having a similar bug as reported in #8 where in Chrome v70 the value of `inView` seems to be `true` on load no matter if the element is in view or not.

Here's a simple demo of what I mean:
https://codesandbox.io/s/2w2w87744r

It works fine on Firefox so it might be just a Chrome bug.

**Comment by thebuilder** [comment]
Hey, the issue seems to be related to the height of the `<Observer />` during first render. It renders `<div />` with your image inside.

I tried to use a function to pass the ref to the `<img />` tag, which seems to work.
https://codesandbox.io/s/64945wmrx3

**Comment by thebuilder** [comment]
This has the added benefit of not requiring you to maintain the the state in your **Img** component. 🙂

**Comment by thebuilder** [comment]
Setting the width and height on the `<Observer />` (wrapping div) also seems to fix it:
https://codesandbox.io/s/23ql7zw85y

**Comment by jahvi** [comment]
Ah I could have sworn I tried that but didn't work, I must have missed something it does work now. Thanks!
