### ISSUE TITLE
Better examples/demo

### ISSUE THREAD

**Issue by thebuilder** [thebuilder/react-intersection-observer#142]
While the storybook is nice, it's more useful when developing the module.

It should be replaced by a better looking static site, that also demonstrates common usecases, like lazy images and animation triggers.

**Comment by riyadshauk** [comment]
Yeah, a lazy-loaded image code example would definitely be appreciated.

**Comment by jpdevries** [comment]
More examples are always great, but just want to say how much I appreciate this module. Excellent work!

**Comment by thebuilder** [comment]
Some work has been done on this for v7.0.0 - https://github.com/thebuilder/react-intersection-observer/releases/tag/v7.0.0

But there's always room for more improvement.
