### ISSUE TITLE
Many targets with one observer.

### ISSUE THREAD

**Issue by kherel** [thebuilder/react-intersection-observer#155]
Can I use "react-intersection-observer" to observe for many elements(targets) in one root component and one observer?

**Comment by thebuilder** [comment]
You can create an instance for each element you want to monitor. If they share the same root and threshold it will reuse the Intersection Observer.

**Comment by qramilq** [comment]
@thebuilder  thank's for your answer, but can you show some example? I have created some [sandbox](https://codesandbox.io/s/fervent-jang-5cuzi)

**Comment by thebuilder** [comment]
@qramilq You would still need to create a new `useInView` hook for each target (Button in this instance).
What `react-intersection-observer` does internally is reuse the `IntersectionObserver` instance for all the targets.

**Comment by stephyswe** [comment]
> You can create an instance for each element you want to monitor. If they share the same root and threshold it will reuse the Intersection Observer.

How ?

**Comment by thebuilder** [comment]
It happens automatically if the observer is using the same options. Just create your `useInView` hooks where you need to them.
