### ISSUE TITLE
Can it export more properties of IntersectionObserverEntry?

### ISSUE THREAD

**Issue by lenchen1112** [thebuilder/react-intersection-observer#156]
Now it seems like only export `intersectionRatio` in callback.
https://github.com/thebuilder/react-intersection-observer/blob/master/src/intersection.js#L158

Can it export more properties of intersectionObserverEntry or the entire entry for reducing redundant calculation? I have encountered a situation that I need to count target's in-viewport time and would like to use `intersectionObserverEntry.time`.

Thanks.

**Comment by thebuilder** [comment]
That would make sense. It should return the entire `IntersectionObserverEntry`. Need to consider how to best add this, without breaking the API.

**Comment by thebuilder** [comment]
Check out the new version: https://github.com/thebuilder/react-intersection-observer/releases/tag/v7.0.0

It's exposing the entire IntersectionObserverEntry object for you now!
