### ISSUE TITLE
process.env.NODE_ENV is undefined

### ISSUE THREAD

**Issue by SudharsanSukumar** [thebuilder/react-intersection-observer#157]
Hi,

Another team using this package noticed that when using their build system they would get a runtime error saying process.env.NODE_ENV is undefined or something to that effect. It seems like this library requires that environment variable to be set? We mitigated this by replacing this manually at build time for a temporary workaround. Our team is using 6.1.1 and we haven't hit this issue, but they are using 6.4.1. Any ideas?

Thanks,
Dharsan

**Comment by SudharsanSukumar** [comment]
Looks like this PR: https://github.com/thebuilder/react-intersection-observer/pull/88/files

**Comment by thebuilder** [comment]
How are they building the package? It should be able to read the `process.env.NODE_ENV` variable, that you would normally set as part of bundling React.

**Comment by thebuilder** [comment]
I can see that this is actually included in the UMD bundle, so that would properly break because of it. I should update the Rollup config to set `process.env.NODE_ENV` to `production` for the UMD, since it is intended to be embedded in the browser.

**Comment by SudharsanSukumar** [comment]
Yes we're using the UMD which would explain it! Thanks for the quick response!

**Comment by thebuilder** [comment]
This is fixed in version `6.4.2`👌

**Comment by SudharsanSukumar** [comment]
Brilliant thanks again for the great lib 👍
