### ISSUE TITLE
Component cannot be polyfilled to level of IntersectionObserver

### ISSUE THREAD

**Issue by etripier** [thebuilder/react-intersection-observer#166]
I really like this component! I'm hoping to use it in a few projects, but unfortunately I can't until it supports the same browsers that the `IntersectionObserver` polyfill does. The issue is the use of `WeakMap` here: https://github.com/thebuilder/react-intersection-observer/blob/master/src/intersection.ts#L17.

`WeakMap` cannot be polyfilled on IE10, among other browsers, because IE10 doesn't allow HTML elements to be extended (a key requirement to support the loosely-held references).

I think you could use a regular `Map` and `delete` as needed. You could also just set `window.WeakMap = window.WeakMap || Map` and lose out on garbage collection (probably not the best idea, but it does support older browsers without compromising on performance).

I'd be happy to put up a PR for either change. Wondering what you think and if you'd be open to the idea.

**Comment by thebuilder** [comment]
I wasn't aware of this issue. I'll just use the map instead, which should be fine. 

Just need to check if it's still used, or delete the key from the map. 

Thanks fur the heads up👌 Feel free to make a PR if you want to.
