### ISSUE TITLE
Allow for full `IntersectionObserver` options to be passed in?

### ISSUE THREAD

**Issue by tizmagik** [thebuilder/react-intersection-observer#18]
First, thanks for the component, this is great!

I wanted to ask if the full options of `IntersectionObserver` API could be passed in? Right now it looks like [only](https://github.com/thebuilder/react-intersection-observer/blob/master/src/intersection.js#L14) `{ threshold }` is passed in, so it's missing the [other options](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), like `root` and `rootMargin`.

Was this a deliberate decision? If not, would you accept a PR adding in the other options?

**Comment by thebuilder** [comment]
Hey - I didn't need to use the other options, so never got around to adding it. It makes sense to add them, but i guess it requires some work. 

Right now i'm using the `threshold` to handle the instance creation of `IntersectionObserver` - It would need to take all the options into account.

**Comment by DannyLingard** [comment]
Hey just stumbled across this as looking to implement an infinite scroller for an ancestor element. Are you intending to add `root` option or awaiting a PR from @tizmagik?

**Comment by thebuilder** [comment]
Hey, just created a new branch for it yesterday 🙌- still needs some more test, before it's ready for release. Haven't used the root options before - any good usecases for it?🤔

Med venlig hilsen
Daniel Schmidt
________________________________

**Comment by thebuilder** [comment]
Fixed in #21 and released as version 1.0.0

**Comment by thebuilder** [comment]
@tizmagik and @DannyLingard - Try out these new options if you have a chance. Would like to know if there are any issues, when you make an actual implementation.

**Comment by DannyLingard** [comment]
@thebuilder Thanks for the update, I'm about a week or so away from implementing but will keep you posted. Use case:  I'm developing an enterprise dashboard where the user can have 1000+ search results, which are displayed in a dropdown. Each result is also a collapse, displaying related data when expanded. I'm hoping I can use this as an alternative to react-virtualized for infinite scrolling as I'm catering to evergreen browsers.
