### ISSUE TITLE
Add `className` into `InView` typings

### ISSUE THREAD

**Issue by r3nya** [thebuilder/react-intersection-observer#181]
Hey @thebuilder!
Thanks a lot for your job!

I guess you have to add `className` field for `inView` typings. :)

E.g. code:
```js
<InView
  as="footer"
  role="contentinfo"
  triggerOnce
  className={styles.container}
  onChange={this.setVisible}
>
…
</inView>
```

As far as I understood correctly, need to change https://github.com/thebuilder/react-intersection-observer/blob/master/src/typings/types.ts#L14 file, right?
If yes, I can create a PR. Please let me know. :)

**Comment by thebuilder** [comment]
I think it should accept more values than just `className`. I'll have to look into doing it properly.

**Comment by thebuilder** [comment]
Types should be split into one for the Render Props and one for the Plain children. The Plainchildren can then extend HTML Props - https://github.com/sw-yx/react-typescript-cheatsheet/blob/master/ADVANCED.md#props-one-or-the-other-but-not-both

**Comment by thebuilder** [comment]
Thi should be fixe in v.8.10.0, where i added separate typings for PlainChildren props. 👌

**Comment by r3nya** [comment]
Thank you!
