### ISSUE TITLE
Testing a component using `react-intersection-observer`

### ISSUE THREAD

**Issue by Jayphen** [thebuilder/react-intersection-observer#185]
How might one test a React component that is implementing the `useInView` hook?

I have mocked IntersectionObserver:

```
global.IntersectionObserver = jest.fn(function() {
  this.observe = jest.fn();
  this.unobserve = jest.fn();
  this.disconnect = jest.fn();
});
```

My Image component should have a certain background image when in view, as described in my test below. I've attempted to trigger the intersection (by naively copying some of the tests I found in this library), but without luck.

```
  it('renders full image when in view', () => {
    const { image } = render(<Image />);
    const calls = global.IntersectionObserver.mock.calls;
    const [onChange] = calls[calls.length - 1];

    onChange([
      {
        target: image.firstChild,
        isIntersecting: true,
        intersectionRatio: 0.5
      }
    ]);


    expect(image).toHaveStyleRule(
      'background-image',
      'url(https://dummyimage.com/600x400/000/fff)'
    );
  });
```

Any tips here? Thank you!

**Comment by thebuilder** [comment]
It's actually a good question. 
I should come up with a reusable example for testing it in applications, or a helper method for simulating intersection state. You really shouldn't have to mess with mocking the `IntersectionObserver` like that, just to test it.

The idea is that you want to trigger the `onChange` method with the intersection state, which will then trigger an update of your component. You properly need to `wait` for the next render to happen, before you can see the effect on the DOM output.

**Comment by Jayphen** [comment]
I did try it with an `await wait(0)` as well as with `waitForDomChange()`, but without luck.

Mocking the `IntersectionObserver` seems to be necessary anyway, as it's not available on `window` in the test environment

**Comment by Jayphen** [comment]
For now I can actually just get around this by mocking the module and having `useInView` return `true` in the tuple

**Comment by thebuilder** [comment]
That would work 👍

**Comment by JohnAlbin** [comment]
FYI, here's how mocked the InView version for Jest tests. Comments/criticisms welcome.

```javascript
// __mocks__/react-intersection-observer.js
import React from 'react';

export const InView = ({ children }) => children({ inView: true, ref: null });
```

**Comment by thebuilder** [comment]
I've created a `test-helper.js` that exposes some mock methods, to assist with testing.
Just going to try it in a real project before i publish it, but so far it seems to be working nicely. 

https://github.com/thebuilder/react-intersection-observer/blob/d35365990136bfbc99ce112270e5ff232cf45f7f/src/test-helper.ts

```js
import React from 'react'
import { act } from 'react-dom/test-utils'
import { render } from 'react-testing-library'
import { useInView } from 'react-intersection-observer'
import {
  intersectionMockInstance,
  mockIntersection,
} from 'react-intersection-observer/lib/test-helper'

const HookComponent = ({ options }) => {
  const [ref, inView] = useInView(options)
  return (
    <div data-testid="wrapper" ref={ref}>
      {inView.toString()}
    </div>
  )
}
test('should create a hook inView', () => {
  const { getByText, getByTestId } = render(<HookComponent />)
  act(() => {
    mockIntersection(getByTestId('wrapper'), true)
  })
  getByText('true')
})
```

**Comment by thebuilder** [comment]
This is included in the `8.20.0` release:
https://github.com/thebuilder/react-intersection-observer/releases/tag/v8.20.0

Let me know if it works. 👌

**Comment by asherccohen** [comment]
Heu, Thanks for these helpers. I ave noticed some methods have changed name, wasn't too hard to discover.

I am trying to test a component that makes use of your hook and I tried getting the intersection-observer instance with intersectionMockInstance method.

I am using enzyme and mount, I pass an element like this:

const wrapper = mount(<LazyImage />);
const instance = intersectionMockInstance(wrapper);

or like this:
const instance = intersectionMockInstance(<LazyImage />);

or like this:
const instance = intersectionMockInstance(mount(<LazyImage />));

But instance is always undefined. How can I mock the intersection-observer to run a test with enzyme on a custom component?My goal is to test <LazyImage />, not the hook.

**Comment by thebuilder** [comment]
I haven't tested it myself using Enzyme.
But you need to pass it the actual DOM element - I'm fairly certain enzyme `mount()` returns a reference to the Enzyme instance?

Calling `mockAllIsIntersecting(true)` will also trigger all elements if they have been mounted.

**Comment by asherccohen** [comment]
Thanks for confirming my idea!The problem is that with mount (and its methods to get an element node) I'm always thrown back the error: 'No instance found. Are you sure the element is still in the DOM' coming from your test-utils.

I'm forced to use enzyme for I'm working on a legacy project that only relies on unit testing.

**Comment by asherccohen** [comment]
So, just a quick answer to my long investigation if anyone lands here:

MY SCENARIO:
I am forced to unit test (and make sure coverage is very high) with Enzyme, so the only tools I have are SHALLOW or MOUNT.

PROBLEM: 
Hooks need a wrapper component to be tested, they are not normal functions and they need to be called in a react environment. Also the intersection observer needs to be fully mocked.

MY APPROACH:
I decided to use the real component I had to test as a wrapper for the hook. With one catch I  would test the component AND the hook.
I could see the hook being called, the DOM elements change as I wanted but my assertions would never pass. Why?

MY DISCOVERY:
Enzyme DOES NOT re-render children, even with:
- mount 
- wrapper.update()
- wrapping my effect in act from react test utils as suggested in many tutorials.

The only way Enzyme re-renders children is with wrapper.setProps({}), BUT if your logic doesn't depend on props then you're stuck.

THE SOLUTION:
If you can, USE the amazing 'react-testing-library' render. This truly re-renders as I was able to make the tests work.
I was lucky to discover that I didn't need the hook after-all. I changed my component's logic to make full use of useInView and the REF function to conditionally lazy load my images. So thanks to the maintainers for this awesome library!

**Comment by minhduc-nguyen** [comment]
FYI if anyone wants to mock `useInView` with Jest, here is the solution I use:
```
import { useInView } from 'react-intersection-observer';

jest.mock('react-intersection-observer');

test('test', () => {
    useInView.mockImplementation(() => [null, true]);
    const wrapper = mount(renderTestComponent());

    // ... test some logic with mocked value of `inView=true` above ...
});

```

**Comment by mattce** [comment]
We ran into the same situation where `mockAllIsIntersecting(true)` just didn't work. After many hours of debugging and trial and error we recognised that single executed tests worked fine whereas running a whole suit resulted in no or wrongly executed mocks.

A solution for us was to actively unmount the wrapper via `wrapper.unmount()` (we are using enzyme) after every test and then everything was fine. This also accounted to absolutely independent tests where components were freshly mounted from case to case.

**Comment by thebuilder** [comment]
I think this is an issue with how Enzyme mounts/unmounts. I have only tested it with testing-library and `act`, so something needs to change for Enzyme.

**Comment by thebuilder** [comment]
I've also noticed react-datocms https://github.com/datocms/react-datocms/blob/master/src/Image/__tests__/index.test.tsx is using the `test-utils` with Enzyme. They hacked it by setting different threshold values (to create new instances).

**Comment by SerhatG35** [comment]
> FYI if anyone wants to mock `useInView` with Jest, here is the solution I use:
> 
> ```
> import { useInView } from 'react-intersection-observer';
> 
> jest.mock('react-intersection-observer');
> 
> test('test', () => {
>     useInView.mockImplementation(() => [null, true]);
> 
>     // ... test some logic with mocked value of `inView=true` above ...
> });
> ```

I have the component below, when im testing i used your trick to mock react-intersection-observer everything work well but this time useEffect triggers twice the one with the inView === true i cant figure it out i need help, thank you.

```javascript
const Episodes = () => {
    const [episodes, setEpisodes] = useState<EpisodeTypes[]>([])
    const [page, setPage] = useState<number | null>(1)
    const [ref, inView] = useInView()

    const fetchEpisodes = async () => {
        if (page !== null) {
            const data = await EpisodesGET(page)
            setEpisodes(prev => [...prev, ...data.results])
            if (data.info.next !== null) setPage(Number(data.info.next.split('page=')[1]))
            else setPage(data.info.next)
        } else return
    }
        useEffect(() => {
        if (inView === true) fetchEpisodes()
    }, [inView])

       return (
            <Center as='main' justifyContent='flex-start' width='70%'>
                {episodes?.map((episode, index) => (
                    <EpisodeBox
                        key={episode.id}
                        episode={episode}
                        viewRef={index === episodes.length - 1 ? ref : undefined}
                    />
                ))}
            </Center>
       )
```

**Comment by minhduc-nguyen** [comment]
@SerhatG35 have you tried `const [ref, inView] = useInView({ triggerOnce: true })`?

**Comment by SerhatG35** [comment]
unfortunately not, im still getting two children with the same key error and i am sure it is because react-intersection-observer because when i remove all related code it works fine.

**Comment by thebuilder** [comment]
@SerhatG35 you should move the `fetchEpisodes` into the `useEffect` - You are recreating the function on each render, but it's not updating inside the `useEffect`.

**Comment by guilhermefront** [comment]
I was using  the hook like this

```js
const { ref, inView } = useInView({ triggerOnce: true });
```

so mocking like this solved to me

```ts
jest.mock('react-intersection-observer');
(useInView as jest.Mock).mockImplementation(() => ({ inView: true }));
```
