### ISSUE TITLE
triggerOnce option not working as expected

### ISSUE THREAD

**Issue by hill84** [thebuilder/react-intersection-observer#188]
I'm tring to use the render props implementation with the triggerOnce option enabled, but the inView prop returned by the function is always true (in the example below it's always rendered `<div>In view</div>` even if at the beginning the element is not visible and I need to scroll down to get to see it). I expected it would be false untill the component would be in view and then true from there on. Am I missing something?

```jsx
<InView triggerOnce={true}>
  {({ inView, ref }) => (
    <div ref={ref}>
      {inView ? <div>In view</div> : <div>Not in view</div>}
    </div>
  )}
</InView>
```

**Comment by hill84** [comment]
It turned out the issue was caused by the development configuration of create-react-app v.2 that delays CSS loading. At first load (when no CSS is applied, and therefore all elements have no height or padding), the component resulted in view for a fraction of a second, before been hide at CSS loading. Production build should solve the issue.

I wonder if there could be an alternative work-around...

**Comment by thebuilder** [comment]
This is an issue with CRA I think. Not sure if they have a solution for it? You could set `triggerOnce={process.env.NODE_ENV === 'production'}` to fix it.
