### ISSUE TITLE
Demo Link

### ISSUE THREAD

**Issue by timarney** [thebuilder/react-intersection-observer#19]
The demo link in the Readme isn't working.

![screen shot 2017-07-19 at 1 51 30 pm](https://user-images.githubusercontent.com/62242/28381610-738b7a20-6c89-11e7-83fb-9fe4b6d84498.png)

**Comment by thebuilder** [comment]
Thanks for letting me know about this! I'll look into fixing it. :)

**Comment by thebuilder** [comment]
Well, updating dev dependencies and rebuilding seems to have fixed it. 🤷
