### ISSUE TITLE
InView always forces a React Tree Reconciliation

### ISSUE THREAD

**Issue by etripier** [thebuilder/react-intersection-observer#195]
The `handleChange` callback always calls `setState` regardless of whether or not the value for `state.inView` will change. This forces a React Tree Reconciliation for each observed component when the tree is mounted (IO calls the callback once for each observed component).

I think an optimization could be made to https://github.com/thebuilder/react-intersection-observer/blob/master/src/InView.tsx#L96:

```
handleChange = (inView: boolean, entry: IntersectionObserverEntry) => {
  if (inView !== this.state.inView || inView) {
    this.setState({ inView, entry })
  }
  if (this.props.onChange) {
    this.props.onChange(inView, entry)
  }
}
```

This would allow the child to receive a new value for `entry` when in view (where it counts), but would prevent the re-render/reconciliation that happens at the very beginning.

What do you think? Am I missing some context here?

**Comment by thebuilder** [comment]
The `IntersectionObserver` only fires a change event when it actually crosses a threshold. So if you only have a single threshold value it will only be triggered when the element enters or leaves view.

If you added multiple thresholds you'll want to to be notified whenever it crosses a threshold - so it needs to update the `state` with the current `IntersectionObserverEntry`, so it can be properly passed along to to the render prop function.

**Comment by etripier** [comment]
My observation is that the component fires a callback as soon as the observer is instantiated (see https://stackoverflow.com/questions/53214116/intersectionobserver-callback-firing-immediately-on-page-load). A component in the viewport will have two callbacks fired - one where `inView` is `false` and another where `inView` is true. Components outside of the viewport will fire only the first callback.

**Comment by thebuilder** [comment]
This is the intended behavior. Are you seeing any actual performance issues because of this? To ignore the first callback would require extra logic, and if I recall correctly, not all (older) browsers trigger it.

**Comment by etripier** [comment]
I think the problem I'm seeing is that the initial callback kicks off `setState({ inView })`, even if it would simply set `state.inView === false` to `false`. That causes a reconciliation which could be avoided.

**Comment by thebuilder** [comment]
Looking at what happens in the Storybook, it only triggers a single `onChange` event, when starting inside the view. Logging out when `onChange` gets called, it also seems like it's only being called once.
https://thebuilder.github.io/react-intersection-observer/?path=/story/intersection-observer--start-in-view

Even if `inView === false` on the initial callback, it still gets the `entry`, that should be set in the state.

**Comment by etripier** [comment]
To clarify what I mean, here's an example (I probably should have led with this):

```jsx
() => {
  console.log('render');
  return (
    <>
      <div className="container">
        <div className="grid">
          {[...Array(40)].map((_, i) => (
            <InView key={i}>
              {({ inView, ref }) => {
                console.log(inView);
                return <div ref={ref} />;
              }}
            </InView>
          ))}
        </div>
        <style jsx>{`
          .container {
            padding: 0 16px 16px;
            width: 100%;
          }

          .grid {
            display: grid;
            grid-gap: 16px;
            grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
          }
        `}</style>
      </div>
    </>
  );
};
```

Rendering the above gives me the following:

<img width="401" alt="Screen Shot 2019-03-09 at 6 46 39 AM" src="https://user-images.githubusercontent.com/7219423/54073335-cc9eb400-423a-11e9-966f-b5a626d7fce0.png">

This is what I would expect and lines up with the built-in behavior for `IntersectionObserver`, like you mentioned.

What is unexpected, however, are the following stack traces:

The first observation:

<img width="1105" alt="Screen Shot 2019-03-09 at 6 56 37 AM" src="https://user-images.githubusercontent.com/7219423/54073368-256e4c80-423b-11e9-8855-b5f30c59be32.png">

The second observation:

<img width="1107" alt="Screen Shot 2019-03-09 at 6 57 00 AM" src="https://user-images.githubusercontent.com/7219423/54073373-2d2df100-423b-11e9-8d81-7b33df233561.png">

In this case the extra work done by React to reconcile a state update of `state.inView` from `false` to `false` for the 22 components below the fold incurs a reasonably significant cost (relatively, at least). I don't need the update to `entry` for those components because they still haven't come in view, either.

**Comment by thebuilder** [comment]
One of the reasons you might want to read the `entry`, even if the component is not inside the viewport, is to let you know that it has triggered the callback. Maybe you need to trigger an animation, only when the element starts outside the viewport.

If you did try to render a heavy component, would using `React.memo` to stop an unnecessary update help?

I have no way of knowing how this library is actually consumed, so maybe it wouldn't be a problem to change the behaviour.

**Comment by thebuilder** [comment]
I went ahead and implemented this check - Let's see if it causes any actual issues. Properly not!

**Comment by etripier** [comment]
Oh, great! Thank you for the fix!

**Comment by ChrisW-B** [comment]
This also seems to happen to the hook still, unless the update hasn't been pushed to npm yet!

**Comment by thebuilder** [comment]
The hook does an extra render when the ref is set. Is this what you're seeing? This is how hooks are designed.

**Comment by ChrisW-B** [comment]
Sorry for the delay! I'm really sorry if this is just me misunderstanding intersection observer, but it seems like if I set `{threshold: [0,1]}`, the component continually sets inView to true when the component is visible, though it only returns one when the component is out of view

**Comment by thebuilder** [comment]
That sounds like the intended behavior. It will trigger whenever it crosses the threshold, and when it doesn't match a threshold. You should look at the entry you also get back, to determine which threshold it just crossed

**Comment by ChrisW-B** [comment]
Thanks again, your most recent update fixed this for me! I was using `[0,1]` assuming I needed it since I wasn't getting an event when the element was no longer visible, but that was a misunderstanding on my part bc of the bug you fixed. Sorry about that!

**Comment by ChrisW-B** [comment]
Thanks again, your most recent update fixed this for me! I was using `[0,1]` assuming I needed it since I wasn't getting an event when the element was no longer visible, but that was a misunderstanding on my part bc of the bug you fixed. Sorry about that!
