### ISSUE TITLE
Cannot find module '/node_modules/react-intersection-observer/dist/react-intersection-observer.cjs.js'

### ISSUE THREAD

**Issue by nicubarbaros** [thebuilder/react-intersection-observer#199]
The folder structure of the library in `node_modules` folder is only this
```
License
package.json
README.md
test-utils.d.ts
test-utils.js
```

Library version
```
 "react-intersection-observer": "^8.22.2",
```

PS: I am loading the parent component dynamically.

**Comment by thebuilder** [comment]
It should also contain the `dist` directory.

You can see the actual content here: https://unpkg.com/react-intersection-observer@8.22.2/

**Comment by nicubarbaros** [comment]
It doesnot have the dist directory.

**Comment by thebuilder** [comment]
Not sure what could be the cause of this. Have you tried to do a clean install of `node_modules`?

This url is generated from the published NPM package, and it contains the `dist` with the correct files:
https://unpkg.com/react-intersection-observer@8.22.2/dist/

**Comment by nicubarbaros** [comment]
Your `gitignore file` has  `/dist` in it. Might this be the issue?

```
.vscode
.cache
.docz
node_modules
reports
example
lib/
dist/
coverage/
nuget
npm-debug.log*
.DS_store
.eslintcache
.stylelintcache
.idea
.tern
.tmp
*.log
test-utils.js
test-utils.d.ts
```

**Comment by thebuilder** [comment]
Nope, it should be fine - `dist` shouldn't be added to the Git repo, because it's compiled from the source.
The files published to npm are referenced inside the `files` in `package.json`.

**Comment by nicubarbaros** [comment]
Really weird, tried multiple clean installs and still nothing on my side. Missing `dist` folder.

**Comment by thebuilder** [comment]
It seems like it's a problem related to your specific NPM installation. I'm going to close for now, but if others experience the same issue, or you can replicate it in an environment like codesandbox.io, i'll open it back up.

Let me know if you figure out what the issue is!
