### ISSUE TITLE
possibility to trigger change if window resized?

### ISSUE THREAD

**Issue by dohomi** [thebuilder/react-intersection-observer#206]
Hello,

I love the simplicity of this package! I am currently experimenting with `useInView` hook and it works very neat. I would like to know if its somehow possible to watch changes on the `entry`. I can read the `entry.boundingClientRect.width` and would love to listen on this changes as well on window resize. Is there any chance or does the IntersectionObserver does not trigger any change?
Cheers

**Comment by thebuilder** [comment]
The `IntersectionObserver` is only triggered when an element crosses the threshold.

So for this use case, you would add a `ResizeObserver` to the element, that notifies you of changes to the size. You could combine it with the `useInView` hook, so it's only active if the element is inside the viewport.

**Comment by dohomi** [comment]
@thebuilder thanks for the heads up - this is how I currently doing it. I thought there might be an option inside of IntersectionObserver but good to hear that I am doing it the right way
