### ISSUE TITLE
Introducing ElementType makes react type version requirement stricter.

### ISSUE THREAD

**Issue by thomasballinger** [thebuilder/react-intersection-observer#208]
The introduction of ElementType in https://github.com/thebuilder/react-intersection-observer/commit/24745375826b5c11706f0dfdde0f559550c88251#diff-e86a5f9747e6341f87c5a59e066766c7R38 causes react-intersection-observer to require very recent version of React types (just added https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e1f9647734bd990f49b0aca0f44acd4d55fe1e93).

I'm not sure what there is to do about this. Could react-intersection-observer be explicitly requiring the right React types?

**Comment by thebuilder** [comment]
Any idea what would be a better type?

**Comment by thebuilder** [comment]
So the new `ElementType` is the correct way of indicating `as` types, and it replaces the deprecated `ReactType`.

I see 3 possible solutions:

1. Leave it as is.
2. Add a peer dependency for the correct `@types/react`. This would show a warning, even if you aren't using TypeScript.
3. Go back to using `ReactType<any>` for now. Looking in the source code, the current definition looks like `type ReactType<P = any> = ElementType<P>;`, so it would be the same.

**Comment by thomasballinger** [comment]
I don't know community norms for types like this / how this usually works. For my particular use case I'd like to go back to using ReactType<any> for say 6 months or so.
