### ISSUE TITLE
Proposal: prop receive inView as decimal

### ISSUE THREAD

**Issue by jpdevries** [thebuilder/react-intersection-observer#224]
So `inView` is a boolean right? So what if I want to know _how much_ something is in view? It seems like it would be nice if in addition to `inView` and `ref` we could also get a property that is a decimal indicating how much it is in view (such as `0.76` which if course resolves to true while 0.0 would not).

**Comment by thebuilder** [comment]
Hey @jpdevries 

An Intersection Observer just tells you when certain threshold of an element is inside the viewport. You can add an array of thresholds, and look at the `entry` you get back, to determine which threshold was crossed. Tracking the exact visible percentage, is something you'd have to build on top using `scroll` event listeners. 

You might be interested in my scroll percentage, that builds on top of the intersection observer:
https://github.com/thebuilder/react-scroll-percentage

It gives you a percentage of how far the element has been scrolled into the viewport.

I've made a new Hook version, that i'll integrate into the existing library once i have time for it, but you can find it here:
https://www.npmjs.com/package/@charlietango/use-scroll-percentage

**Comment by jpdevries** [comment]
Oh wow. That's amazing. I'll give that a go. Thanks @thebuilder
