### ISSUE TITLE
How to use the hook with a "scroll parent" implementation.

### ISSUE THREAD

**Issue by danoc** [thebuilder/react-intersection-observer#225]
Hello!

I'm moving away from `react-waypoint` and am looking to keep their default [`scrollableAncestor` prop](https://github.com/civiccc/react-waypoint#prop-types) behavior of finding the nearest scroll parent.

How could I do this with `react-intersection-observer`? I'm confused because I don't have access to the ref.

```js
const [ref, inView] = useInView({
    threshold: 0,
    root: scrollparent(???), // https://www.npmjs.com/package/scrollparent
});
```

**Comment by danoc** [comment]
Got this to work by calculating the `root` in the parent component and passing the `root` in as a `ref`. Works well for my case, but I'd love for that to be part of the component itself.

***
Nice work with this library, by the way. Great README and clearly well maintained.

**Comment by thebuilder** [comment]
The default `root` is the same as the Intersection Observer API's default value (`window`), and I think this is also what makes sense for most use case.

There are multiple ways of getting a `ref` to the scroll container you want. If it's all contained inside the same component, you should be able to use a `ref` you assign to the root:

```js
function ScrollComponent() {
  const rootRef = useRef()
  const [ref, inView] = useInView({root: rootRef.current})

  return <div className="root" ref={rootRef}>
    <div ref={ref}>Inner</div>
  </div>
}
```

**Comment by danoc** [comment]
Ah, great. That's exactly what I needed. Thanks! 🙇
