### ISSUE TITLE
No exposed way to get a ref to the underlying element

### ISSUE THREAD

**Issue by calinoracation** [thebuilder/react-intersection-observer#229]
I'm building a carousel and need to do some work to set scrolling positions and determine the active slide, so currently I have a `<ul>` by using `<InView as="ul" />` and the same for my `<li>` elements inside it. I'd really rather not put wrapper element's inside the `<li>` and double my DOM node count just for the purpose of the intersection observer, so currently my solution is to add a `ref={setMyRef}` attribute and then grab the `.node` property off of it. That's a private implementation detail and definitely not a great solution, so I'm hoping for the addition of some way to pass a `ref` to it in another way. The other little annoyance here is that when using `as`, the type signature is still `HTMLDivElement` and not `ul` or `li`. That's a bit less of a big deal but I wanted to point it out.

```tsx
<InView as="ul" ref={this.setListRef} />

private setListRef = (el: InView) => {
  // @ts-ignore
  const node = el && (el.node as HTMLUListElement);
  this.listRef = node;
};
```

**Comment by calinoracation** [comment]
As per the types, we're on `8.22.5` and I see some changes in the following release and perhaps our usages that may potentially fix that, but the ref to the underlying element seems to still be an issue.

**Comment by thebuilder** [comment]
I'd highly recommend you use either the the `useInView` hook, or the [Render Props](https://github.com/thebuilder/react-intersection-observer#render-props) to solve this. They give you full control over the DOM you're rendering, and allows you to control the `ref`. 

The plain children version you're using is more useful when don't really care about the details (like `ref`).

**Comment by calinoracation** [comment]
I think that's fair, we can't utilize hooks yet due to React version and tended to prefer the plain children version over the `Render Props`, but I can make the switch to the render prop version today if that's the preferred route. Thanks for the response, and we're making a ton of usage out of this library, thank you very much for all the work on it!!
