### ISSUE TITLE
Support multiple thresholds

### ISSUE THREAD

**Issue by calinoracation** [thebuilder/react-intersection-observer#231]
One thing I think would be really useful is to be able to detect when something is at multiple thresholds, so for example when something is either fully in view or not I might use something like the following:

```tsx
<InView threshold={[1, 0]} onChange={someHandler}>...</InView>
```

For something like determining when a new slide comes in for a carousel, I might use values like `.51` to know when the slide passes the 50% threshold, but also a value of `1` so I know when its snapped into place fully for impression tracking. So in that case values of `[.51, 1]`. Since `IntersectionObserverEntry` already contains `intersectionRatio`, I would have all of the information necessary to determine which one triggered it in my event handler with no changes to the `onChange` API.

Is that something ya'll would be open to in terms of functionality and/or pull requests?

**Comment by thebuilder** [comment]
Hey @calinoracation 

The `<InView>` component should already support both single threshold and array of threshold values. You also get the `IntersectionObserverEntry` that allows you to read the `intersectionRatio`. 

```js
const Component = () => (
  <InView threshold={[0, 0.5, 0.75]}>
    {({ inView, ref, entry }) => (
      <div ref={ref}>
        <h2>{entry.intersectionRatio}</h2>
      </div>
    )}
  </InView>
)
```

Is this what you are looking for? I guess it could be a bit more clear in the `readme` that you can get the `IntersectionObserverEntry ` back.

**Comment by calinoracation** [comment]
Oh, that's jazzy, I didn't realize it. Just tried it out and it worked! Thank you! Sadly it's not super useful from what I can tell, looking at the `intersectionRatio` it was never exact and sometimes dangerously off to be able to distinguish. With a perf throttling to 6x, a `.6` threshold would sometime be _just_ over `.5`, we assume it's because it's likely being calculated in an animation frame, so while we tried to use `toFixed(1)`, but it seemed dangerous. Even a threshold of `1` was not always `1` and sometimes `.99`ish. That said, for some scenarios this will be great, so many thanks!

**Comment by thebuilder** [comment]
Yeah, that's just how the browsers implement it. It's more of a hint that a threshold was crossed. 
It might work to floor the intersection ratio, to the nearest threshold ratio? Or you could look at the element bounds and do your own calculations. 🤔

**Comment by calinoracation** [comment]
We looked at the bounds to try to calculate it, but from what we could tell the ratio was calculated based on the bounds. flooring it wouldn't of worked either, since we specify a threshold of `0.6` and flooring `0.5xxxx` would be wrong, and on slower devices might be even lower. We considered using a range of values, but that seemed brittle.

**Comment by thebuilder** [comment]
Hey @calinoracation 
Just an idea, maybe a better solution would be to add an Intersection Observer for each slide in your carousel.
This would allow you to know exactly which slides are visible, triggering an `onChange` for each of them.

The same `IntersectionObserver` instance is reused as long as they have the same options, so don't worry about performance. This is what it was made for.
