### ISSUE TITLE
Breaking API change without major release

### ISSUE THREAD

**Issue by bogdansoare** [thebuilder/react-intersection-observer#237]
I'm sad when I see libraries not respecting semver.

I'm using the Observer api `<Observer onChange />` in the 8.22.5 version and after I've updated to 8.23.0 I get an error that module can't be found, weird I say, let's check the github for the docs. Surprise, the API has been changed without any breaking change

**Comment by thebuilder** [comment]
Can you provide more details? 
You shouldn't have any breaking changes in between those versions.

**Comment by bogdansoare** [comment]
Hey Daniel, sorry for the tone in my issue, you're right, there are no breaking changes, I don't know why yarn, after I upgraded the package, couldn't seem to find the default export anymore. My apologies for the confusion, keep up the good work with this library.

**Comment by thebuilder** [comment]
Good to know - I do try to to respect semver (that's why the library is at version 8.x now), but there is always the possibility that I overlooked something.
