### ISSUE TITLE
How to combine useInView with debounce?

### ISSUE THREAD

**Issue by patrykkarny** [thebuilder/react-intersection-observer#238]
Hi, do you have an idea of how to combine `useInView` with `debounce` to decrease rerenders when quickly scrolling through the list of components which are using Intersection Observer?

**Comment by thebuilder** [comment]
I'm guessing you want to delay the update after the element enters the viewport. So you don't really want to `debounce` the method, but create a `setTimeout` that can be cancelled. 

The `useEffect` for could look like this, where you trigger it with the `inView` value from the `useInView` hook:

```js
useEffect(() => {
  if (inView) {
    const timeout = setTimeout(() => {
      // Update state, to trigger a rerender here
    }, 500)
    return () => clearTimeout(timeout)
  }
  return undefined
}, [inView])

```

**Comment by say8425** [comment]
I just increase overscan that can help reducing observing failure.
