### ISSUE TITLE
Multiple thresholds triggering too often

### ISSUE THREAD

**Issue by herrstucki** [thebuilder/react-intersection-observer#248]
If I understand the spec correctly, specifying a threshold array should trigger _only_ when the specified thresholds are crossed.

A simple example: `threshold: 0.5` and `threshold: [0.5]` should act the same. `threshold: [0, 1]` should trigger only twice when scrolling in one direction.

In this library however, the `entry` changes constantly when an array is specified. Am I overlooking something or is this a bug?

Repro here: https://codesandbox.io/s/ecstatic-johnson-o75in

**Comment by herrstucki** [comment]
OK, so I figured out the issue 😅 When using an inline array in the options (that will change identity in each render), the use of `useEffect`'s dependencies will unobserve/observe in each render.

So this doesn't work as expected:

```js
const Foo () => {
  const [ref, inView, entry] = useInView({threshold: [0.5]});
}
```

but this does:

```js
const THRESHOLD = [0.5];
const Foo () => {
  const [ref, inView, entry] = useInView({threshold: THRESHOLD});
}
```

Source: https://github.com/thebuilder/react-intersection-observer/blob/796129248cccff01395d3d77e079a9e0c81a1e37/src/useInView.tsx#L43

**Comment by thebuilder** [comment]
Not sure if there's a good solution for this - But maybe I should add a note about it the readme.

**Comment by herrstucki** [comment]
Yeah, I also don't know of a good solution. Maybe it's good to recommend to keep the whole options  object constant …

Probably a bad idea (I don't know what happens when the length of the dependencies array changes) but I wonder if spreading the array into useEffect's dependencies would work:

```js
useEffect(() => {}, [foo, bar, ...threshold])
```

**Comment by herrstucki** [comment]
OK, nevermind, the length of the useEffect dependencies array can't change between renders 🤷‍♂

**Comment by fabb** [comment]
Alternatively, in `useInView` you can use `JSON.stringify(options.threshold)` instead of `options.threshold` in the dependency array. That requires silencing eslint though.

**Comment by herrstucki** [comment]
@fabb Better (if thresholds are even changing) is probably `useMemo` (less overhead than calling JSON.stringify on each render, works properly with ESLint and TypeScript):

```js
const threshold = useMemo(() => [0.5], []);
const [ref, inView, entry] = useInView({ threshold });
```

**Comment by fabb** [comment]
That‘s only possible on call-side, so users of the hook need to comply. Using `JSON.stringify()` inside the hook would abstract that away from users. Tradeoff between resilience and performance overhead.
