### ISSUE TITLE
Detect is element is below another in css z-index stack

### ISSUE THREAD

**Issue by adamjw3** [thebuilder/react-intersection-observer#252]
Love the hook for this helper. I have a use case where i have an initial message on the page that then animates out revealing the rest of the site. similar to https://www.makereign.com/

I have a function to detect if the element is not behind another element https://jsfiddle.net/adamjw3/u3b0rcsf/30/

Would love to add it all to one hook, what do you think?

**Comment by thebuilder** [comment]
I'm not sure i follow. Are you asking how to implement that logic in your own custom hook?

**Comment by adamjw3** [comment]
I can create a custom hook but thought it might be good to add for this plugin. 

What do you think?

**Comment by thebuilder** [comment]
The intention of this library is expose a clean way of using the IntersectionObserver API in React applications. The library shouldn't start to expose custom features on top of this.

**Comment by adamjw3** [comment]
I know this is closed but we now have https://web.dev/intersectionobserver-v2/ will this module be updated to use this?

**Comment by thebuilder** [comment]
This has been added:
https://github.com/thebuilder/react-intersection-observer#intersectionobserver-v2-

Keep in mind browser support is very limited.
