### ISSUE TITLE
Allow use with React.forwardRef

### ISSUE THREAD

**Issue by rileyjshaw** [thebuilder/react-intersection-observer#264]
First off, thanks for providing such a thorough & well documented implementation! It's worked great so far for all kinds of use cases.

I can't seem to get the hook to work with `React.forwardRef`. Specifically, I'm trying to pass the `ref` to an externally defined component like so:

```
import React from 'react';
import {useInView} from 'react-intersection-observer';

const WrapperHOC = React.forwardRef(({children, ...props}, ref) => (
	<div {...props} ref={ref}>
		{children}
	</div>
));

export default () => {
	const [ref, inView] = useInView({threshold: 0.3});
	return (
		<div>
			<WrapperHOC style={{color: inView ? 'red' : 'black'}} ref={ref}>
				Always red?
			</WrapperHOC>
		</div>
	);
};
```

After reading https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780, I'm starting to think this could be due to `ref` not being updated in the right order for capturing the HOC.

Apologies if this is already covered in https://github.com/thebuilder/react-intersection-observer/issues/162 or https://github.com/thebuilder/react-intersection-observer/issues/186, feel free to close it if it's redundant.

**Comment by rileyjshaw** [comment]
Okay, turns out my previous example was overcomplicated. This seems to be an issue with wrapping components.

The following example works:
```
import React from 'react';
import {useInView} from 'react-intersection-observer';
export default () => {
	const [ref, inView] = useInView({threshold: 0.5});
	return (
		<div ref={ref}>
			<span style={{color: inView ? 'red' : 'black'}}>Turns red.</span>
		</div>
	);
};
```

The following example does not:
```
import React from 'react';
import {useInView} from 'react-intersection-observer';
export default () => {
	const [ref, inView] = useInView({threshold: 0.5});
	return (
		<div>
			<div ref={ref}>
				<span style={{color: inView ? 'red' : 'black'}}>
					Always red?
				</span>
			</div>
		</div>
	);
};
```

Happy to give more detailed info, but I feel like I'm fundamentally misunderstanding something here.

**Comment by rileyjshaw** [comment]
This magically fixed itself over the weekend. Sorry for the noise!

**Comment by thebuilder** [comment]
Stuff that's broken on a friday, tends to work first thing on mondays. 🧙‍♂️
