### ISSUE TITLE
Do you create multiple listeners or just one

### ISSUE THREAD

**Issue by ScriptedAlchemy** [thebuilder/react-intersection-observer#267]
Looking at using this tool. But wanted to ask, do you create a new intersection observer listener every time i use `InView`. Id like to avoid adding multiple listeners. Can you provide any info on this

**Comment by thebuilder** [comment]
IntersectionObserver instances are reused between `<InView>`, as long as the options are the same  (`threshold`, 'root` and `rootMargin`) - So yes, it only creates the minimum amount of listeners needed.

**Comment by ScriptedAlchemy** [comment]
Beautiful work 🥰
