### ISSUE TITLE
Observer onChange gets called on text input `change` events

### ISSUE THREAD

**Issue by eljusto** [thebuilder/react-intersection-observer#269]
When you type something in the text input contained inside of the observer, onChange callback is getting called.

Here is a code example: https://codesandbox.io/s/v0p7c

This occurs in bubbling phase of React event dispatching
 ![react_debug](https://user-images.githubusercontent.com/380726/64174982-0efc2300-ce63-11e9-9a1f-d3f052ea0258.png)

**Comment by thebuilder** [comment]
That's interesting - not sure what is going on. Looks like, maybe the wrapping `<div>` catches the bubbling `onChange` event?`

I'd reccomend you try using the render function approach or hook instead if possible. Will need to dig into what's going on here.
