### ISSUE TITLE
Recipe.md typo? (minor)

### ISSUE THREAD

**Issue by wilbsy** [thebuilder/react-intersection-observer#275]
Trigger animations & Track impressions recipes both use `rootMargin: '-100px 0'` which causes the following error:  
> 'IntersectionObserver': rootMargin must be specified in pixels or percent

Seems like a simple typo...  adding 'px' (ie `rootMargin: '-100px 0px'`) solved it for me.

For reference to typo locations:
https://github.com/thebuilder/react-intersection-observer/blob/master/docs/Recipes.md#trigger-animations
https://github.com/thebuilder/react-intersection-observer/blob/master/docs/Recipes.md#track-impressions

@thebuilder 
Just thought I'd let you know.
Thanks for the great packages!  :)

**Comment by thebuilder** [comment]
Good catch - For some reason the Intersection Observer api is bit more picky about the margin having `px`.
