### ISSUE TITLE
Some tests break even when mocking IntersectionObserver

### ISSUE THREAD

**Issue by eslachance** [thebuilder/react-intersection-observer#279]
Hello,

I'm having a bit of an issue with testing, using react-intersection-observer. I'm using it in a component that's being used by many different other "blocks" (it's a short video preview appearing when a "card" is in view, otherwise it's a still thumbnail). 

The module works perfectly well, at least for the current needs we have. However, testing isn't going so great. I'm using Jest and I added the test-utils mock to a centralized utility we use to create a mock app used everywhere. This createMockApp util and the new IO mock work almost perfectly - without the mock I get 52 failed tests saying "IntersectingObserver is not defined"... with it, I hoped to go to 0, but for some reason it's 5.

For privacy reasons, it's impossible for me to share the project. I'd like to share parts of it, but at 50k+ lines of code and about 12 different files involved in just showing this one card component, any code will be pretty limited. However, I can share one particular component where it's extremely strange: some tests work, others don't, in the exact same testing file. Here's the test itself: https://text.evie.codes/wuxatiyavo.js and here's the output from the `console.log(IntersectionObserver)` lines that I have in my card component: https://text.evie.codes/opohinayap.js . The Card component itself, currently the useInView is commented so I get a useful logging output without a crash: https://text.evie.codes/akudefohug.js

It's extremely strange to me that there are 3 outputs with undefined, and the rest show something (a function which I assume is the mock output). 

I'm wondering if anyone can assist in determining what's going on here.

**Comment by eslachance** [comment]
Update: As a test, I took the block that defines global.IntersectionObserver and the 2 maps and threw it in my createMockApp file... and the tests are now functional. 

Theory: Something in the process of the mock (the beforeAll() maybe?) is asyncronous and causes it to be undefined for a short amount of time. This wouldn't directly explain the fact that it's not the first test that fails, others later also fail, but it seems like it's a good hint, perhaps?

**Comment by thebuilder** [comment]
Hard to say why it breaks. But if it works for you to copy the test utils into your own project, then that's perfectly fine?

**Comment by eslachance** [comment]
The only way I've gotten it to really work, is if I am actually setting `global.IntersectionObserver` outside of any testing. Using the beforeAll() fails in any test using it.

**Comment by thebuilder** [comment]
When are you loading the `test-utils.js`? 
Have you tried loading it in the specific tests that need it, instead of adding it to your centralized utility file?
If you want to load it for all tests, you should have it in a Jest setup file:
https://jestjs.io/docs/en/configuration#setupfilesafterenv-array

I'd love to help, but if the issue is that `IntersectionObserver` is `undefined`, then it has be related to how your specific setup is loading the file - `beforeAll` is executed before your tests, so `global.IntersectionObserver` will be set to the mock if `test-utils.js` was imported.

**Comment by eslachance** [comment]
Essentially, for some tests it doesn't seem to matter at all *when* I load the test-utils, it will not work whatever I do. For instance, here's my CategoriesListBlock.spec.js file. It fails due to the above error (IntersectionObserver is not defined). It's in 3 different places, including the 2 shown.

![image](https://user-images.githubusercontent.com/643344/67212315-30e93f00-f3ea-11e9-8029-7c73787fa1e3.png)

**Comment by thebuilder** [comment]
You are accessing the mock function outside a `test` or `it` block - could explain why `beforeAll` is not triggered?

**Comment by eslachance** [comment]
Ohhhhhh I see exactly what you're saying. Indeed, because it wasn't in beforeAll, those tests failed. I've modified the code so that the createMockApp was called in beforeAll() and it works great! 

Sorry for the trouble, and thank you *very much* for this awesome implementation :D
