### ISSUE TITLE
Hand `ref` back

### ISSUE THREAD

**Issue by coreyward** [thebuilder/react-intersection-observer#281]
It'd be great if the useInView hook returned the actual ref object so it could be used elsewhere. I need access to `ref.current` for some bounding rect measurements after `inView` is true, and while wrapping the callbacks and assigning a second ref works it's a bit clumsy to follow.

**Comment by matt-d-rat** [comment]
@coreyward Just ran into the same problem. For the time being, how are you working around this? I need to support a `forwardRef` and the `setRef` callback returned by `react-intersection-observer`

**Comment by thebuilder** [comment]
You could try to use https://github.com/smooth-code/react-merge-refs/ To manage it.

**Comment by thebuilder** [comment]
The thing is, it's using a ref callback function - not a `React.RefObject`, so it can't just return a ref object.
If you just need the DOM element, then you can access it from [entry.target](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry) once that is set.

**Comment by coreyward** [comment]
@thebuilder The hook returns a callback ref now, but you actually create a ref object and assign its `current` value in the hook. I just want that ref object returned as an additional piece of information. I’d be fine with adding `current` as a property on the ref callback function even, just helping it quack more like a hook ref (i.e. `callbackRef.current = ref.current`)

**Comment by thebuilder** [comment]
I can see how `callbackRef.current = ref.current` would work, but it's going to be a hack, and getting TypeScript types to play nicely with it is going to be a challenge. 🙂

I'm also a bit vary about adding more fields to the return array from the hook. I'm afraid it would just be more confusing for most users, if there's two `ref` values in the array. 

Again, you should already get a reference to the DOM node inside the [entry.target](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry).  That would be the exact same result you get from looking at `ref.current`.
