### ISSUE TITLE
useInView() doesn't return a proper ref object

### ISSUE THREAD

**Issue by maranomynet** [thebuilder/react-intersection-observer#285]
I was trying to reuse the `ref` returned by the `useInView()` hook, and realized it isn't a ref object, but an old-schoolish ref-function, that returns `void`.

This causes annoying hoop-jumping*, which wouldn't be necessary if `useInView()` used `useEffect` internally to grab `ref.current` and set up the observation.

----

*) i.e. creating a separate `myRef` object, and then adding this custom `ref` prop to the observed element `ref={(elm) => { myRef.current = relm; inViewRef(elm); }}`

**Comment by thebuilder** [comment]
Hey @maranomynet 

This is intentional, and the recommended approach by the React team - See:
https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node
https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780

It allows the hook to be notified when the `ref` changes.

**Comment by maranomynet** [comment]
Thanks for the explanation.
This recommendation is interesting. I don't understand why reading the value of `ref.current`, and passing it as dependency to `useEffect` wouldn't suffice to pick up on changes to the red's placement in the DOM.

**Comment by maranomynet** [comment]
... sorry, didn't read the second link before posting.
so it's a trick to reduce lag and/or the need for a second render pass. Ok

**Comment by maranomynet** [comment]
Actually, React's behavior is just downright weird.
https://codesandbox.io/s/ref-and-hooks-1viwi

It runs the useEffect callback for #initial twice - even though its ref.callback **did not** change, but doesn't run the effect callback for #lazy even tough its ref.callback **did** change during the second render - before the second useEffect phase.

**Comment by ajayns** [comment]
I read the article and I'm still a bit confused on how to make use of refs with useInView. Consider the following code snippet:

```javascript
const [ref, inView] = useInView({ threshold: 0 });

  useEffect(
    () => {
      if (inView) {
        ref.current.style.tranform = 'rotate(10deg)';
      }
    },
    [inView]
  );
```

**Comment by thebuilder** [comment]
`ref` is a callback function, and doesn't contain the `current` value. What you can do, is look at the `target` from the [IntersectionObserverEntry](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/target)

```js
const [ref, inView, entry] = useInView({ threshold: 0 });

  useEffect(
    () => {
      if (inView) {
        entry.target.style.tranform = 'rotate(10deg)';
      }
    },
    [inView]
  );
```
