### ISSUE TITLE
Change introduced in 8.24.1 causing component to re-render infinitely

### ISSUE THREAD

**Issue by danoc** [thebuilder/react-intersection-observer#291]
Hi! 

We're using this library at Thumbtack in our `Image` React component and noticed that a change in `v8.24.1` was causing our component to infinitely re-render. We're using `inViewRef` and I suspect that it started to break [because of this commit](https://github.com/thebuilder/react-intersection-observer/commit/b31487b0c796cf35ecd3faaaa61da743a6abe9a2).

I was able to fix the issue in our end by changing the approach we use to combine multiple refs into one. [The `useCallback` suggestion](https://github.com/thebuilder/react-intersection-observer#how-can-i-assign-multiple-refs-to-a-component) seemed to work: https://github.com/thumbtack/thumbprint/pull/634

It's possible that there's not actually an issue with `react-intersection-observer` here and that my initial non-useCallback approach of combining refs was incorrect. Either way, I figured it'd be helpful to make an issue here in case other folks run into this.

Thanks for the library!

**Comment by thebuilder** [comment]
Good to know. 👍

**Comment by danoc** [comment]
Will close since I imagine there isn't any action item here. 🤝
