### ISSUE TITLE
Mount when inView?

### ISSUE THREAD

**Issue by kobsTheReal** [thebuilder/react-intersection-observer#293]
Is it possible to mount the children when in view? 
That would be great to defer a bunch of elements. But It would mean that it needs some kind of placeholder with the same size.
Any idea?

**Comment by thebuilder** [comment]
It's a great idea to use an intersection observer to do this - But as you mention, you'll want a placeholder element with the same size. You can use this placeholder element to assign the `ref` for the IntersectionObserver. Use `triggerOnce` so the element isn't removed again later.

See the [Lazy Image load recipe ](https://github.com/thebuilder/react-intersection-observer/blob/master/docs/Recipes.md#lazy-image-load) for an example.

**Comment by kobsTheReal** [comment]
Thanks for the response. Here's what I've done with a bit of mobx help, please let me know if there is something that could be improved:

```
import React from 'react';
import { InView } from 'react-intersection-observer';
import { observable, action } from "mobx";
import { observer } from 'mobx-react';

@observer
export default class Lazy extends React.Component {

    @observable visible = false

    @action
    setVisible(inView) {
        if (inView) {
            this.visible = true
        }
    }

    render() {
        return <InView {...this.props} as="div" triggerOnce={true} onChange={(inView, entry) => { this.setVisible(inView) }}>
            {this.visible ? <React.Fragment>{this.props.children}</React.Fragment> : <div style={{ minHeight: this.props.placeHolderHeight, width: "100%" }}/>}
        </InView>
    }
}
```
