### ISSUE TITLE
How to fire a init callback to check if component is in view at page load ?

### ISSUE THREAD

**Issue by GaddMaster** [thebuilder/react-intersection-observer#295]
I have an issue where all my components are triggered as in view, as they load in stacked so each component gets a small top of page slot.

How do we check if a component is in the view from the start when [age loads. I have to leave its view before the on change fires

Daniel

**Comment by thebuilder** [comment]
This is really just the `IntersectionObserver` doing what it should (inform you that the elements are inside the viewport). 

I'm not sure what exactly you mean by "stacked", but if you are adjusting the layout after the initial render, then you will have to delay starting the hook.

See this similar question from a few days ago: https://github.com/thebuilder/react-intersection-observer/issues/294

**Comment by GaddMaster** [comment]
What I meant by stacked.....(Bad expression) ->
Components randomly loaded into the DOM. We see the lower ones sometimes load in before the higher ones. Example. Article ->
-Banner
_Title
-Body
-Interactions
-Tags
-Teasers
Now we may see teasers and tags in the viewport for a split second before the top ones load in. The result for me is all are marked as been viewed.

**Comment by GaddMaster** [comment]
I think my question is different from that shared link to a similar question.
I need to trigger a callback for components that are in view on page init and remain there even after the page has fully loaded and settled. I also need delay so I left a comment in #294
