### ISSUE TITLE
Add support for external refs

### ISSUE THREAD

**Issue by droganov** [thebuilder/react-intersection-observer#301]
Hi
I faced a design problem, I need to use react forward ref object, how do I do that?

**Comment by thebuilder** [comment]
See the FAQ: https://github.com/thebuilder/react-intersection-observer/blob/master/README.md#how-can-i-assign-multiple-refs-to-a-component

If you are using the `<IntersectionObserver>` then it doesn't support ref forwarding. You should use the children as function style, so you render your own child (that can handle ref).
