### ISSUE TITLE
inView stays true when component is unmounted

### ISSUE THREAD

**Issue by chapa** [thebuilder/react-intersection-observer#303]
Hello,

When the component holding the `ref` is unmounted while it was visible, the `inView` stays `true`.

Here's a fork of your basic example using `useInView` : https://codesandbox.io/s/react-intersection-observer-2rdzd
Click on the button to unmount the `<Wrapper>` component which holds the `ref`, the status at the top-right corner stays green

**Comment by thebuilder** [comment]
That's a use case I haven't considered. Makes sense that it clears the state.
Should be a matter of resetting the state if the `ref` changes.
