### ISSUE TITLE
Make polyfill optional when using in old browsers

### ISSUE THREAD

**Issue by trotzig** [thebuilder/react-intersection-observer#307]
Hi there! First of all, thanks for providing the library - it's excellent!

I have an idea that I'd like to vet with you. I recently used the lib in a website to make a sticky nav. To prevent the site from breaking I need to make it work in IntersectionObserver-less browsers (like IE). Now, I don't actually care if the nav is sticky in these browsers, I just want my code to run. Adding the polyfill is of course an option, but there's no optimal way of adding the polyfill without also affecting performance (slightly) for modern browser.

So here's my idea: make the default behavior of the library so that it will report `inView: true` for browsers where IntersectionObserver isn't supported. Optionally, we could hide it behind a configuration option of some sort. This will make more things just work™️ when the intersection observer behavior is an enhancement and not a requirement. 

With a pointer or two, I'd be happy to come up with a PR for this.

**Comment by thebuilder** [comment]
> Adding the polyfill is of course an option, but there's no optimal way of adding the polyfill without also affecting performance (slightly) for modern browser.

There's plenty of ways to only include it in browsers that need the polyfill. Doing a feature detection before loading the polyfill is one way. https://github.com/thebuilder/react-intersection-observer#polyfill

I believe it's better to throw an error if the implementation is missing, than assume the usage is purely enchantments. 

You could create a custom extension of the hook that checks for support, and returns `inView = true`. This could be changed to instead lazy load the polyfill, before returning the correct `hookResult`.

```js
function useInViewFallback(options) {
  const hookResult = useInView(options);
  
  if (typeof window.IntersectionObserver === 'undefined') {
    // Unsupported, return no `ref` and default `inView` true value
    return [undefined, true];
  }

  return  hookResult
}
```

**Comment by trotzig** [comment]
Thanks! Yeah that seems like a reasonable workaround, it's similar (but simpler) to the one I ended up using. Agreed about failing hard being better than silently working around. The problem here is most people don't test in intersection-less browsers and so they often end up with broken experiences for a percentage of their users, and they'll never know about the error. 

Tagging on to your idea about lazy-loading the polyfill, would it make sense to provide the `useInViewWithPolyfill` hook from this library? We could lazy-load `https://polyfill.io/v3/polyfill.min.js?callback=cb&features=IntersectionObserver` for old browsers.

**Comment by thebuilder** [comment]
If using polyfill.io, i would add it as a `<script>` in the HTML so you are sure the polyfills you need are loaded.

**Comment by trotzig** [comment]
Sure, but that leads to an unnecessary (potentially blocking) roundtrip to polyfill.io, even for browsers that have intersection observer.

**Comment by thebuilder** [comment]
Sure - the question is really how you want to handle polyfills in your application. Using a defered polyfill.io script is one way. Make sure to `<link rel="preload">` it to fetch it as early as possible in modern browsers.

Are you already including corejs, a better solution might be to check for extra polyfills before you call `React.render`, and delay rendering untill they are imported.

**Comment by baddox** [comment]
> I believe it's better to throw an error if the implementation is missing, than assume the usage is purely enchantments.

That makes sense, but how can we do that with the `useInView` hook? It does seem to work okay to check for support and return an `<img />` before calling the hook, but that violates the rule that hooks should always be called unconditionally and the React hook lint rules don't like it. I can't seem to find what the best practices are around handling errors in hooks.

**Comment by baddox** [comment]
Here I found Danny A recommending to use another component with an error boundary. I suppose that makes sense.

https://github.com/facebook/react/issues/16026#issuecomment-507767582

**Comment by thebuilder** [comment]
You'd wrap you application/component in an error boundary. But that would just stop it from breaking other parts of the application. I'm also not sure it would trigger the error boundary, since it happens as a side effect (not the render method itself).

**Comment by baddox** [comment]
Am I crazy here? For the moment I'm just going to use an error boundary, roughly like this:

```jsx
import { ErrorBoundary } from 'react-error-boundary';

const LazyImageThatThrowsErrors = ({ src }) => {
  // This hook throws a runtime error if the browser doesn't support
  // IntersectionObserver.
  const [ref, inView] = useInView();
  return <img ref={ref} src={inView ? src : undefined} />;
};

const LazyImage = ({ src }) => {
  return (
    <ErrorBoundary FallbackComponent={() => <img src={src} />}>
      <LazyImageThatThrowsErrors src={src} />
    </ErrorBoundary>
  );
};

```

**Comment by baddox** [comment]
> You'd wrap you application/component in an error boundary. But that would just stop it from breaking other parts of the application. I'm also not sure it would trigger the error boundary, since it happens as a side effect (not the render method itself).

My goal is to have browsers which don't support IntersectionObserver to simply revert to normal `<img src="foo.jpg" />` behavior.

**Comment by thebuilder** [comment]
> 
> 
> Am I crazy here? For the moment I'm just going to use an error boundary, roughly like this:
> 
> ```js-jsx
> import { ErrorBoundary } from 'react-error-boundary';
> 
> const LazyImageThatThrowsErrors = ({ src }) => {
>   // This hook throws a runtime error if the browser doesn't support
>   // IntersectionObserver.
>   const [ref, inView] = useInView();
>   return <img ref={ref} src={inView ? src : undefined} />;
> };
> 
> const LazyImage = ({ src }) => {
>   return (
>     <ErrorBoundary FallbackComponent={() => <img src={src} />}>
>       <LazyImageThatThrowsErrors src={src} />
>     </ErrorBoundary>
>   );
> };
> ```

That might work? Honestly, I would just do a check for Intersection support, and adjust accordingly:

```js
const Image= ({ src }) => {
  const [ref, inView] = useInView();
  const unsupported = typeof window.IntersectionObserver === 'undefined'
  
  return <img ref={!unsupported  ? ref : undefined} src={inView || unsupported  ? src : undefined} />;
};
``` 

As long as you don't assign the `ref`, the hook will IntersectionObserver will never be instantiated.
This example will fail if rendered serverside - Move the check into a `useEffect` if you need to do that.
