### ISSUE TITLE
v 8.26.0 results in sudden false attribute even element is inView

### ISSUE THREAD

**Issue by dohomi** [thebuilder/react-intersection-observer#311]
Hi

I updated from 8.25.3 => 8.26.0 and all of sudden a container is returned into `false` state after it was true. I use `triggerOnce` attribute but not sure which one was causing it.
```js
  const [refIntersectionObserver, inView] = useInView({
  triggerOnce: true,
  rootMargin: '400px 0px 400px 0px'}
  )

  const getImageSrc = (image: string) => imageService(image, '0x' + height)
  console.log(inView) // triggered false, true and false again even though its inside of visible area
  const Logo = (
    <div className="h-100 d-inline-block" ref={refIntersectionObserver}>
    (...)
    </div>
```
Downgrade to 8.25.3 works for me to show the container again

**Comment by thebuilder** [comment]
That doesn't sound good - I'll look into it!

**Comment by thebuilder** [comment]
Can you make a codesandbox example?

This might potentially be the library working correctly - If the `ref` is ever removed/changed it will reset the inView status. I guess there might be an argument to make that it shouldn't do that if it's set to `triggerOnce`.

**Comment by dohomi** [comment]
@thebuilder sorry I am currently in Asia so I haven't had the chance to make a codesandbox. But your current v8.26.1 fixed it in my usecase thanks a bunch
