### ISSUE TITLE
Allow custom attributes on InView

### ISSUE THREAD

**Issue by chaitu9916** [thebuilder/react-intersection-observer#315]
* Could you pass on custom attributes set on <InView /> to the 'as' type element.

Example:
   ` <InView key={id} as="div" id={id} threshold={0.95} onChange={inViewCallBack} custom-attribute={someValue} />`

Output:
`      <div id="id" custom-attribute="someValue" />
`

**Comment by thebuilder** [comment]
All rest props are forwarded to the html component. Have you tried this?

**Comment by chaitu9916** [comment]
Yes, my bad. It does work. Thank you.
