### ISSUE TITLE
Question:Observe multiple target and take Ref instead of element as input.

### ISSUE THREAD

**Issue by chaitu9916** [thebuilder/react-intersection-observer#318]
* Considering i have a table such as - [Link](https://engineering.cerner.com/terra-ui/raw/components/terra-clinical-data-grid/clinical-data-grid/datagrid-examples/datagrid-with-subsections)
* If i would like to detect the visibility of each column 
  * `<InView root={node} key={columnId} as="div"threshold={0.95} onChange={inViewCallBack} column-id={columnId} />`
  * I will have to use useEffect/onComponentMount and have a local state variable store the element from ref.current value. Thus triggering a render on parent component wrapping all the columns. 
  * That could be avoided if InView accepts a ref?

  * Is it possible to have one trigger/callback for a collections of elements with same root?

**Comment by thebuilder** [comment]
See #285 for similar discussion. Consider using the render function approach of you need more control. 

Internally the observer instance is reused. You should be able to give each '<InView>` the same onChange function if that helps?

**Comment by chaitu9916** [comment]
If a single observer instance is re-used is it not possible to expose the whole array of entries on each callback ? 
Then externally, one can debounce/Throttle and function can get state of visibility across the whole array of targets?

**Comment by chaitu9916** [comment]
My bad, didn't realize you can't get the current intersecting values for all targets from the observer instance but have to rely on callbacks which get the entries from only target that have hit the threshold.
