### ISSUE TITLE
Debounce?

### ISSUE THREAD

**Issue by wle8300** [thebuilder/react-intersection-observer#323]
Love this lib! Thx for making it.

## Question:

I don't think Intersection Observer has a way to define a debounce time. But...

Any plans to implement this into this component? I'm using it on a list of DOM nodes (~20ish) and the performance is really slow.

**Comment by ckeeney** [comment]
Are you passing an array to threshold?

**Comment by wle8300** [comment]
no, just a number.

1!

**Comment by wle8300** [comment]
Like this:

```
      <InView
        as="div"
        threshold={1}
        onChange={this.handleInView}
      >
```

**Comment by thebuilder** [comment]
It's unsupported but the API, so this isn't something that's going to be implemented in this library.

**Comment by samuelgoldenbaum** [comment]
> Are you passing an array to threshold?

Is this relevant to the performance?
