### ISSUE TITLE
Let hook consumer optionally pass a ref

### ISSUE THREAD

**Issue by ckeeney** [thebuilder/react-intersection-observer#324]
In my use case, I want to track intersections between a target element and more than one other element on the page

Currently, `useInView` creates and returns a new `ref` that must be attached to the DOM, and it accepts a `root` config to target another element.

https://github.com/thebuilder/react-intersection-observer/blob/149437a8f41bd5484d2cd94a8ada7975c1160a88/src/useInView.tsx#L16-L19

I suggest letting the consumer pass a `ref` to the `useInViewHook`.  This would allow us to register multiple intersection observers on the same element, which is useful for tracking intersections between an element and multiple other boundaries.  Passing the same ref into `useInView` multiple times but setting different `root` properties in the options would let you track intersections between one element and multiple targets.

**Comment by renchap** [comment]
As a workaround, you can do something like this:

```js
const setRef = React.useCallback(
  (element) => {
    observer1Ref(e)
    observer2Ref(e)
  },
  [observer1Ref, observer2Ref],
)

return <div ref={setRef}>…</div>
```

**Comment by thebuilder** [comment]
I'm going to close this issue - It seems like a special use case, that you can solve by combining the refs from multiple `useInView` hooks.
