### ISSUE TITLE
New option to untrigger once 

### ISSUE THREAD

**Issue by DaveTrost** [thebuilder/react-intersection-observer#335]
I had a case where I wanted to track an element leaving the viewport, and once it left, I didn't need to get any more updates about it re-entering (or re-exiting).
I can propose a new option for anyone else who may encounter this use scenario: unTriggerOnce. Behavior: Once triggered the first time, the method will give exactly one more update - when the reference element leaves the viewport.
I was able to achieve my desired behavior with this useEffect hook:
```
  const [triggeredOnce, setTriggeredOnce] = useState(false);
  const [untriggeredOnce, setUntriggeredOnce] = useState(false);
  useEffect(() => {
    if(!triggeredOnce) {
      if(entry && inView) {
        setTriggeredOnce(true);
      }
    }
    else if(!untriggeredOnce) {
      if(entry && !inView) {
        setUntriggeredOnce(true)
      }
    }
  },
  [entry, inView, triggeredOnce, untriggeredOnce]);
```
I'm curious to hear more thoughts on this.

**Comment by thebuilder** [comment]
I'm not sure what a usecase for this would be?
If you need something like this, I'd recommend disabling the observer by removing the `ref` from the element.

**Comment by DaveTrost** [comment]
In my case, I have a component where a series of state changes take place over 7 seconds to generate the appearance of animation. The section of page below the animation is blank while the animation runs. When the animation ends, the remainder of the page becomes visible. 
Using the approach above, I am able to sense the user scrolling further down the page (animation component becomes untriggered once). Upon untriggering, the animation is turned off and the remainder of the page is displayed. At this point, it is useless to trigger any more inView changes to the ref component. It's pretty hard to describe in text. You can see it on my site [here](davetrost.com).

It's not clear to me if removing the ref accomplishes the same thing. Also not sure how to remove the ref. I tried using a ternary to set the ref equal to useInView's ref or to an empty function. Do you have any suggestions for how to remove the ref?

**Comment by thebuilder** [comment]
Wouldn't you be able to solve this by using `triggerOnce`? 

Otherwise you can remove the `ref` like this:

```js
return <div ref={!untriggered ? ref : undefined} />
```

**Comment by DaveTrost** [comment]
Well, I tried this, and I got a console message from React: "Warning: Cannot update a component from inside the function body of a different component." I will stick with my method for now (it seems more flexible).
Anyway, I have a workaround, and I haven't laid my case out well enough to convince you of the usage scenario. I'd be fine with closing this issue.
