### ISSUE TITLE
threshold on horizontal scrolling

### ISSUE THREAD

**Issue by munichfeels** [thebuilder/react-intersection-observer#338]
I'm not able to implement a working solution for the threshold option on a horizontal scrollbar. InView fires as soon as one of my items is visible. Any ideas how to fix that?

thanks

**Comment by thebuilder** [comment]
You'll need to provide at Codesandbox with the issue - There's no reason it shouldn't work.

**Comment by munichfeels** [comment]
That was a fast reply. :D I'will provide the sandbox here asap. Thanks :)

**Comment by aderchox** [comment]
Hi @thebuilder, can you please have a look at this sandbox? https://codesandbox.io/s/festive-glitter-8sb7l0?file=/src/App.js
I want to know when the `.test__pane` is out of the viewport's horizontal area, is it possible with react-intersection-observer?

**Comment by aderchox** [comment]
I've got it. I've used the threshold option of 1 and it's fixed now. I think the name `inView` is a bit misleading, but anyways, it's fixed now, thanks.

**Comment by thebuilder** [comment]
How is `inView` misleading? I matches the rules you have defined for the intersection:)

**Comment by aderchox** [comment]
> How is `inView` misleading? I matches the rules you have defined for the intersection:)

I mean on the first glance and on the first impression (in terms of readability, i.e., without knowing anything about intersection observers), if something is even 1% in the view, then it's in the view, just my humble opinion.
