### ISSUE TITLE
Use same ref for multiple `useInView()` with different options

### ISSUE THREAD

**Issue by orballo** [thebuilder/react-intersection-observer#340]
Hi! I have a use case where I'd like to use the same reference for more than one `useInView()`, each one with different options. When I try to do that I get an error because the library doesn't allow to do it.

- Is there a reason for not supporting multiple observers to one reference?
- Do you have a suggestion on how to achieve what I'm trying to do?

In case it helps, here is a sandbox using two different `div`s to achieve this:
https://codesandbox.io/s/infinite-scroll-frqbq

But I'd rather avoid using more elements than the necessary! :)

Thanks!

**Comment by thebuilder** [comment]
I'm not sure how you are trying to do that? 

You can merge the `refs` from multiple `useInView` hooks:

```
import { useInView } from 'react-intersection-observer'

function Component(props) {
  const ref = useRef()
  const [inViewRef, inView] = useInView()
  const [inViewRef2, inView2] = useInView()

  // Use `useCallback` so we don't recreate the function on each render - Could result in infinite loop
  const setRefs = useCallback(
    (node) => {
      // Callback refs, like the one from `useInView`, is a function that takes the node as an argument
      inViewRef(node)
      inViewRef2(node)
    },
    [inViewRef, inViewRef2],
  )

  return <div ref={setRefs}>Shared ref div</div>
}
```

**Comment by orballo** [comment]
Thanks for the quick reply!

I tried to do exactly that, but it seems to work only when setting external references, not when setting more than one `inViewRef`.

The error I get is:
```
Error: "Invariant failed: react-intersection-observer: Trying to observe %s, but it's already being observed by another instance.
Make sure the `ref` is only used by a single <Observer /> instance.
```
Which seems to come from: https://github.com/thebuilder/react-intersection-observer/blob/d1e14954f373f67030c85d26094da65680e7eebe/src/intersection.ts#L41-L44

Here is a small codesandbox reproducing it https://codesandbox.io/s/infinite-scroll-with-error-vom3l

**Comment by thebuilder** [comment]
Right. That's true. I can't recall the exact reasoning for that limitation. Need to do some digging😉

**Comment by thebuilder** [comment]
See https://github.com/thebuilder/react-intersection-observer/issues/119

**Comment by thebuilder** [comment]
Might make sense to start looking into refactoring the internals, so it doesn't map observers to DOM elements.

**Comment by orballo** [comment]
That would be very nice :)
