### ISSUE TITLE
inView not being triggered when the image is already within the intersection (with  triggerOnce: true)

### ISSUE THREAD

**Issue by kuworking** [thebuilder/react-intersection-observer#341]
I'm facing this problem, just starting to dive in to see if I can figure out what's happening here

But I've thought that maybe it has some easy explanation, so I've made the gif

In short, it looks like when going back with the browser button, the browser remembers the scroll position, and if then I land on the previous page with the scroll already moved, then `inView` is not reporting events as one would expect, in my example causing images not to load

*in the image you can see a `console.log(inView)` from a 

```
  const settings = {
    triggerOnce: true,
    rootMargin: '200px 0px',
    threshold: 0,
  }
  const [ref, inView] = useInView(settings)

  useEffect(() => {
    console.log(inView)
    inView && setShowRecipes(prev => [...prev, ...recipes.splice(0, more_recipes)])
  }, [inView])
```

Posting now in case there is a simple explanation and solution, otherwise I'll try to make a minimal repo

![test](https://user-images.githubusercontent.com/4474004/81175143-4d725080-8fa3-11ea-9781-3e19c770e371.gif)

------------

EDIT: I can see that this doesn't happen if I remove the `triggerOnce`, but if I can't use it in this example where I only need the event to happen once, what is the use case for `triggerOnce`?

**Comment by thebuilder** [comment]
There's nothing as such that stop it from working. It would report `true` if it starts inside the viewport.

What is your `ref` assigned to? It's not the image itself, nor the rows.

**Comment by kuworking** [comment]
I'm assigning a ref to the last item of the array (item = card), when this is seen then the array increases and the ref is re-assigned to the last item of the new array

I do this to avoid having too many refs that might slowdown the ux (can't remember if I did this based on experience or as a precaution, but I'd say the former)

When I say "the last item" I'm specifically saying a div within the card, below the image, that contains some icons

**Comment by thebuilder** [comment]
Trigger once is intended for one-and-done events, but you are actually reusing the hook.

What i think you want here, is a `<Satellite>` element placed below your grid. 
This element has the intersection observer assigned (without `triggerOnce`), and lets you know when the user is scrolled to the bottom of the viewport.

It should trigger a load of more objects whenever you aren't loading and it's still inside the viewport.

**Comment by kuworking** [comment]
It would be the same than moving the hook to the last item (what I'm doing) but without triggerOnce, but it actually looks simpler to have the Satellite element so I'll implement your suggestion (thanks! :)

Still, what happens here is weird because there's no problem if when I got back to the browser I'm at the top of the scroll (if the problem was of reusing the hook, then it neither would work)

Somehow it is like if the automatic scroll to the last position prevents the trigger

Anyway, removing the triggerOnce looks a good solution to me, so I close the issue

*And thanks again for your incredible response time 🙌🙌🙌
