### ISSUE TITLE
Trigger animations recipe causes infinite render

### ISSUE THREAD

**Issue by alberthajdu** [thebuilder/react-intersection-observer#342]
Hi!

There's a bug in this recipe: https://github.com/thebuilder/react-intersection-observer/blob/master/docs/Recipes.md#trigger-animations

I'm not sure whether it's related to the library or the recipe. But following the structure in the recipe causes infinite renders.

Repro
1. Open this codesandbox https://codesandbox.io/s/affectionate-roentgen-tfj0y
2. See infinite render logs.

You can solve the issue by placing `ref={ref}` on another element either outside or inside the `<animated.div style={props}>` element. But when they are on the same element the definitely don't play nice together.

Can you please confirm whether it's related to the packages or to the recipe? So we can solve it accordingly.

Thanks,
Albert

**Comment by thebuilder** [comment]
Great. Might be related to how `react-spring` handles the `ref`.
Tried to replace it with `framer-motion`, and that works nicely:
https://codesandbox.io/s/dark-brook-d1cwq

**Comment by thebuilder** [comment]
Could be related to this issue: https://github.com/react-spring/react-spring/issues/1037

**Comment by thebuilder** [comment]
I've updated the recipe to use Framer Motion for showcasing the usage.

**Comment by alberthajdu** [comment]
Yes, framer-motion works nicely. Thanks!
