### ISSUE TITLE
adding height to children will not trigger <InView>

### ISSUE THREAD

**Issue by prafulrajhm** [thebuilder/react-intersection-observer#344]
I am using the package to change navbar background, I have a section where children contain the CSS property `min-height: '20rem'`. This is not triggering the onChange function. If I remove that min-height, onChange is working perfectly.

`<InView
        as="div"
        threshold={[0.9, 0.1]}
        onChange={(inView, entry) => {
          changeBg('#fff', false, entry);
        }}
      >
        <section id="locations" className="full-height align-items-center py-5">
          <div className="container locationPadding">
            <p className="mt-4 mb-5" style={{ maxWidth: '48rem' }}>
              Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
              is simply dummy text of the printing and typesetting industry.
            </p>
            <div className="row">
              <div className="col-md-6">
                <div className="card my-4 mx-1"></div>
              </div>
              <div className="col-md-6">
                <div className="card my-4 mx-1"></div>
              </div>
              <div className="col-md-6">
                <div className="card my-4 mx-1"></div>
              </div>
              <div className="col-md-6">
                <div className="card my-4 mx-1"></div>
              </div>
            </div>
          </div>
        </section>
      </InView>`

and the CSS is 

`#locations {

  .full-height {
    min-height: 100vh;
  }
  
  .card {
    min-height: 20rem;
    background-color: #dcdada;
    border: none;
    border-radius: $border-xl;
  }

  .locationPadding {
    padding-top: 5rem;
    padding-bottom: 5rem;
    color: #515151;
  }
}`

version: 8.26.2
browser : chrome 83.0.4

**Comment by thebuilder** [comment]
Please provide a Codesandbox where the issue can be replicated. 
It sounds like an issue with how your styling is interacting with IntersectionObservers, and not an issue with the library as such.
