### ISSUE TITLE
How to remove the observer? (un subscribe)

### ISSUE THREAD

**Issue by JorgeSivil** [thebuilder/react-intersection-observer#345]
Hi, this is not very clear from the docs, but once I trigger the intersection, I don't need the observer anymore.

How do I dispose it?

Code is

```
...
const observerOptions = {
    triggerOnce: true,
    onChange: handleIntersection,
    rootMargin: '0px 0px 300px 0px',
  };

  return (
    <Observer {...observerOptions}>
      <aside className={styles.main}>
        {getSection('MORE POPULAR LISTS', morePopularLists)}
        {moreLikeThisLists.length > 0 && getSection('MORE LIKE THIS', moreLikeThisLists)}
      </aside>
    </Observer>
  );
....
```

**Comment by thebuilder** [comment]
It removes the events once it's triggered. The `<Observer>` should be left there.
If you don't want to render it anymore, you need to modify your code so it doesn't add the `<Observer>` once a local state is true (you really don't need to do this).
