### ISSUE TITLE
Allow `root` option to be explicitly set to window

### ISSUE THREAD

**Issue by jdfm** [thebuilder/react-intersection-observer#346]
From the documentation:

Name | Type | Default | Required | Description
-- | -- | -- | -- | --
root | Element | window | false | The Element that is used as the viewport for checking visibility of the target. Defaults to the browser viewport (window) if not specified or if null.

via https://github.com/thebuilder/react-intersection-observer#options

So, it defaults to the window if it's passed a `null` value or not specified. But, if you try to set `root` to window explicitly, it throws errors and breaks stuff. Can we just allow `root` to be set to the window?

**Comment by thebuilder** [comment]
Do you have an example of this error? Any reason to set the value to `window` explicitly? ``root` defaulting to `window` is the native browser implementation.

**Comment by jdfm** [comment]
The error I'm seeing is:

`Uncaught TypeError: Failed to construct 'IntersectionObserver': The provided value is not of type '(Element or Document)'`

So, this seems to be coming from IntersectionObserver itself.

The reason being able to explicitly setting it to window would be useful is if you have a few scrolling contexts in your app, but, it takes some time to get them set up. So a sensible default is to consider the window as the only scrolling context until the other ones are ready to be used.

If we can't pass window directly to IntersectionObserver, would checking the root (when using react-intersection-observer) for `window` and forcing it to `null` in that case (so IntersectionObserver doesn't throw) be reasonable? Just so the possibility of using window in react-intersection-observer is there, and IntersectionObserver is kept happy?

**Comment by thebuilder** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/root
It should actually be `document`, not `window` - I've listed it wrong in the prop documentation.
That's also what you are seeing in the error message you are getting - Provide a valid `Element` or `Document` (e.g. `window.document`).

**Comment by thebuilder** [comment]
Note that it will work if you pass `document` as the `root`, but if you are using TypeScript you'll get an error since the `lib.dom.d.ts` implementation for `IntersectionObserver` lists [`root` as `Element | null`](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.intersectionobserver.html#root).
