### ISSUE TITLE
Edge and mobile browser quirks

### ISSUE THREAD

**Issue by jooj123** [thebuilder/react-intersection-observer#35]
Currently using this component extensively across various code bases I work on - thanks for the work !

Do you think it would be useful for me to add some docs on how to get around some of the quirks mentioned here (to do with Edge and mobile browsers) - or at least provide a bit of a heads up to users wanting to use this component ? See:
https://www.quirksmode.org/blog/archives/2017/10/intersection_ob.html
(Eg. I can get it to work quite well with edge by just tinkering with `rootMargin` for instance)

I know its not specifically related to `react-intersection-observer` but more about Intersection Observer support in browsers as of xyz date

Happy to throw up PR if you think it would be worthwhile

**Comment by damusnet** [comment]
Hi @jooj123 

We just started using this awesome library (thanks @thebuilder) and while we don't support Edge just yet, I'd be very interested to hear about the quirks on mobile browsers that you know of.

Thank you :)
