### ISSUE TITLE
how to remove the div wrapper

### ISSUE THREAD

**Issue by avalenti89** [thebuilder/react-intersection-observer#358]
Hi,
I'm trying to use your plugin inside a table to show a big amount of rows at once.
I wrapped my N rows with a single InView wrapper component but, when my table was rendered, I figure out that InView creates a div element in DOM.

There is a way to not use a new element in DOM?

**Comment by thebuilder** [comment]
You can use the `<InView>` component as a [render prop](https://github.com/thebuilder/react-intersection-observer#render-props) - that way no extra elements are created.

Alternatively, use the `useInView` hook.
