### ISSUE TITLE
Infinite loop when used with react-native-web View

### ISSUE THREAD

**Issue by MoOx** [thebuilder/react-intersection-observer#359]
Everything is in the title. No issue with a div, as soon as I try to use RNW View, a infinite loop is started.

This is likely due to how RNW handle ref for the View (and maybe others)

https://github.com/necolas/react-native-web/blob/251cdfb220a165dc652bf118063139da2b9345f1/packages/react-native-web/src/exports/View/index.js#L104-L140

**Comment by thebuilder** [comment]
Yeah, this is because they always trigger the ref callback function. The ref callback they create should be wrapped in a `useCallback` - Otherwise it will be called multiple times.

https://github.com/thebuilder/react-intersection-observer#how-can-i-assign-multiple-refs-to-a-component

**Comment by thebuilder** [comment]
I might also be able to modify the ref callback, so it doesn't recreate the observer if it's the same element and options.

**Comment by wildfrontend** [comment]
i find when i use `Profiler` , i find inViewRef will cause Infinite loop

i use useInView to set ref

it is a bug? 
![Oct-15-2020 13-35-48](https://user-images.githubusercontent.com/20965813/96081274-8b2cbb00-0eeb-11eb-857f-73ea7ca7be0d.gif)

**Comment by thebuilder** [comment]
> i find when i use `Profiler` `inViewRef` will cause Infinite loop
> 
> i use useInView to set ref
> 
> it is a bug?
> 
> sample code ：[codesandbox.io/s/serverless-cache-z7hdv?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/serverless-cache-z7hdv?fontsize=14&hidenavigation=1&theme=dark)
> 

It's because you are creating a new `threshold` on each render, causing it to recreate the observer.

```js
 threshold: [0.5]
```

**Comment by thebuilder** [comment]
@wildfrontend I made a new release that should prevent that issue. #404

**Comment by thebuilder** [comment]
This issue has been resolved by [react-native-web](https://github.com/necolas/react-native-web) in https://github.com/necolas/react-native-web/pull/1746
