### ISSUE TITLE
disable lazy load image when image in the view first render

### ISSUE THREAD

**Issue by zerofront** [thebuilder/react-intersection-observer#366]
https://codesandbox.io/s/lazy-image-load-forked-dirzr

![image](https://user-images.githubusercontent.com/19327366/91047092-20c66f80-e64c-11ea-8955-003b34b7df2f.png)

![image](https://user-images.githubusercontent.com/19327366/91047133-2cb23180-e64c-11ea-8d70-ba214f6ac492.png)

if the image is in the view when the first render. I want to let this picture only render the actual image not placeholder image.

but it seem that in the first render the value inVIew return by useInView is always false, so in the first render it always render the placeholder image

**Comment by thebuilder** [comment]
This is intentional. Adding the IntersectionObserver is a side effect that requires access to a rendered DOM node.
If you want to wait until the initial state is known, check for the `entry` value to defined, and don't set the `src` before `entry` exists.
