### ISSUE TITLE
Intersection Observer V2 Support

### ISSUE THREAD

**Issue by agcty** [thebuilder/react-intersection-observer#368]
Now with Chrome v85 supporting the Intersection Observer v2 API I was wondering if there are any plans to support v2 (maybe with fallback support to v1) or if it makes sense to wait until more browser support the new API.

**Comment by thebuilder** [comment]
Yes, I've been meaning to look into it.

Seems like it mostly adds the new `delay` and `trackVisibility` options, so should be fairly simple to, with basic fallback support to always assume elements are visible.
