### ISSUE TITLE
Possible to to add callback for isVisible

### ISSUE THREAD

**Issue by ScriptedAlchemy** [thebuilder/react-intersection-observer#369]
Hey!

Would it be possible to add an additional callback prop for when something is visible, or triggerOnceVisible. 

## Reasoning

I have collapsed accordions, intersection observer comes back with `inView=true` but the element is not actually visible to the end user (accordion is collapsed) 

It would be nice if there was an onChange event for visibility as well

**Comment by thebuilder** [comment]
This sounds like it might be an issue with how your accordion is collapsed? Make sure to properly hide the collapsed element (`display: none` or `hidden` attribute`, etc.).

Full support for visibilty detection is only supported in IntersectionObserver v2, which is still early. It's not something this library supports yet. #368

**Comment by ScriptedAlchemy** [comment]
ahhh okay. Yeah i think the accordion is using height to "hide" it, when I was looking at the observer, I saw visible:true and was like "oh neat, let me speak to the project authors" 

Makes sense now, part of a V2 observer. Ill retrofit my code to display none.
