### ISSUE TITLE
inView not working with Firefox after upgrade from 8.27.1 to 8.28.1

### ISSUE THREAD

**Issue by karl-knuttel** [thebuilder/react-intersection-observer#383]
Hey. After upgrade we now have an issue where inView does not seem to trigger on Firefox.

Usage is as follows
```
const [ref, inView, entry] = useInView({
    threshold: 1
  });
```

```
const showElement =
    !inView &&
    entry &&
    entry.boundingClientRect.top < 0;
```

It previously worked and there's been no changes in the code. Any reason why this should be?

Cheers!

**Comment by thebuilder** [comment]
Can you replicate it in a Codesandbox? https://codesandbox.io/s/react-intersection-observer-ud2vo?fontsize=14&hidenavigation=1&theme=dark

What's the exact issue you are seeing?

**Comment by karl-knuttel** [comment]
Hey! Sure: https://codesandbox.io/s/react-intersection-observer-forked-ltqjj?file=/src/index.tsx

Here it works in chrome, but on Firefox it is flaky. It seems to work if you quickly scroll down, but if you slowly scroll the ref doesn't seems to trigger.

**Comment by thebuilder** [comment]
Can't seem to replicate it. Tried scrolling a single pixel to trigger, scrolling fast, scrolling slow.
What version of Firefox are you running? Windows or Mac?
![Skærmoptagelse 2020-09-09 kl  11 08 20](https://user-images.githubusercontent.com/3764345/92579111-12ec2d80-f28d-11ea-92e8-6f3fd9867bb6.gif)

**Comment by karl-knuttel** [comment]
Hmm weird. MacOS 8.12.0esr (64-bit)

**Comment by thebuilder** [comment]
Can you log out the `entry` object you get when it leaves the viewport? Does it actually trigger a new intersection?

**Comment by karl-knuttel** [comment]
No problem. It certainly seems to trigger. Very strange.
![r-i-o_capture_2](https://user-images.githubusercontent.com/42608917/92581911-90fe0380-f290-11ea-801a-8648ca809910.gif)

**Comment by thebuilder** [comment]
Can you show the details (content) of the entries? You can see them in the regular browser console.
Also what is the value of `inView`? Does that correctly reflect it has left the viewport (and does it match `entry.isIntersecting`)?

**Comment by karl-knuttel** [comment]
The first entry is when it's successful (fast scroll). The third entry is when it's unsuccessful (slow scroll).

<img width="497" alt="Screenshot 2020-09-09 at 14 53 40" src="https://user-images.githubusercontent.com/42608917/92600861-628e2180-f2ac-11ea-9919-13eb8712ea06.png">

**Comment by thebuilder** [comment]
Huh - It's still marked as `isIntersecting`, even tho the `intersectionRatio` is clearly below the threshold.

**Comment by thebuilder** [comment]
Right - seems like there is still some disagreement between browsers on when an element `isIntersecting`. I'll add back back my fix for this, where I look at the reported `threshold` to determine if it's actually inside the viewport.

**Comment by thebuilder** [comment]
Can you try the Codesandbox in #384, see if that fixes the issue?

**Comment by karl-knuttel** [comment]
> Can you try the Codesandbox in #384, see if that fixes the issue?

Works perfectly now with 8.28.3. Thanks for the fix!
