### ISSUE TITLE
<InView> doesn't work when the target component is re-rendered

### ISSUE THREAD

**Issue by caohv** [thebuilder/react-intersection-observer#386]
```
{currentTab === TabValues.COMING ? (
  <InView onChange={() => {
    console.log('1');
  }}
  >
    hihi
  </InView>
) : (
  <InView onChange={() => {
    console.log('2');
  }}
  >
    haha
  </InView>
)}
```

**Comment by caohv** [comment]
I try add key in <InView>: `<InView key={id}>` and then work. So, what happend? Can anyone help?

**Comment by thebuilder** [comment]
Adding a `key` seems like the right approach, to ensure `<InView>` correctly updates when replaced. In your instance it would update the component with the new `onChange` and `children`. These wouldn't cause a new IntersectionObserver to be created, which might be able to break the component?
