### ISSUE TITLE
InView with threshold=1 not working

### ISSUE THREAD

**Issue by joekur** [thebuilder/react-intersection-observer#387]
This can be reproduced in the storybook: https://react-intersection-observer.now.sh/?path=/story/useinview-hook--with-threshold-100-percentage. The first argument to the `onChange` callback is always false, but it should be true when scrolling fully into view.

From some local testing, this appears to be introduced in version `8.28.4`.

**Comment by thebuilder** [comment]
That's not good. Will look into it, thanks!

**Comment by thebuilder** [comment]
A case of having `>` instead of `>=`, preventing an `intersectionRatio` of `1` from ever triggering. Solved in next release.
