### ISSUE TITLE
[question] How to make react-intersection-observer to be triggered if threshold is 1 and section's height is larger than viewport

### ISSUE THREAD

**Issue by SilencerWeb** [thebuilder/react-intersection-observer#388]
Hi! Thanks for the great library, we use it in all our projects.

I just wanted to ask if there is a way to make `react-intersection-observer` to be triggered if `threshold` is 1 and the section's height is larger than the viewport. [Here](https://react-intersection-observer.now.sh/?path=/story/useinview-hook--taller-than-viewport-with-threshold-100-percentage) is an example of the case in your Storybook.

The problem is that we trigger animations once the user is in the section's viewport. Usually, we set `threshold` to 0.7, and the problem that on mobile screens sometimes the section is just too large and animation can't be triggered, especially if the device is in landscape orientation.

So, is there a workaround for this? I know there is a way to pass an array of thresholds but I'm not sure if it is what we need 🙂

**Comment by thebuilder** [comment]
Not that I know of. For your use case I'd recommend using `rootMargin` instead.
https://github.com/thebuilder/react-intersection-observer/blob/master/docs/Recipes.md#trigger-animations

**Comment by SilencerWeb** [comment]
Thanks a lot @thebuilder!

Could you also tell me what % in `rootMargin` depends on? Like, on window height, window width, section height, or section width?

**Comment by thebuilder** [comment]
It depends on the Root visit viewport. So the window height and width by default. Works as you'd expect😉
