### ISSUE TITLE
Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.

### ISSUE THREAD

**Issue by Whooolia** [thebuilder/react-intersection-observer#389]
<img width="1046" alt="Screen Shot 2020-09-16 at 11 57 33 AM" src="https://user-images.githubusercontent.com/36998110/93287177-cfa53800-f813-11ea-9f48-ced748546b32.png">

It would be nice to update the docs although it's a small thing. `RootMargin` should be updated as `rootMargin="100% 0%"` or `rootMargin="-100px 0px"` it requires px or % to 0 as well. otherwise it causes an issue as a screenshot below.

<img width="478" alt="Screen Shot 2020-09-16 at 11 58 33 AM" src="https://user-images.githubusercontent.com/36998110/93287238-f4011480-f813-11ea-84a7-f0f4f6ce19a9.png">

**Comment by thebuilder** [comment]
Sorry bout - One of those weird rules that are easy to forget. I'll fix it.

**Comment by thebuilder** [comment]
Fixed in: https://github.com/thebuilder/react-intersection-observer/commit/a9eac7ea8349ee51ecad5053ede9d974f63f1822
