### ISSUE TITLE
Getting "React.createElement: type is invalid" error with 8.28.5

### ISSUE THREAD

**Issue by klapec** [thebuilder/react-intersection-observer#390]
Dependabot bumped `react-intersection-observer` in one of my repos to version 8.28.5 and since then, every time I use the `<InView triggerOnce>` component, I'm getting a following error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check your code at xxx.js:100.
    in xxx
    in Context.Provider
    in ConnectFunction
    in ConnectFunction (at _app.js:36)
    in App
    in Context.Provider
    in Provider
    in withRedux(App)
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at ReactDOMServerRenderer.render (/xxx/node_modules/react-dom/cjs/react-dom-server.node.development.js:3743:17)
    at ReactDOMServerRenderer.read (/xxx/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/xxx/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at Object.renderPage (/xxx/node_modules/next/dist/next-server/server/render.js:48:686)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:129:19)
    at Function.getInitialProps (webpack-internal:///./pages/_document.js:20:85)
    at loadGetInitialProps (/xxx/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/xxx/node_modules/next/dist/next-server/server/render.js:48:977)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Has anything changed recently with regards to `<InView triggerOnce>`?
Reverting back to 8.27.1 (which was the version previously used in my repo) fixes the problem.

**Comment by thebuilder** [comment]
What does your immediate `children` look like in the component?

**Comment by klapec** [comment]
Sorry for the late reply, I somehow missed the notification.
Here's the relevant code:
```
              <InView triggerOnce>
                {({ inView, ref }) => (
                  <div className="offer-details-block__gallery" ref={ref}>
                    {inView ? (
                      <GalleryContainer
                        ...
                      />
                    ) : null}
                  </div>
                )}
              </InView>
```

**Comment by thebuilder** [comment]
Added that to a Sandbox - Seems to work fine. Could it be something inside your `<GalleryContainer>` that breaks? 

[![Edit react-intersection-observer #390](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-intersection-observer-forked-jekd6?fontsize=14&hidenavigation=1&theme=dark)

**Comment by klapec** [comment]
I've found the culprit: I had `InView` imported as a default export, not a named one.
I changed:
`import InView from 'react-intersection-observer';`
to
`import { InView } from 'react-intersection-observer';`
and it worked.
Weird because it worked @ 8.27.1.

**Comment by nagman** [comment]
I had the (almost) exact same issue:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object
```
Running `react-intersection-observer` on next.js 10.

The issue comes from the fact that the vs code auto-import takes the default export of the package instead of the child one.
If we can't import and use the default one, why would it be exported?
It would be more logic to name that default export with an other name, like `ReactIntersectionObserver`.

**Comment by thebuilder** [comment]
What does VS code do? What's the generated code?
The `default export` is deprecated, and it will likely be removed in the next major release.

https://github.com/thebuilder/react-intersection-observer/issues/381

**Comment by nagman** [comment]
It auto-imports the default export:

![Peek 29-12-2020 14-52](https://user-images.githubusercontent.com/16116486/103288598-7e493f00-49e5-11eb-8170-f46e71466505.gif)

**Comment by thebuilder** [comment]
Hm, but that should still work fine. What do you get when log out `console.log(InView)`?

**Comment by nagman** [comment]
First I get a server-side error from next.js :
![image](https://user-images.githubusercontent.com/16116486/103304544-2fad9c00-4a09-11eb-83a5-b771179a4e08.png)

And if I console.log:
```
{
  InView: [Function: InView] {
    displayName: 'InView',
    defaultProps: { threshold: 0, triggerOnce: false, initialInView: false }
  },
  default: [Function: InView] {
    displayName: 'InView',
    defaultProps: { threshold: 0, triggerOnce: false, initialInView: false }
  },
  useInView: [Function: useInView]
}
```

**Comment by thebuilder** [comment]
How are you bundling your app? Seems like it doesn't handle the `default` export, instead returning everything that's exported. This would be the CJS bundle instead of the ES module.

**Comment by nagman** [comment]
I'm using the default next.js `tsconfig.json`:
```json
{
	"compilerOptions": {
		"baseUrl": "./src",
		"target": "es5",
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": true,
		"skipLibCheck": true,
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve"
	},
	"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
	"exclude": ["node_modules"]
}
```

**Comment by thebuilder** [comment]
Made a new Next.js project on Github, and it was working with the default import🤔

**Comment by nagman** [comment]
Almost a year passed and I still encounter this issue on next 11.1.2 and react-intersection-observer 8.32.1.
Yet now I only have the default export (the one that doesn't work) with VS Code autoimport feature.

**Comment by thebuilder** [comment]
Can you clarify/make an example? 

The package exports all of these, so not sure what problem you might be seeing:

```ts
export { InView } from './InView';
export { useInView } from './useInView';
export { observe } from './observe';

export default InView;
```
