### ISSUE TITLE
Allow access to <InView /> (plain child) ref

### ISSUE THREAD

**Issue by maeertin** [thebuilder/react-intersection-observer#391]
Hi there, loving this package and using it across several projects, cheers!

However, is there any reason why one can't get access to the ref when using <InView /> plain child? Currently I might be forced to use something like `ReactDOM.findDOMNode` which is sad as the hook and render props options are a no go (can explain if needed).

If normal Ref Forwarding is not an option can't this be implemented via a `innerRef` prop? For example:

```jsx
// setRef util
export default function setRef(ref, value) {
  if (typeof ref === 'function') {
    ref(value);
  } else if (ref) {
    ref.current = value;
  }
}
```

```jsx
import setRef from './setRef'

export class InView extends React.Component {
  ...
  handleNode = (node) => {
    if (this.node) {
      this.unobserve();
      if (!node && !this.props.triggerOnce && !this.props.skip) {
        this.setState({ inView: false, entry: undefined });
      }
    }
    this.node = node ? node : null;
    this.observeNode();

    // Forward the ref via prop innerRef
    setRef(this.props.innerRef, node);
  };
  ...
}
```

Thanks in advance

**Comment by thebuilder** [comment]
I recommend using the ["Render Props"](https://github.com/thebuilder/react-intersection-observer#render-props) pattern (if hooks isn't an option), since this gives you full control over the `ref` handling.

**Comment by maeertin** [comment]
Hi @thebuilder, thank you for your response!

This is an issue in several components I've wanted to create. One example being something like below:
```jsx
const Media = React.forwardRef(function Media(props, ref) {
  const { lazy: lazyProp, src: srcProp, ...other } = props

  const [lazy, setLazy] = React.useState(lazyProp)
  const handleChange = (inView) => {
    if (inView) {
      setLazy(false)
    }
  }

  const src = !lazy ? srcProp : undefined

  if (lazyProp) {
    return <InView as="img" onChange={handleChange} src={src} ref={ref} {...other} />
  }

  return <img src={src} ref={ref} {...other} />
})
```
In the example above my `Media` component has no way of forwarding the ref.

```jsx
const Media = React.forwardRef(function Media(props, ref) {
  // ...

  return (
    <InView>
      {({ inView, ref: innerRef }) => {
        // React crashes here as hooks are not allowed to be run in the return statement
        const handleRef = useForkRef(innerRef, ref) // Combines the refs and memoizes them

        return <img ref={handleRef} />
      }}
    </InView>
  )
})
```
Example above is with renderProps but not sure how I could implement this in a clean way. Also using the `useInView` hook is not an option as one can't have hooks inside if-statements.

`useForkRef` hook taken from:
https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/utils/useForkRef.js

**Comment by thebuilder** [comment]
You can add `skip` to the `useInView` hook, so it doesn't do anything. No need to conditionally render it

**Comment by thebuilder** [comment]
If you need to merge the refs, you should use a `useCallback`: https://github.com/thebuilder/react-intersection-observer#how-can-i-assign-multiple-refs-to-a-component

**Comment by maeertin** [comment]
This might be a separate issue @thebuilder but another reason I never use the `useInView` hook is that it makes the component render twice on mount vs using `<InView />` which only renders once on mount. This being a performance issue. If this was not the case I would gladly use the `useInView` hook.

```jsx
function MyComponent() {
  const [ref] = useInView({ triggerOnce: true })

  console.log('render')

  return <div ref={ref} />
}
```
```jsx
function App() {
  return <MyComponent />
}
```
The example above will log `render` to the console twice.

**Comment by maeertin** [comment]
Just to clarify, `useInView` logging "render" twice for mount and a **third** time once in view.

**Comment by thebuilder** [comment]
> This being a performance issue.

Have you profiled that it's a performance issue?

This is how Hooks work. The second `render` occurs when the IntersectionObserver is created, and you get back the first entry - It's a way for you to confirm that the observer has ben added.

The reason the `InView` only gets a single `render`, is that I only trigger the state update if `inView` changes. This might actually be considered a bug, if you expect the `entry` to be the current one. Could be an issue with multiple `thresholds` or if you rely on the `entry`.

**Comment by maeertin** [comment]
I think I understand @thebuilder, so basically the implementations differ where it's rather `<InView />` that has a bug. Sounds like I've actually been looking for something like a `useInView({ skipEntries: true })` option that could skip this second render (for `useInView` & `InView`) since I'm only interested in the `inView` boolean for lazy loading capabilities. Maybe that this would be out-of-scope for `react-intersection-observer`?

Regarding performance issues, two renders would have been fine in a controlled environment and a known amount of components rendered. In our case we're trying to create a React component library in the same fashion as https://material-ui.com/ that can be npm installed and used in a vast variation of projects, where components can opt-in on lazy loading functionality using `react-intersection-observer`. This being the case we want to optimize where possible with one example being a "Media" component that by itself already accounts for a huge amount of components being rendered twice.

Thank you for your help, much appreciated!

**Comment by thebuilder** [comment]
You can already skip creating the Observer.

```js
const [ref, inView] = useInView({skip: true})
```

This will return a `ref` function that doesn't do anything. You can also/instead skip assigning the `ref` to element, so it never gets an element to observe.

You could also consider creating your own `<Lazy>` component that the `<Media>` can conditionally render, allowing you to consume hooks inside it.

**Comment by thebuilder** [comment]
I've made #392 to fix the issues with the render path in the `<InView>`. This will introduce an extra `render` pass to the component when using render props, but limits the plain children to one render (since you keep track of state using `onChange`).
