### ISSUE TITLE
Default value for SSR and legacy browsers.

### ISSUE THREAD

**Issue by HKalbasi** [thebuilder/react-intersection-observer#393]
I'm using this library for animating navbar color based on scrollbar position. In the server side, the inView is always false, (at least I think so) which is somehow reasonable and meaningful. But it cause a flash animation in my case, which inView should be true at first.

Although ugly hacks are possible (which makes the linter sad), I think it is good to have a `default` parameter for contexts that does not have IntersectionObserver api. It also can be good for those who don't want to use a polyfill.

**Comment by thebuilder** [comment]
You can check for the `entry` value, to see if it's been activated. Using this, you could use a default value until it's ready.

```js
const [ref, inView, entry] = useInView()
inView = entry ? inView : true
```

**Comment by HKalbasi** [comment]
Thank you!
