### ISSUE TITLE
Property 'ref' does not exist on type 'InViewHookResponse'

### ISSUE THREAD

**Issue by BramDecuypere** [thebuilder/react-intersection-observer#400]
I'm having this issue pop up (Next.js (SSR) + netlify + typescript). Typing issue?

**Comment by BramDecuypere** [comment]
After switching to `Array desctructuring`, the build became functional again and typescript was not having issues.

**Comment by BramDecuypere** [comment]
Looks like this wasn't understood correctly for some reason:

```
export type InViewHookResponse = [
  (node?: Element | null) => void,
  boolean,
  IntersectionObserverEntry | undefined,
] & {
  ref: (node?: Element | null) => void;
  inView: boolean;
  entry?: IntersectionObserverEntry;
};
```

**Comment by nghiepit** [comment]
@BramDecuypere How `Array destructuring` work for you? I had tried but not work.
