### ISSUE TITLE
React 17 Compatability

### ISSUE THREAD

**Issue by arietrouw** [thebuilder/react-intersection-observer#406]
When upgrading my project to React 17, this library stops functioning and causes an error to be thrown saying that a hook was not called at the start for a render function.  May be due to dependency incompatibility.  Steps to reproduce: Upgrade a working project to React 17.

Note: I am using TypeScript.

**Comment by thebuilder** [comment]
I'm using it without issues on multiple React 17 projects.
Running on Codesandbox here:
https://codesandbox.io/s/useinview-ud2vo

**Comment by thebuilder** [comment]
Can you provide a failing Codesandbox example?
