### ISSUE TITLE
Works like a charm, unless I am using the triggerOnce prop

### ISSUE THREAD

**Issue by chiku524** [thebuilder/react-intersection-observer#413]
It seems that adding triggerOnce makes whatever you have set to ref always inView. 

For example, I have divs that fade-in based on the status of inView. If I add the prop triggerOnce, all of my divs fade-in once the page renders (when I scroll down, all of my divs have already faded-in and are already displaying on the web page).

**Comment by thebuilder** [comment]
Please check the styling to ensure they have a correct height from the start. If they contain images, ensure they have a fixed height/aspect ratio.

Can you create a Codesandbox with an example?

**Comment by chiku524** [comment]
Well I made a codesandbox, and it's actually working perfect on there. The triggerOnce is not working fine on my localhost and deployed site, however. Not sure why, it is pretty much the same code. I'll paste the URLs so you can compare the two. You will notice all of the fade-in animations occur once the page is rendered on my deployed site. 

codesandbox: https://codesandbox.io/s/agitated-buck-f5le7?file=/src/App.js
deployed site: https://hajjar-associates-remake.vercel.app/

**Comment by chiku524** [comment]
Also, I just checked and it works perfectly on my iPhone 12 (mobile), even with the triggerOnce.

**Comment by chiku524** [comment]
Great news. I added more elements to the site, and it is working for at least one of my divs. You must have been correct about it having to do with the styles, so I will go ahead and close this issue.
Thanks for the quick response and maintaining this wonderful feature, will be sure to use it on many of my future works.

**Comment by thebuilder** [comment]
On your example site it's clear that you are missing a width/height on the `<img>` elements, and you get a clear layout shift once the images are loaded. 

Read more about avoiding Layout shifts: https://web.dev/optimize-cls/
