### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by AnnaCate** [thebuilder/react-intersection-observer#414]
I'm seeing a `TypeError: Cannot read property 'some' of undefined` for users on `Chrome 86` and `Samsung Internet 5.2`, so far only for users on a `SM-J727T` device.

The error seems to be originating from:
https://github.com/thebuilder/react-intersection-observer/blob/9312d1d8b0c20e226dc31d0878c9dfca75ed5737/src/observers.ts#L58-L62

I'm already employing the `'intersection-observer'` polyfill.

A similar issue was raised in #192 and resolved in #194, but it seems that the code has since changed.

**Comment by thebuilder** [comment]
Hey @AnnaCate, that sounds weird - Can you share the options you pass when creating the observer? The `observer` instance should have the `thresholds` array according to the spec.

I'm not seeing in myself running Chrome 86 in a Codesandbox: https://codesandbox.io/s/useinview-ud2vo?fontsize=14&hidenavigation=1&theme=dark

It might make sense to just add the fix implemented in #194 - just to be sure `threshold` is defined.

**Comment by AnnaCate** [comment]
@thebuilder thank you for the quick resolution. FWIW this these are the options being passed: 
```
  const { ref, inView } = useInView({
    threshold: 0.9,
    triggerOnce: true,
  })
```

**Comment by thebuilder** [comment]
That's really weird. The solution I made assumes it's defined, and reverts to 0 threshold otherwise. 

If you are seeing this with an actual threshold, it wouldn't work as expected. Might look into taking the value you supplied in the options.
