### ISSUE TITLE
UseInView doesn't work with display: 'contents'. I would like to observe child element.

### ISSUE THREAD

**Issue by YutamaKotaro** [thebuilder/react-intersection-observer#421]
## Problem
UseInView doesn't work with display: 'contents'.
InView never change to true, no matter what you do.

Sample code is bellow.

```jsx
export default function Log(props: Props) {
  const {children, ...directProps} = props;
  const logContext = useContext(LogContext);
  const {ref, inView} = useInView();
  
  return (
    <LogContext.Provider value={{...directProps, ...logContext}}>
      <div style={{ display: 'contents' }} ref={ref}> 
           {children}
       </div>
    </LogContext.Provider>
  );
}
```

If I remove `display: 'contents', it'll will work fine.But design will collapses.

```jsx
      <div ref={ref}> 
           {children}
       </div>
```

## solution
This problem is due to using current node.
So, I wanna be able to use child element with useInView by using child option.

sample code is bellow

```jsx
export default function Log(props: Props) {
  const {children, ...directProps} = props;
  const logContext = useContext(LogContext);
  const {ref, inView} = useInView({
   child: true,
  });
  
  return (
    <LogContext.Provider value={{...directProps, ...logContext}}>
      <div style={{ display: 'contents' }} ref={ref}> 
           {children}
       </div>
    </LogContext.Provider>
  );
}
```

Would you review my pull request?

**Comment by thebuilder** [comment]
Hey @YutamaKotaro 

Thanks for creating a PR to fix this. This is  the first I have  heard of `display: contents;`, and I'm not sure what an actual usecase for it would be?

So this is a solution for an experimental CSS feature. I'd like to avoid polluting the options with edge case fixes. It's also not clear what a `child` option actually does, from just reading the variable name.

If this is something you need, I think you should be able to accomplish it with your own ref callback, that assigns the child node of the `div`, to the `inViewRef()`. You could even wrap this into an `useChildInView()` hook.

**Comment by thebuilder** [comment]
@isc30 Don't observe the element with `display: contents`. For all intents and purposes it doesn't exists.

**Comment by isc30** [comment]
this isn't a proper "solution". Sometimes we don't have control over `children`'s ref. The way I solved is:

```ts
const [inViewRef, inView] = useInView(...)

const setRefs = useCallback(
  (el: HTMLDivElement) => {
    if (el?.childElementCount > 1) {
      throw new Error(
        'Found multiple DOM children. Please wrap them inside a <div>'
      )
    }

    inViewRef(el?.firstElementChild)
  },
  []
)

return <div ref={setRefs}>...</div>
```
