### ISSUE TITLE
how to check if an element is onEnter or onLeave

### ISSUE THREAD

**Issue by frommainland** [thebuilder/react-intersection-observer#439]
Hi, I am trying to find how to check if an element is entering or leaving the view from documentation, which could be helpful for setting two states for entering and leaving animation. Unfortunately there isn't much in the storybook demo. 

Would you mind giving more examples for element entering or leaving the view? Thank you.

**Comment by thebuilder** [comment]
You could check would the [previous](https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state) `inView` value was. If it changes from `false` to `true` it just entered the viewport, and viceversa.
