### ISSUE TITLE
Add possibility to resubscribe to observer

### ISSUE THREAD

**Issue by vivcogit** [thebuilder/react-intersection-observer#455]
**Is your feature request related to a problem? Please describe.** 
I have to do once some logic when the components appear at the screen. But one of the components is changed by data and I have to resubscribe to the observer, because old version could have already appeared and called this logic

**Describe the solution you'd like**
Adding optional property to resubscribe if this property has changed

**Describe alternatives you've considered** 
Current version resubscribes if IntersectionObserver options have changed, so I can change them to resubscribe, but it isn't a good solution

**Comment by thebuilder** [comment]
Have you considered setting a `key` on your `<InView>` component? This should accomplish the same thing.

```
it('Should recreate observer when trackBy change', () => {
  const { container, rerender } = render(<InView>Inner</InView>);
  mockAllIsIntersecting(true);
  const instance = intersectionMockInstance(container.children[0]);
  jest.spyOn(instance, 'unobserve');

  rerender(<InView key="newValue">Inner</InView>);
  expect(instance.unobserve).toHaveBeenCalled();
});
```

**Comment by vivcogit** [comment]
Sorry for late reply, I've just found time to check you solution. It works. Thank you!

**Comment by cbingrui** [comment]
> Have you considered setting a `key` on your `<InView>` component? This should accomplish the same thing.
> 
> ```
> it('Should recreate observer when trackBy change', () => {
>   const { container, rerender } = render(<InView>Inner</InView>);
>   mockAllIsIntersecting(true);
>   const instance = intersectionMockInstance(container.children[0]);
>   jest.spyOn(instance, 'unobserve');
> 
>   rerender(<InView key="newValue">Inner</InView>);
>   expect(instance.unobserve).toHaveBeenCalled();
> });
> ```
this demo not work with delay option. when the key changes, the inView should be true after the "delay" time out
