### ISSUE TITLE
Fallback in unsupported browser versions

### ISSUE THREAD

**Issue by hoangvvo** [thebuilder/react-intersection-observer#457]
**Is your feature request related to a problem? Please describe.**

If `react-intersection-observer` is used within a browser without support of IntersectionObserver, it will crash the web app:

```
IntersectionObserver is not defined
```

**Describe the solution you'd like** 

Check if IntersectionObserver is defined and fallback `inView` to always be `true` if the browser does not support it.

**Describe alternatives you've considered**

Import intersection-observer polyfill, but I think that would increase the bundle size.

Would you accept a PR to change this?

**Comment by thebuilder** [comment]
Hey @hoangvvo 

This is a recurring suggestion/issue, and the right approach is debatable. I feel like the current approach is the most sensible, and ensures you include the polyfill if needed for your users. Defaulting to `true` can have unintended side-effects, causing other bugs. 

See #307 - You can wrap the `useInView` to provide this functionality in your own application.

The polyfill will not be included in the package itself - It's supported natively in all modern browsers, and very easy to include in your application if needed.

**Comment by hoangvvo** [comment]
Thank you for your answer. Your suggestion seems like it would work for me (I should have checked existing issue :p)

Awesome library by the way!
