### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Friedoo** [thebuilder/react-intersection-observer#462]
First of all - thank you for the great library! :)

We are experiencing a memory leak. In our app we use a view containing a couple of sections. These sections utilize the useInView hook. Everything works fine as long as you stay on the view. The problem happens when leaving the view. I can see that unobserve is executed for each section and memory is cleaned up BUT one thing remains: the RootIds
The RootIds map keeps a reference to the view which does no longer exist. Memory constantly grows when going back to the view and leaving the view.

After visiting the view three times:
![image](https://user-images.githubusercontent.com/19726362/115220290-a7165100-a108-11eb-81c7-a56cae61f40b.png)

A possible solution could be a replacement of an existing element reference if the ID matches(?)

Thank you in advance!
Friedoo

**Comment by thebuilder** [comment]
Nice find.
This might be solved by using a `WeakMap` instead, so making a PR for that now.

**Comment by Friedoo** [comment]
Great!!! Thank you! :)
