### ISSUE TITLE
White screen on Iphone and Ipad

### ISSUE THREAD

**Issue by gochigochi** [thebuilder/react-intersection-observer#465]
When using useInView, after I deploy my app, Iphone and Ipad (Safary) display a white screen instead of the web site. When I remove useInView everything works fine and the page displays normally.

**Comment by thebuilder** [comment]
Hey @gochigochi - You'll need to provide a codesandbox that replicates this issue.
It sounds like a misconfiguration of either the `useInView` hook, or how you are applying styling on your application.

**Comment by gochigochi** [comment]
Solved! Sorry, it wasn't  a problem with react-intersection-observer. I was lacking a IntersectionObserver polyfill
