### ISSUE TITLE
updating skip from false to true after initial run does not kill observer.

### ISSUE THREAD

**Issue by rayventerprise** [thebuilder/react-intersection-observer#466]
I have a state property that will toggle the "skip" property as a performance helper since I am using the hook on 50+ comps. However I notice when skip is set to true after the node was already set, the observer will not remove itself causing needless state updates.

`
const [disableObserving, setDisableObserving] = useState(false)

const {inViewRef, inView} = useInView({
   skip: disableObserving
})

// inViewRef() is called somewhere down the road

useEffect(() => {
setTImeout(() => {
   setDisableObserving(true)
}, 1000)
}, [])

useEffect(() => {
   console.log('still flips to true or false even when I have skip set to true at this exact moment.')
}, [inView])

`

**Comment by thebuilder** [comment]
Can you post a codesandbox example? 
It works fine if you toggle `skip` in the Controls on the [Storybook](https://react-intersection-observer.vercel.app/?path=/story/useinview-hook--basic), and if  `skip` is `true` it will destroy the old one, and skip creating the observer.

https://github.com/thebuilder/react-intersection-observer/blob/master/src/useInView.tsx#L53-L59

**Comment by rayventerprise** [comment]
is there a chance the story book is recalling the setRef function when skip changes? I believe the problem is you have to recall setRef which would be redundant as the ref node may already be initially set when the node was mounted.

**Comment by thebuilder** [comment]
It recreated the ref function when skip changes, which causes React to call it with the mode again

**Comment by rayventerprise** [comment]
Is there anyway around having the ref be essentially the new state setter? I use framer-motion and they dont support automatically recalling refs on function update.

https://github.com/framer/motion/issues/742

**Comment by thebuilder** [comment]
I think https://github.com/framer/motion/blob/main/src/motion/utils/use-motion-ref.ts might need to perform an update by adding the `externalRef` to the dependency array.

**Comment by thebuilder** [comment]
So, this isn't a problem with `react-intersection-observer`, but with how `framer-motion` handles `ref` values. The `ref` provided by `react-intersection-observer` needs to be a callback function, since this is the only way it can correctly update if options changes.

 I've created https://github.com/framer/motion/pull/1119 that should fix the issue - Let's see what happens there.
