### ISSUE TITLE
Struggling with rootMargin settings

### ISSUE THREAD

**Issue by derwaldgeist** [thebuilder/react-intersection-observer#467]
I read a lot about the "rootMargin" settings option, in both the docs and issues, but I still don't really get it. I thought it was pretty much the same as what `waypoints` defines as `offset`. But I can't get it to work. In my use-case, I want to implement endless scrolling, so if the user reaches about 300px before the end of the page, additional content is being loaded.

I tried a lot of combinations, yet the trigger only fires if I reach the very bottom of the page, which is too late. It seems to work if the scroll container is a scrollable div, but it does not work well if the scrolling container is the document itself. Although my code is based on React classes, I even tried switching to a functional component, so I could 1:1 copy your sample. But still to no avail.

I am also confused by the name `rootMargin`, as the root is defined as the scroll container. Why should this root have a margin? I would expect that the triggering element itself has a margin (or better: an offset).

I think it would help if you could provide some kind of image / sketch how this actually works. Thanks.

**Comment by thebuilder** [comment]
I'd recommend reading up on Intersection Observers in general - This library is using the native API and options, including the `rootMargin` - It's not just something i came up with.

* https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/rootMargin
* https://developers.google.com/web/updates/2016/04/intersectionobserver

For infinite scrolling you'll want to use the "sentinel" pattern, by adding an element with an observer to the end of your list that triggers the load. Make sure to give this a positive `rootMargin`  value, so it triggers early, like `rootMargin: '200px 0px',`.

**Comment by derwaldgeist** [comment]
Thanks for the links.

> For infinite scrolling you'll want to use the "sentinel" pattern, by adding an element with an observer to the end of your list that triggers the load.

This is exactly what I did. It kinda works, but not if the root is the document.
