### ISSUE TITLE
Add default visibility for jest

### ISSUE THREAD

**Issue by wbolduc** [thebuilder/react-intersection-observer#468]
In some of my tests I use async components that happen to react-intersection-observer. They show up in 2 stages. First get their data asynchronously, then they check if they're visible. For tests that happen to use these components it's unclear when to call mockAllIsIntersecting.

Ideally I would like some sort of jest function to default the visibility state of all instances of useInView to true regardless of when they mount.

I've tried this to no avail (and admittedly I'm pretty new to jest)
`
jest.mock("react-intersection-observer", () => {
	const originalObserver = jest.requireActual("react-intersection-observer");
	const { mockAllIsIntersecting } = jest.requireActual(
		"react-intersection-observer/test-utils"
	);

	return {
		__esModule: true,
		...originalObserver,
		useInView: jest
			.fn((...args) => originalObserver.useInView(...args))
			.mockImplementationOnce((...args) => {
				setTimeout(() => mockAllIsIntersecting(true), 200);
				return originalObserver.useInView(...args);
			}),
	};
});
`

**Comment by thebuilder** [comment]
Are you using something like Testing Library to handle Async tests? 
https://testing-library.com/docs/dom-testing-library/api-async

You should be able to `await` your components being ready, and then triggering `mockAllIsIntersecting`.

Also note that `test-utils` is already mocking the `IntersectionObserver`, allowing you to spy on a the method. I think you could also use this to trigger an update after a new instance is created.
