### ISSUE TITLE
Safari issue: Can't find variable: IntersectionObserver

### ISSUE THREAD

**Issue by DoneDeal0** [thebuilder/react-intersection-observer#469]
**Describe the bug** A clear and concise description of what the bug is.
The hook doesn't work with Safari (my version is 11.1). The error thrown is: `Can't find variable: IntersectionObserver`.

**To Reproduce** Try and recreate the issue in a **Codesandbox**:
(https://codesandbox.io/s/useinview-ud2vo?fontsize=14&hidenavigation=1&theme=dark)
this is your own demo, I havn't modified a single line.

**Expected behavior** A clear and concise description of what you expected to
happen.
Provide a polyfill, or disable the observer, but don't make the page crash. 

**Desktop (please complete the following information):**

- OS: osx
- Browser safari
- Version 11.1

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by thebuilder** [comment]
The `IntersectionObserver` isn't supported in older versions of Safari, so you need to provide a polyfill. See [caniuse](https://caniuse.com/intersectionobserver) for supported browsers.

See also the readme for details on how you can include a polyfill:
https://github.com/thebuilder/react-intersection-observer#intersection-observer

**Comment by DoneDeal0** [comment]
Aa cool, I didn't see it in the doc at first glance, thanks!
