### ISSUE TITLE
Set root after mount for SSR

### ISSUE THREAD

**Issue by allan2** [thebuilder/react-intersection-observer#477]
I'm using Next.js and I'd like to set root to a specific element.

`window` and `document` are only accessible after mount. 

Is there an SSR-friendly way to wait until the component is mounted to set root?

Note: `useEffect` fires only after mount.

```
// this won't work; document not defined
const { ref, inView } = useInView({
    root: document.querySelector(".myroot"),
});

useEffect(() => {
    if (inView) {
        doSomething();
    }
}, [inView, doSomething]);
```

**Comment by thebuilder** [comment]
In this case, the the simplest way would be check if rendering on the server or client before using `window` or `document`.

```js
{
  root: typeof document !== 'undefined' ? document.querySelctor('.myroot') : undefined
}
```

**Comment by thebuilder** [comment]
It's safe, since the IntersectionObserver doesn't trigger until the client is hydrated anyway.

**Comment by thebuilder** [comment]
You could use the new Intersectionobserver v2. Support is still limited https://caniuse.com/intersectionobserver-v2

Otherwise it might make sense to look at the scroll position?

**Comment by allan2** [comment]
Thanks! I got it working in v1 and v2.
I used two observers for v1, one above the target div. When that is hidden but the target is visible, I achieve my goal.

https://f4rwj.sse.codesandbox.io/
https://codesandbox.io/s/competent-cohen-f4rwj?file=/pages/index.tsx
