### ISSUE TITLE
root margin not working as intended because of overflow-y: scroll

### ISSUE THREAD

**Issue by StErMi** [thebuilder/react-intersection-observer#481]
**Describe the bug** A clear and concise description of what the bug is.

I'm developing a mobile application and I need to handle the infinite scroll loader of a grid. I would like to implement it in a way that as soon as the user reaches 500px before the "sentry" element it will trigger the `fetchNextPage()` method.

I think that the main problem is the layout:

```
<div className="flex flex-col h-screen">
  <div className="flex-none min-h-20 safe-top bg-red-700 z-10">
    <Header />
  </div>
  <div
    className="flex-grow overflow-y-scroll bg-gray-100"
  >
    <Content>
      <InView rootMargin="500px 0px" threshold={0} as="div" onChange={(inView, entry) => console.log('Inview:', inView)}>
        {({inView, ref, entry}) => (
                <Grid></Grid>
                <SentryElement ref={ref}></SentryElement>
        )}
      </InView>
    </Content>
  </div>
  <div className="flex-none safe-bottom bg-white z-10">
    <Footer />
  </div>
</div>
```

it seems that the `rootMargin` is totally ignored because of the `overflow-y-scroll` but I cannot remove the `overflow-y-scroll` because otherwise the `header` and `footer` won't be sticky to the top and bottom.

UPDATE

I've created a stackbliz to reproduce the problem: https://stackblitz.com/edit/tailwind-jit-swjhqa?file=pages/index.js

How can I solve this issue?

**Comment by StErMi** [comment]
Updated with a working example

**Comment by thebuilder** [comment]
This is most likely an issue with the Intersection Observer browser implementation.

**Comment by StErMi** [comment]
> This is most likely an issue with the Intersection Observer browser implementation.

I think that the problem is that the Grid is inside a container with overflow-y scroll. How should I organize the code in order to make my content scrollable and be able to use the rootMargin?

**Comment by thebuilder** [comment]
Ah, you'd need to set the `root` as the overflow container.

**Comment by StErMi** [comment]
> Ah, you'd need to set the `root` as the overflow container.

is there an example that uses the root props?

**Comment by thebuilder** [comment]
https://react-intersection-observer.vercel.app/?path=/story/inview-component--with-root-and-root-margin
