### ISSUE TITLE
Hook useInView "inView" doesn't trigger on small devices (because content overflows?)

### ISSUE THREAD

**Issue by Vadorequest** [thebuilder/react-intersection-observer#482]
#### **Describe the bug**

When the device's size is too small, our page's content overflows a bit on the right and the animations don't trigger. We noticed the `inView` prop returned by `useInView` doesn't change.

On desktop (and also on larger mobiles), it works fine:
![image](https://user-images.githubusercontent.com/3807458/121026138-2093fc80-c7a6-11eb-8008-622a955ed07e.png)

> The animation displays the 3 text paragraphs upon scroll, one by one

![image](https://user-images.githubusercontent.com/3807458/121026396-618c1100-c7a6-11eb-8a72-a9e13e6b4446.png)

Also, we used responsive design to avoid the issue, and it works well in all our in-browser tests.
But, some users have reported not seeing the content on some devices (IOS, Iphone X, Safari mobile).

Our in-browser tests using the same device dimensions work as expected.

#### **To Reproduce** Try and recreate the issue in a **Codesandbox**:

We're not able to reproduce it on Desktop.

Here is the source code of one of the components:

```tsx
import {
  Flex,
  IconButton,
  Text,
} from '@chakra-ui/react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  domAnimation,
  LazyMotion,
  m as motion,
  useAnimation,
} from 'framer-motion';
import React, { useEffect } from 'react';
import { useInView } from 'react-intersection-observer';

type Props = {}

export const FinancialHelp: React.FunctionComponent<Props> = (props): JSX.Element => {
  const controls = useAnimation();
  const [ref, inView] = useInView();

  useEffect(() => {
    if (inView) {
      controls.start('visible');
    }
  }, [controls, inView]);

  return (
    // Optimize using async loading - See https://www.framer.com/api/motion/guide-reduce-bundle-size/#how-to-reduce-bundle-size
    <LazyMotion features={domAnimation} strict>
      <Flex
        flexDirection={'column'}
        mt={'25%'}
      >
        <Flex
          alignItems={'baseline'}
          flexDirection={{ base: 'column', sm: 'row', md: 'row' }}
        >
          <motion.h4
            ref={ref}
            animate={controls}
            initial="hidden"
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1 },
              hidden: { opacity: 0 },
            }}
          >
            Argent
          </motion.h4>
          <motion.div
            ref={ref}
            className={'rocket-icon financialHelp-icon'}
            style={{ translateX: '-160px' }}
            animate={controls}
            initial="hidden"
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 },
            }}
          >
            <IconButton
              variant="primary"
              aria-label="icon"
              icon={<FontAwesomeIcon icon="money-bill-alt" />}
              size="md"
            />
          </motion.div>
        </Flex>
        <motion.div
          animate={controls}
          initial="hidden"
          transition={{ duration: 0.3 }}
          variants={{
            visible: { opacity: 1 },
            hidden: { opacity: 0 },
          }}
        >
          <Text>
            Tu reçois une <em>bourse</em> versée mensuellement et un <em>prêt d'honneur</em> à taux zéro sans garantie
          </Text>
        </motion.div>
      </Flex>
    </LazyMotion>
  );
};

```

#### **Expected behavior** 

It should trigger `inView=true` whenever part of the content is on the viewport, it's supposed to be the default behavior (and we didn't change it).

**Comment by thebuilder** [comment]
You shouldn't assign the `ref` to multiple elements - Instead create multiple `useInView` hooks, or wrap it inside individual components.

**Comment by Vadorequest** [comment]
I didn't write that part of the code and I'm not so familiar with `react-intersection-observer`.

What's the consequence of assigning the same ref to several elements? Is it a recommandation specific to this library or is it a global rule to the React world?

**Comment by Vadorequest** [comment]
I removed the duplicated `ref` assignments and move them to the top-level element of the component. 

I wonder if it's even valid to apply the `ref` to a sub-element, from what I've noticed it detects presence in the viewport only for the top-level element of the component anyway.

**Comment by thebuilder** [comment]
This is a global React thing. A `ref` is the reference to a single DOM element, so by assigning it multiple times you'd end up with it only observing the last element.
