### ISSUE TITLE
version in package.json stuck at 8.26.1

### ISSUE THREAD

**Issue by Ognian** [thebuilder/react-intersection-observer#485]
Please update version field in package.json to the actual version.
This haven't happened since 8.26.1

**Comment by thebuilder** [comment]
The version is controlled by semantic release running with Github Action, and the version in the committed package.json isn't updated as a result of this. https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository

Not sure I see the reason for committing it every time a new release is made. The versions are already tagged to the git commits.

**Comment by Ognian** [comment]
Hmm, you are right. I looked at the repo since it is easier than going thru node_moduels... Maybe you should change the version to 0.0.0 so that someone looking at github realizes that there is more going on... The original problem was that Webstorm complained about a version mismatch between package.json and the node_modules content and offers a `npm install` in a loop ... Anyway I looked up the version now in node_modules and it is indeed 8.32.0
