### ISSUE TITLE
triggerOnce option is not working in local/dev environment

### ISSUE THREAD

**Issue by niraj1234567890** [thebuilder/react-intersection-observer#487]
Is there a way to test the functionality of trigger once in local/dev environment. Here is my implementation.

```
<InView triggerOnce>
                                    {({ inView, ref, entry }) => (
                                        <div className="main-node" ref={ref}>
                                            <CardNodeMainContainer key={id} id={id}/>
                                        </div>
                                    )}
</InView>
```
inView gives always true in my case.

**Comment by thebuilder** [comment]
Guessing it's true because it starts in view? Wouldn't trigger again after it becomes true

**Comment by niraj1234567890** [comment]
It was my bad. I misunderstood the inView functionality. I wasn't conditionally checking the 'inView' and expecting that the component inside the <InView></InView> will only render if 'inView' is true. Turns out, the component inside the 'InView' Component will always render. Thanks for your prompt response. I am closing this issue and here is the change I made to make it work.

```
<InView triggerOnce>
                                    {({ inView, ref, entry }) => (
                                        <div className="main-node" ref={ref}>
                                        {inView ? <CardNodeMainContainer key={id} id={id}/> : <div style={{height: '50px'}}></div>}
                                        </div>
                                    )}
</InView>
```
