### ISSUE TITLE
rootMargin is not working

### ISSUE THREAD

**Issue by niraj1234567890** [thebuilder/react-intersection-observer#488]
I am trying to implement rootMargin option and it's not working at least in my case. I have implemented it like this:

```
<InView triggerOnce rootMargin={"200px 0px 200px 0px"}>
                                    {({ inView, ref, entry }) => (
                                        <div className="main-node" ref={ref}>
                                            
                                        {inView ? <CardNodeMainContainer key={id} id={id}/> : <div style={{height: '50px'}}></div>}
                                        </div>
                                    )}
</InView>
```

Does any one have a clue on why it's not working?

**Comment by thebuilder** [comment]
You'll need to provide more context - Root Margin is working, but maybe it's not doing what you expect it to? 
Create a Codesandbox that replicates the issue, and describe what about it isn't working.
