### ISSUE TITLE
[Question] Intersection observer causes framer motion elements re-rendering

### ISSUE THREAD

**Issue by Ikkevoid** [thebuilder/react-intersection-observer#497]
I'm trying to track sections on my website so that I can show which menu item is selected, That part works really well, but the problem is when I start using framer motion in the sections that I track, Every time U scroll to another section, the div where the motion component is, re-renders. Is that how it should work? And how can I make it work, so the animation only changes when the user clicks the button?

[Simple example: ](https://1fvmv.csb.app/)
[Code](https://codesandbox.io/s/react-intersection-observer-and-framer-motion-1fvmv?file=/src/App.js)

**Comment by thebuilder** [comment]
By defining your components like `Section` and `Animate` inside your `App` function, you are essentially recreating the components on every render. Whenever the `onChange` is triggered, it updates the state recreating the `Section` component, and triggering a new `onChange` event.

**Comment by Ikkevoid** [comment]
I'm really sorry that I asked this question, I was trying to find a problem in the parts where there was nothing wrong. Thank you so much for making me aware of this problem.
Thanks for helping me, and for creating such an awesome lib as this.
I wish you have a nice day 😄

**Comment by thebuilder** [comment]
No problem!
