### ISSUE TITLE
Confusion on storybook example

### ISSUE THREAD

**Issue by Paxatax** [thebuilder/react-intersection-observer#498]
Hi,

First off, fantastic hook, it has been super helpful in my project, so thank you for that.

I am having a harder time understanding the storybook example below and was wondering if you could help clear the confusion.

![Screen Shot 2021-08-08 at 11 35 23 AM](https://user-images.githubusercontent.com/81934985/128637575-eafac90d-f8a3-4fac-8f7a-5ef8f186ac37.png)

The purple box is set as the root, and then rootMargin is being applied to it - however it is still intersecting with the viewport? (green checkmark goes red when it is scrolled outside of the view, based on the threshold + rootMargin). How does this work? In this example, what is the target?

It kind of looks like the viewport is the root, the purple box is the target, and then you're applying a "targetMargin"(not an actual thing) to the target. 

Thank you in advance, I really appreciate it.

**Comment by thebuilder** [comment]
Sounds like you got the right understanding, of how it's been applied. 
All the names and implementation is based on the IntersectionObserver API if you want to read more into how it works.

**Comment by Paxatax** [comment]
Thanks for the quick reply! 

If the viewport is the root, and the purple box is the target, how are you applying margin to the target?

**Comment by thebuilder** [comment]
I guess `rootMargin` can be a bit confusing. But the dotted lines around the purple box indicate when it would hit the margin. It's useful to trigger intersection early or late, with a known amount of spacing. When using `threshold` it's a percentage of the elements size, which can potentially mean it would never trigger (if the threshold is larger then the root). 
If you change it in the controls, you should see it updated so you can see how it affects the trigger point. There's a small indicator in the upper corner that also showcases the state, so you can see it even if the box is outside the viewport. :)

**Comment by Paxatax** [comment]
Ah ok, the dotted lines are just visual representations of when the viewport's rootMargin would trigger an entry on the target?

By the look of it, the target (purple box) was having its own "rootMargin" applied (like a targetMargin, of sorts.. which goes against everything I had read online).

**Comment by thebuilder** [comment]
Yeah - Just visual guidelines. They could have been set with global styling, and the inView would trigger when they crossed paths. But, it would be hard to showcase a negative margin since that would just be outside the viewport. Seems more visually clear with the dotted line. :)

**Comment by Paxatax** [comment]
Perfect, thank you very much for helping clear that up @thebuilder! Really appreciate it.
