### ISSUE TITLE
Type definition for IntersectionObserverProps should include style

### ISSUE THREAD

**Issue by wrumsby** [thebuilder/react-intersection-observer#51]
In the [render callback example](https://github.com/thebuilder/react-intersection-observer#render-callback) the example code shows a `style` prop being used on the `Observer` component.

This is not documented in the [Props section](https://github.com/thebuilder/react-intersection-observer#props) or in the type definition (`index.d.ts`).

Assuming `style` is a valid property not having this declared in the type definition leads to "property 'style' does not exist on value of type" errors when using TypeScript (for at least TypeScript 2.3.4).

**Comment by thebuilder** [comment]
The `style` prop is being forwarded to to wrapping element, the `div`, along with all other unknown props. How does Typescript handle rest props?

Med venlig hilsen
Daniel Schmidt
________________________________

**Comment by thebuilder** [comment]
Style is no longer in the example, so closing this
