### ISSUE TITLE
Change default root or remove it and make it a required prop

### ISSUE THREAD

**Issue by kylemh** [thebuilder/react-intersection-observer#533]
According to MDN, the `root` option cannot be set to an instance of `Document` on iOS. Therefore, it seems like a bad idea to make `document` the default value for `root`. Would you instead accept `document.body` or make the option required?

https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver#browser_compatibility

**Comment by thebuilder** [comment]
Hi @kylemh - The library isn't actually setting the `root` to `document`. The readme just list `document`as the default, as that is what the [browsers do](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/root) (even if you can't set `options.root` to document as the user). Same goes for all the default values list - It's the implementation default.
