### ISSUE TITLE
Use typescript generics to be able to type the entry.target

### ISSUE THREAD

**Issue by mittnavnermike** [thebuilder/react-intersection-observer#537]
Let's say I'm making a pause/play video when in view hook. I would like to specify that the `ref` should be a `HTMLVideoElement`, because if not – `.play()` and `.pause()` functions do not exist.

I'd love to be able to define what the element type for `ref` should be. Not quite sure what the API should look like, but something with generics along the lines of:
```typescript
const { ref } = useInVIew<HTMLVideoElement>()
```

Ideally if I tried to do the below it would give me an error stating that `HTMLDivElement` is not `HTMLVideoElement` or something like that.

```typescript
const SomeComponent = () => {
  const { ref } = useInVIew<HTMLVideoElement>()

  return (
    <div ref={ref}>This should error</div>
  )
}

```

I could not find the documentation for this – I'm sorry if I'm re-raising or missed something in the docs

**Comment by thebuilder** [comment]
The type of the `ref` function matches what the IntersectionObserver expects (`Element`). 

But, you can't use it in your own components. It's just a function that takes an `Element`. Instead you should create and attach your own `ref` to the element. This way you can also set it to whatever type you might need.

See: https://github.com/thebuilder/react-intersection-observer#how-can-i-assign-multiple-refs-to-a-component

**Comment by ChrisCrossCrash** [comment]
Following the linked ["How can I assign multiple refs to a component?"](https://github.com/thebuilder/react-intersection-observer#how-can-i-assign-multiple-refs-to-a-component) section, I get the TypeScript error:

```
Cannot assign to 'current' because it is a read-only property.ts(2540)
```
However, the component is at least working correctly.

Here's the relevant code from my component:
```
const videoRef = useRef<HTMLVideoElement>(null)
  const { ref: inViewRef, inView } = useInView()

  // Use `useCallback` so we don't recreate the function on each render
  const setRefs = useCallback(
    (node: any) => {
      // Ref's from useRef needs to have the node assigned to `current`
      videoRef.current = node // ERROR ON THIS LINE
      // Callback refs, like the one from `useInView`, is a function that takes the node as an argument
      inViewRef(node)
    },
    [inViewRef]
  )

  useEffect(() => {
    // TODO: Logic to play/pause video when inView changes
    if (!videoRef.current) {
      throw new Error('videoRef.current is null')
    }
    if (inView) {
      videoRef.current.play()
    } else {
      videoRef.current.pause()
    }
  }, [inView])
```
