### ISSUE TITLE
Continuous state updates with react-merge-refs

### ISSUE THREAD

**Issue by donmccurdy** [thebuilder/react-intersection-observer#542]
If I understand correctly, the `useInView` hook changes state — causing its parent component to render — when there is any change to the intersection entry. This can be a lot (e.g. while scrolling) and in some applications (e.g. WebGL rendered at 60fps, see https://docs.pmnd.rs/react-three-fiber/advanced/pitfalls) that is a substantial performance hit. For my application, I only need to make changes when boolean visibility changes from true to false or false to true, and the fractional state changes beyond that cause overhead. Is this an option that could be provided?

**Comment by thebuilder** [comment]
The hook only updates the state when the intersection triggers - Unless you set a threshold array value, this will only happens when it enters the viewport, and when it leaves. 

Are you actually encountering any issues?

**Comment by donmccurdy** [comment]
Glad to hear that's the intended behavior! I'm seeing continuous updates to state in my project, and assumed that was by design. I'll try to track down what's happening and provide a repro case if it's not simply user error.

**Comment by thebuilder** [comment]
Make sure your styling doesn't impact the layout when visibility changes.

**Comment by donmccurdy** [comment]
Here's a simplified case reproducing the issue:

https://codesandbox.io/s/continuous-intersection-repro-o9ws74?file=/src/index.js

The problem seems to be related to mixing `react-intersection-observer` with `react-merge-refs`. If I remove `react-merge-refs` — which I'll look into, but isn't totally trivial in my real application — there's no problem.

Current Behavior:

1. Open sandbox, notice that `Renders` counter increases continuously.
2. Scroll down to the logo, notice that intersection event fires and font turns red.

Expected Behavior:

1. Same as above, but without continuous rendering.

Other notes:

1. The example also includes a custom of `useInView` function, which you can uncomment to test. It doesn't render continuously (✅) and updates on intersection (✅) but doesn't update when the element leaves the viewport (❌).

I'm not sure whether this is a problem in one package or the other, or just a misunderstanding of how react refs work — totally understand if this isn't within the scope of `react-intersection-observer`. 🤔

**Comment by thebuilder** [comment]
See the FAQ: https://github.com/thebuilder/react-intersection-observer#how-can-i-assign-multiple-refs-to-a-component

`react-merge-refs` has an open issue for the behavior you are seeing: https://github.com/gregberge/react-merge-refs/issues/5
