### ISSUE TITLE
'InView' cannot be used as a JSX component.   Its instance type 'InView' is not a valid JSX element.

### ISSUE THREAD

**Issue by emmanuelByte** [thebuilder/react-intersection-observer#547]
I have been battling with this error and can't find the right type for Inview
import InView  from 'react-intersection-observer';
...
 <InView>
        {({ inView, ref, entry }) => (
          <>
</>
)}

      TS2786: 'InView' cannot be used as a JSX component.
  Its instance type 'InView' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/home/user/Desktop/Projects/node_modules/@types/react-router-dom/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.

**Comment by thebuilder** [comment]
Could be a mismatch between `@types/react` from your local repo and  react router? 

Your example seems to be missing code, including the `<InView>`?

**Comment by gatoledo1** [comment]
hello @emmanuelByte,
 
I was having the same problem.
In my case, I had a typing conflict with a library no longer used, so I was able to delete

your conflict comes from `@types/react-router-dom`, an essential typing, you might consider correcting your project typings, or having the typescript ignore the sentence.

JS: `//@ts-ignore`
JSX: `{/* @ts-ignore */}`
