### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by iamludal** [thebuilder/react-intersection-observer#555]
With version 9.2.1, I get this error:
![image](https://user-images.githubusercontent.com/44783088/171689158-d6d58ef3-7abe-43eb-9821-1a1b58ddbbc2.png)

I cannot reproduce in CodeSandbox because I can't use react-intersection-observer@9.2.1.

I don't get the error when I downgrade to version 9.2.0

**Desktop (please complete the following information):**

- OS: macOS
- Browser: N/A

**Comment by mrchrishahn** [comment]
Have the same issue. 

Running in a node:14-alpine Docker Container both version 9.2.0 and 9.2.1 are breaking. 

I don't get where the `.module.js`

**Comment by thebuilder** [comment]
Sorry about that - Something's up with microbundle.

**Comment by thebuilder** [comment]
Are you all running this with Webpack? It's the bundler failing to read the modern script correctly.

**Comment by edoardolunardi** [comment]
Yes, I'm using `next.js` with `webpack` 5.

**Comment by thebuilder** [comment]
Fixed in 9.2.2
