### ISSUE TITLE
trackVisibility and delay

### ISSUE THREAD

**Issue by darkkatarsis** [thebuilder/react-intersection-observer#558]
**Describe the bug** A clear and concise description of what the bug is.
I know that trackVisibility and delay are new functionalities and are tagged as "lab", but I've already had the opportunity to test a bit and as with chrome there are no problems, delay does not work on safari.

**To Reproduce** Try and recreate the issue in a **Codesandbox**:
Using a safari browser or an ios phone

**Expected behavior** A clear and concise description of what you expected to
Working delay

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Safari
- Version 15.5 (17613.2.7.1.8)

**Smartphone (please complete the following information):**

- Device: iPhone12
- OS: iOS15.6
- Browser Safari

**Additional context** Add any other context about the problem here.

**Comment by thebuilder** [comment]
https://caniuse.com/intersectionobserver-v2 it's still unsupported in Safari.
