### ISSUE TITLE
Observer state is always true when renderd by array

### ISSUE THREAD

**Issue by linrz** [thebuilder/react-intersection-observer#56]
```js
import Observer from 'react-intersection-observer'
const images = [image1, image2, ...image10];

images.map((i, index) => {
 return (
    <Observer>
      {inView => <img src={i} key={index} />}
    </Observer>
  );
};
```
These images states' are invisible at first. Then they are all visible at same time. So, can we use this package to lazyload images which rendered by array ?

**Comment by thebuilder** [comment]
You can use the observer for that, yes. Make sure the images have the correct height while hidden. If you want to load them all at the same time, you could move the loop inside the observer.
