### ISSUE TITLE
`useInView`'s `inView` always returns `undefined` with Next.js v12.1.6, only detects changes with `<InView/>` ?

### ISSUE THREAD

**Issue by AndrewNow** [thebuilder/react-intersection-observer#566]
Hey all, 

I'm having trouble getting react-intersection-observer to work with Next specifically. 

Previously, with Gatsby, I was able to run the hook like so:

```js
import React from 'react';
import { useInView } from 'react-intersection-observer';

const Component = () => {
  const { ref, inView, entry } = useInView({
    threshold: 0,
  });

  return (
    <div ref={ref}>
      <h2>{`Header inside viewport ${inView}.`}</h2>
    </div>
  );
};
```

With Next, using this method, `inView` seems to always return `undefined`. The only way I was able to get a response from the intersection observer is when I would use the `<InView/>` component, but this is not an ideal solution for me as my page is going to require multiple instances of the intersection observer (I'm building a sidebar table of contents that highlights the the title of a given section when that section is in view). Furthermore, I need to access the value of `inView` outside of the scope of the `<InView/>` component.

Could anyone please provide any guidance, specifically on how to use mutliple instances of `useInView` with Next.js?

I'm using v9.3.3 of `react-intersection-observer`.

### Here's a minimum reproduction: 

https://codesandbox.io/s/next-js-forked-0u2l96?file=/index.js

**Comment by thebuilder** [comment]
When using object destructuring you need to use the `ref` and `inView` name (and assign them other names if needed):

```ts
const { ref: firstRef, inView: firstInView } = useInView({
    root: null,
    threshold: 0.2,
    triggerOnce: false
  });
```

Otherwise use the array, where the order is fixed:

```ts
const [ firstRef, firstInView ] = useInView({
    root: null,
    threshold: 0.2,
    triggerOnce: false
  });
```

**Comment by AndrewNow** [comment]
Is it possible to use the refs created in this array for `scrollIntoView()` ? At the moment the refs.current return undefined

**Comment by thebuilder** [comment]
No, this `ref` is a callback function that you can't use. If you need to access the `ref` for the element, you should create your `useRef` for it. See the FAQ: https://github.com/thebuilder/react-intersection-observer#how-can-i-assign-multiple-refs-to-a-component
