### ISSUE TITLE
delay property dosen't work on firefox

### ISSUE THREAD

**Issue by gioiadev** [thebuilder/react-intersection-observer#574]
**Describe the bug**
 Firefox dose not respect the delay property.

To Reproduce: https://codesandbox.io/s/useinview-forked-tj017t

**Expected behavior** 
Respect delay property.

- OS: windows 11
- Browser: chrome works ok, firefox not. didn't try others.
- Version:
- chrome: 103.0.5060.114
- firefox: 102.0 and 102.0.1

**Comment by thebuilder** [comment]
Delay is part of Intersection Observer v2. It works alongside `trackVisibilty`, so it does nothing on its own. This library just forwards the values. It's up to the browser how to deal with them (if they are even supported) 

It's still unsupported on Firefox:

https://caniuse.com/intersectionobserver-v2

**Comment by thebuilder** [comment]
See also: https://github.com/thebuilder/react-intersection-observer#intersection-observer-v2-

**Comment by gioiadev** [comment]
Got it. Thanks.
