### ISSUE TITLE
threshold does not work in Chrome / webkit

### ISSUE THREAD

**Issue by LMS007** [thebuilder/react-intersection-observer#582]
Edge / Chrome both ignore threshold--essentially everything is treated as a value of 0.  Or in other words, the event triggers as soon as the first pixel is visible. Firefox on the other hand has correct behavior and you can see differences between values from 0 to 1.  I have not tried Safari yet.

**Comment by thebuilder** [comment]
`threshold` is working fine in Chrome/Edge - You can test it on the demo site: https://react-intersection-observer.vercel.app/?path=/story/useinview-hook--with-threshold-50-percentage
If you are seeing issues, it's most likely related to how you are using the IntersectionObserver. Maybe styling is not the same between browsers - e.g. height is collapsed on the element you are observing? 

If you believe it to still be an issue, please provide a reproducible example.
