### ISSUE TITLE
Why useInView cause the component to re-render twice?

### ISSUE THREAD

**Issue by gremo** [thebuilder/react-intersection-observer#592]
First thank you 🙏 for this great library!

I'm rendering `ProductsListViewItem` 16 times in a list (first `console.log`). After adding `useInView`, there are two more renderings for each one. I would expect just one more rendering when `inView` pass from `false` to `true`.

```typescript
export const ProductsListViewItem = ({ product }: ProductsListViewItemProps) => {
  console.log('[ProductsListViewItem] Rendering...');

  const { ref, inView } = useInView({ triggerOnce: true, delay: 500 });

  return (<div ref={ref}></div>);
}
```

![Immagine 2022-11-22 115548](https://user-images.githubusercontent.com/1532616/203296625-5b7ea26c-312f-4707-a11f-3ad44aa9d705.png)

**Comment by thebuilder** [comment]
It's to solve this issue: #572

**Comment by gremo** [comment]
Hi, thanks. I'm already at 9.4.1 but still experiencing the issue. What I'm missing?

**Comment by thebuilder** [comment]
It's working as intended - It's a way to deal with the `ref`, in sane manner for all use cases. #572 changed how the `ref` is handled, which is what causes the extra render.

**Comment by thebuilder** [comment]
Are you seeing actual issues with this? It shouldn't have an impact on performance under normal circumstances.
