### ISSUE TITLE
How to use multiple observer like InView ? 

### ISSUE THREAD

**Issue by Waqas-Jani** [thebuilder/react-intersection-observer#601]
This is very good lib and Thanks for it
i have checked the docs [https://react-intersection-observer.vercel.app/?path=/docs/inview-component--multiple-thresholds]
there is a example how to use multiple observer but there is no code avaiable 
```sh 
 <InView as={"div"} triggerOnce={true}>
          {({ inView, ref }) => (
            <div ref={ref} />
           
          )}
        </InView>
 <InView as={"div"} triggerOnce={true}>
          {({ inView, ref }) => (
            <div ref={ref} />
           
          )}
        </InView>
```

i'm using like above but when first trigger then all other also triggerd 

Thanks

**Comment by thebuilder** [comment]
That looks correct. Keep in mind that they will trigger at the same time of they are both empty/unstyled (since they are both in view).

It might be easier to keep one observer post component, but that's just to make it simpler for you to manage state.
