### ISSUE TITLE
InView component not working when React App with Vite uses TailwindCSS

### ISSUE THREAD

**Issue by slyofzero** [thebuilder/react-intersection-observer#606]
I am working on a React App with Typescript and Tailwind built using Vite. Here I tried using the InView component provided by [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer) but found out that if my `main.tsx` file is using Tailwind styles instead of conventional CSS, the component doesn't work.

This is my [codesandbox](https://codesandbox.io/p/github/slyofzero/-react-intersection-observer-issue/main?file=%2Fsrc%2Fmain.tsx&workspace=%257B%2522activeFileId%2522%253A%2522cldsuuy2v00068thw1rnwdmqo%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252Fmain.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cldsuv0hg000e2a6engaqxiyf%2522%253A%257B%2522key%2522%253A%2522cldsuv0hg000e2a6engaqxiyf%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522cldsv88bk000t2a6ez8lwziuf%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cldsuv8ea009r2a6eqlfgq5ll%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cldsuv6wp005b2a6ed45y4bhf%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cldsuv0hg000e2a6engaqxiyf%2522%252C%2522spacesOrder%2522%253A%255B%2522cldsuv0hg000e2a6engaqxiyf%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D) where I have posted my project with the related project files.

To reproduce the issue I am facing, just replace line 4 in `src/main.tsx` from
```
import "./Styles/tailwind.css";
```

to
```
import "./Styles/temp.css";
```

**Comment by thebuilder** [comment]
It works fine with react, vite and tailwind. Most likely your styles aren't loaded correctly - make sure they are applied as expected.

**Comment by thebuilder** [comment]
Your `temp.css` doesn't include the Tailwind base styles, so the body element contains 8px margin. This results in your second section being pushed out of the viewport.
