### ISSUE TITLE
Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by alexRicc2** [thebuilder/react-intersection-observer#612]
Does not use passive listeners to improve scrolling performance

I'm using the package in my NEXTjs project as you can se below.

import { InView } from 'react-intersection-observer'
import Image from 'next/image'

const AdvertisementSetion = () => {

  return (
    <Container bg={2}>
      <InView triggerOnce={true}>
        {({ inView, ref }: any) => (
          <div className={`${s.bg}`} >
            <div className={s.container}>
                 .....

When the project is deployed in VERCEL and put to be analyzed in PageSpeed Insights I get the following warning
![image](https://user-images.githubusercontent.com/81180853/218188897-bc821742-c53e-49d3-983b-3c128f00af0d.png)
What is the workaround for this? you can see for yourself here: https://pagespeed.web.dev/report?url=https%3A%2F%2Fkazecheese.com%2Fproducts%2Fcheddar-horseradish-cheese-bites

Thanks for your time, I'll be waiting for a feedback.

**Comment by thebuilder** [comment]
You have some code that adds a `touchstart` event. Most likely what you are using for the image slider.

It's in this piece of minified code: 

```js
let e=document.getElementById("thumb-".concat(t));t>=3?x.current.scrollLeft=e.offsetLeft:x.current.scrollLeft=0}}});(0,s.useEffect)(()=>{let e=e=>{let t=e.touches[0].pageX,a=e.touches[0].radiusX||0;(t-a<10||t+a>window.innerWidth-10)&&e.preventDefault()},t=_.current;return t.addEventListener("touchstart",e),()=>{t&&t.removeEventListener("touchstart",e)}},[]),(0,s.useEffect)(()=>{var e;null===(e=b.current)||void 0===e||e.update({loop:!0,slides:{perView:1},created:()=>m(!0),slideChanged(e){let 
```

This is not from `react-intersection-observer`
