### ISSUE TITLE
Option to trigger only when document has a focus

### ISSUE THREAD

**Issue by pleerock** [thebuilder/react-intersection-observer#614]
Sometimes it's necessary to trigger "viewed" state only when the document / browser tab is actually visible. Imagine some new notification come when you are in the different tab and with current implementation it will be treated as visible, which is not true.

Thanks for the solid maintenance of this library btw.

**Comment by thebuilder** [comment]
This is something you would do in your application code, by adding a [visiblitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) event handler, and setting that as a state.

You can then disable the `useInView` based on visibility.
