### ISSUE TITLE
If threshold=1, big elements on small viewports will never be inView

### ISSUE THREAD

**Issue by 0xsven** [thebuilder/react-intersection-observer#616]
# Problem Description

When setting `threshold={1}`, `inView` doesn't turn to `true` when the element is larger than the viewport.

That means that whatever content is lazyloaded or transitioned, will not show up at all. 

Reproducable here: https://codesandbox.io/p/sandbox/react-intersection-observer-demo-p00wem

# Proposed solution

There could be a prop, let's call it "ignoreOverflow", that if set to true would turn `inView` to `true` if the element fills the entire viewport, even if the threshold is not met. Maybe this could even be the default behaviour?

The following code would work (I believe) if intersection observer wasn't async.
```js
const { ref, inView, entry } = useInView({ threshold: 1, triggerOnce: true });

const coversEntireView = entry?.intersectionRect.height === entry?.rootBounds.height;

return <div ref={ref} style={{ height:  `101vh` }}>{inView || coversEntireView ? "in view ✅" : "not in view ❌"}</ div>
```

# Alternatives

#### Set `rootMargin` to a fixed number
This doesnt work in my case, because I don't know the exact content of the element (content coming from CMS) and I don't know the viewport height of the user's device. 

#### Set `rootMargin` programmatically in `useEffect`
I could read the height of the viewport and the height of the element and change the rootMargin programmatcially. I am doing this now. But it would be much easier if the library supported this usecase.

# Related issues
- https://github.com/thebuilder/react-intersection-observer/issues/388
- https://github.com/thebuilder/react-intersection-observer/issues/482

PS. If you would consider this Solution, I could work on a PR for this. Thanks for the library.

**Comment by thebuilder** [comment]
Hi @0xsven - This is how the IntersectionObserver API works. I don't think your solution will solve it, because it would never trigger the intersection before the threshold is crossed, so you wouldn't know if it's overflowing. You would need another hack to monitor scrolling.

You could consider using an array of thresholds, e.g `[0, 0,5, 1]`, so it would trigger as soon as it enters the viewport, and on other intersections. Then you could do the math by inspecting the `entry`, to determine if you are close to overflowing.

**Comment by nativedone** [comment]
Not sure if that helps in your case but I was able to fix a similar issue with sections not showing up on an IOS device after coming from a CMS:

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/20998754/221320509-a3650a1a-fd12-400f-bbff-3e5b2147e3d7.png">

**Comment by 0xsven** [comment]
Thank you for all the suggestions. I got a solution working with `rootMargins`:

```js
import { useInView } from "react-intersection-observer";
import { useState, useRef, useCallback, useEffect } from "react";
import styles from "./index.module.css";

// ATTENTION: this solution does not work in iframes
export const Box = ({ bg, vh }) => {
  const [rootMargin, setRootMargin] = useState("0px 0px 0px 0px");
  const ref = useRef(null);

  const { ref: inViewRef, inView } = useInView({
    threshold: 1,
    triggerOnce: true,
    rootMargin,
  });

  useEffect(() => {
    const viewHeight = window.innerHeight;
    const boxHeight = ref.current?.offsetHeight;
    const overflow = boxHeight - viewHeight;
    if (overflow > 0) {
      setRootMargin(`${overflow / 2 + 10}px 0px ${overflow / 2 + 10}px 0px`);
    }
  }, [ref.current]);

  const setRefs = useCallback(
    (node) => {
      ref.current = node;
      inViewRef(node);
    },
    [inViewRef]
  );

  return (
    <div
      ref={setRefs}
      className={styles.box}
      style={{ backgroundColor: bg, height: `${vh}vh` }}
    >
      {inView ? "in view ✅" : "not in view ❌"}
    </div>
  );
};
```

I have update the original codesandbox with the new code: https://codesandbox.io/p/sandbox/react-intersection-observer-demo-p00wem (ATTENTION: The sandbox preview doesnt work, because it runs in an iframe. You have to open the fullpage preview.)
