### ISSUE TITLE
Are the docs for `triggerOnce` inaccurate?

### ISSUE THREAD

**Issue by petertflem** [thebuilder/react-intersection-observer#620]
Hello! 👋 

I am testing this package, and wondered about the phrasing for the `triggerOnce` option. It says:
> Only trigger the observer once.

In the [storybook](https://react-intersection-observer.vercel.app/?path=/docs/recipes--docs#track-impressions) it says:
> Set `triggerOnce`, to only trigger an event the first time the element enters the viewport.

However, when I test with a function passed to the `onChange` property in the options and `triggerOnce` set to `true`, the `onChange` handler is fired twice, once when loading the page, then again when the element enters the viewport. If the element subsequently moves out and then back in the viewport, it doesn't fire again.

This is the code for the hook:
```
const { ref, inView } = useInView({
    triggerOnce: true,
    rootMargin: '0px 0px',
    threshold: 0.5,
    onChange(inView) {
        if (inView) {
            console.log('in view', postId);
        } else {
            console.log('not in view', postId);
        }
    }
});
```

Is the behaviour more like "trigger on initial setup, then only the first time `inView` is `true`"? We're basing some tracking around this, so I'd just like to make sure.

Another question: Will the `inView` only change to `true` on the initial entry into the viewport, and never again go back to `false` to then be `true` again on subsequent entries into the viewport, when the `triggerOnce` flag is `true`? The docs state "Only trigger the observer once.", but I am not really sure what that means in practice. I'm guessing it refers to the underlying Intersection Observer API, and that "triggering the observer" refers to the callback function passed to `onChange`? I am asking because the docs doesn't state if `inView` can change from `false` to `true` more than once when `triggerOnce` is `true`.

**Comment by thebuilder** [comment]
The idea is that it will stop triggering events, after the elements enter the viewport. So ti won't go back to `false` after having been `true`.

Wondering if the double `onChange` is triggered by React.StrictMode?

**Comment by petertflem** [comment]
Thanks for the reply! 😄 

React strict mode is set to `false`, but nice idea. Maybe it could be because we're loading items from an API and displaying them async in a feed? This is the logging:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/5292940/231970573-23ebf469-a0fd-4151-b134-5b970bb7c2a8.png">
Just ignore the stuff that is _not_ "in view" or "not in view", it is just to help me identify what it is.

But as long as I know the value for `inView` will never revert to false, I can use that.
