### ISSUE TITLE
The delay option works in chrome but does not appear to work in safari

### ISSUE THREAD

**Issue by kane41** [thebuilder/react-intersection-observer#623]
**Describe the bug**
When the delay option is set, it works in chrome on Mac, but loads immediately without delay in Safari on Mac and Safari on iOS.

**To Reproduce**
You can see the following storybook in chrome and safari.
https://react-intersection-observer.vercel.app/?path=/story/useinview-hook--basic&args=delay:10000

**Expected behavior**
I would like Safari on Mac and Safari on iOS to work with delay as well as Chrome.

Environment
MacOS 13.3.1(a)
Safari 16.4 (18615.1.26.110.1)
iOS Simulator 16.0 (20A360)
Google Chrome 113.0.5672.63 (Official Build) (arm64)

**Comment by thebuilder** [comment]
The `delay` option is part of the Intersection Observer v2 spec, that's not supported in Safari.
