### ISSUE TITLE
No way to make active link on scroll in different components using .map()

### ISSUE THREAD

**Issue by nicitaacom** [thebuilder/react-intersection-observer#630]
No way to make active link on scroll in different components using .map()
I want make something similar to this
![image](https://github.com/thebuilder/react-intersection-observer/assets/39565703/2104185d-81e4-4d14-90a8-e542907aa9b3)

I want here ser inView - category.id
And in Category.tsx I want create ref
![image](https://github.com/thebuilder/react-intersection-observer/assets/39565703/61de55bf-7497-466b-8272-50648d5b9e74)

But its write me that I redeclarete variable
![image](https://github.com/thebuilder/react-intersection-observer/assets/39565703/5d9a91ca-c6b9-4289-8d77-47c34102c2dc)

**Comment by Nicitaa** [comment]
Here I want set inView
![image](https://github.com/thebuilder/react-intersection-observer/assets/39565703/aa90978d-eb00-4d36-991b-047ad5f60fad)

**Comment by thebuilder** [comment]
You can't use a hook inside a loop.

**Comment by Nicitaa** [comment]
> You can't use a hook inside a loop.

I know man
But how I can create something similar to 
https://user-images.githubusercontent.com/39565703/246155279-2104185d-81e4-4d14-90a8-e542907aa9b3.png
