### ISSUE TITLE
package not working with webpack

### ISSUE THREAD

**Issue by aditi-gawli** [thebuilder/react-intersection-observer#635]
**Describe the bug** 

I have installed this package to my repo and it's giving me webpack issues.

`error:`

ModuleParseError: Module parse failed: Unexpected token (48:35)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|           entry.isVisible = inView;
|         }

`webpack.config.js`

`const { webpackConfig } = require('@coremedia/theme-utils');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const path = require('path');

module.exports = (env, argv) => {
    const config = webpackConfig(env, argv);

    config.resolve.alias = {
        react: path.resolve(__dirname, 'node_modules', 'react'),
        'react-dom': path.resolve(__dirname, 'node_modules', 'react-dom'),
        '@deere/fuel-react': path.resolve(__dirname, 'node_modules', '@deere/fuel-react'),
        '@deere/fuel-tokens': path.resolve(__dirname, 'node_modules', '@deere/fuel-tokens'),
        '@emotion/react': path.resolve(__dirname, 'node_modules', '@emotion/react'),
        '@emotion/styled': path.resolve(__dirname, 'node_modules', '@emotion/styled'),
        '@mui/icons-material': path.resolve(__dirname, 'node_modules', '@mui/icons-material'),
        '@mui/material': path.resolve(__dirname, 'node_modules', '@mui/material'),
        '@mui/system': path.resolve(__dirname, 'node_modules', '@mui/system'),
        '@mui/utils': path.resolve(__dirname, 'node_modules', '@mui/utils'),
        '@jd/deere-storybook': path.resolve(__dirname, '..', '..', 'storybook'),
        'html-react-parser': path.resolve(__dirname, 'node_modules', 'html-react-parser'),
        swiper: path.resolve(__dirname, 'node_modules', 'swiper'),
        'react-device-detect': path.resolve(__dirname, 'node_modules', 'react-device-detect'),
        'react-router-dom': path.resolve(__dirname, 'node_modules', 'react-router-dom'),
        'react-youtube': path.resolve(__dirname, 'node_modules', 'react-youtube'),
        'react-intersection-observer': path.resolve(__dirname, 'node_modules', 'react-intersection-observer'),
        clsx: path.resolve(__dirname, 'node_modules', 'clsx'),
        'react-to-print': path.resolve(__dirname, 'node_modules', 'react-to-print'),
    };

    config.resolve.extensions = ['.js', '.jsx', '.ts', '.tsx'];

    config.module.rules.push({
        test: /\.(jsx|js|tsx|ts)$/,
        use: require.resolve('babel-loader'),
        exclude: [/node_modules/],
    });

    config.module.rules.push({
        test: /\.css$/,
        use: [{ loader: require.resolve('style-loader') }, { loader: require.resolve('css-loader') }],
    });

    config.plugins.push(
        new BundleAnalyzerPlugin({
            analyzerMode: process.env.ANALYZER || 'disabled',
        })
    );

    config.optimization.usedExports = true;
    config.optimization.concatenateModules = true;
    config.optimization.sideEffects = true;
    config.optimization.splitChunks.chunks = 'all';

    return config;
};
`

**Comment by thebuilder** [comment]
My guess is that it's the optional chaining that throws the error your are seeing.

<img width="845" alt="image" src="https://github.com/thebuilder/react-intersection-observer/assets/3764345/1f85af26-f439-4e11-bdba-43590b5ccdd5">

You'd need to run the module through Babel.

Might also make sense if i reduce the ES target, to a version before optional chaining.

**Comment by thebuilder** [comment]
It's targeting ES2020 right now

**Comment by aditi-gawli** [comment]
`const { ref, inView } = useInView({ threshold: 0 });` tried adding this still the same

**Comment by aditi-gawli** [comment]
@thebuilder can you please help me by when it will be done?
