### ISSUE TITLE
Safari support <=13 is completely broken.

### ISSUE THREAD

**Issue by rusted-love** [thebuilder/react-intersection-observer#637]
We use [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer) in our NextJS app.
Recently, we discovered that our website is broken in all Safari browsers prior to iOS 13.4.

The root of the problem is that ES2020 features (such a `constructor` and `()=>{}` syntax) are omitted in the production code.
Browser: IOS Safari 13.4
Device: All IPhones
Testing source: Browserstack

Question is:
**Is it expected behaviour to omit the latest ESM features in the [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer)? 
If so, why is it not specified in the documentation?**

For those who are looking for solution. 
**You can work around it by using the [transpilePackages](https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages) field in `next.config.js`.**

Screenshot below shows code included in our NextJS bundle.
<img width="500" alt="Screenshot 2023-06-28 at 14 15 11" src="https://github.com/thebuilder/react-intersection-observer/assets/32598874/fbe9fed8-e58f-45ba-9dc4-29da523390d1">

Screenshot of browser console.

<img width="500" alt="Screenshot 2023-06-28 at 14 14 40" src="https://github.com/thebuilder/react-intersection-observer/assets/32598874/55e667e6-c251-48a5-a313-120cd9d0a699">

**Comment by thebuilder** [comment]
Could you try the latest release? It downgrades the bundle output to ES2018, which should also fix this. 
#635

**Comment by thebuilder** [comment]
> Is it expected behaviour to omit the latest ESM features in the [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer)?

The question is what baseline target should be supported in packages. There's no definite answer to this.

**Comment by thebuilder** [comment]
Fixed by #636
