### ISSUE TITLE
use same ref,useInView for multiple components

### ISSUE THREAD

**Issue by aditi-gawli** [thebuilder/react-intersection-observer#638]
I have a case where I need to create a navBar which on scroll highlights section names as user scrolls, I was trying to use this library for but that doesn't seem to work. 
Can we have some upgrade to this where we can use same useInView for all components.

**Comment by thebuilder** [comment]
This is not something the `useInView` will support. It would require a completely different hook, to deal with multiple observers.

Either:
a) Move the `useInView` into the components, and have it report the status to your parent component.
b) use the `observe` function directly, to manually observe each child.

```ts
import { observe } from 'react-intersection-observer';
const destroy = observe(element, callback, options);
```
