### ISSUE TITLE
Not working below desktop screen view

### ISSUE THREAD

**Issue by sebalaini** [thebuilder/react-intersection-observer#644]
**Describe the bug** A clear and concise description of what the bug is.

The below code works only on big screen but not on mobile view even on desktop when you shrink enough it doesn't work.

```
'use client'

import ...
...
import { useInView } from 'react-intersection-observer'

type ItemProps = {
  src: string,
  alt: string,
} & ComponentProps<'div'>

const FadeInSection = ({ children }: { children: JSX.Element }) => {
  const { ref, inView } = useInView({
    triggerOnce: true,
    // rootMargin: '0px',
    // threshold: 0.5,
  })

  return (
    <div
      className={`${timelineStyle['fade-in-section']} ${inView ? timelineStyle['is-visible'] : ''}`}
      ref={ref}
    >
      {children}
    </div>
  )
}

const Item = ({ src, alt }: ItemProps) => (
  <FadeInSection>
    <div className='my-sm flex pl-[30px]'>
      <div className={`relative min-h-[180px] w-[98%] shadow-bottom-sm md:min-h-[420px] lg:min-h-[500px] ${timelineStyle['timeline-item-content']}`}>
        <Typography
          as='span'
          className='absolute bottom-1 right-1 z-[1] mr-sm text-md text-neutral-white'
        >
          {alt}
        </Typography>
        <Image
          src={src}
          alt={alt}
          fill={true}
          object-fit='contain'
        />
      </div>
    </div>
  </FadeInSection>
)

const Timeline = () => {
  return (
    <Section fullWidth={false}>
      <div className={`${timelineStyle['timeline-container']} relative flex flex-col`}>
        <Item
          src='/images/years/1987.jpg'
          alt='XXX'
        />
      ...
      </div>
    </Section>
  )
}

export default Timeline
```

**Expected behavior** A clear and concise description of what you expected to
happen.

Images appear when are in view on Desktop, tablet, and Mobile, currently working only above tablet size.

even moving the `<FadeInSection>` around the `<Image>` itself doesn't work on mobile, only on desktop and tablet

My previous code was like this, and now that I try properly on mobile view on desktop it doesn't work either so maybe isn't the package but my code 🤔 
```
const FadeInSection = ({ children }: { children: JSX.Element }) => {
  const [isVisible, setVisible] = useState(false)
  const domRef = useRef()

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => setVisible(entry.isIntersecting))
    })

    observer.observe(domRef.current)
  }, [])

  return (
    <div
      className={`${timelineStyle['fade-in-section']} ${isVisible ? timelineStyle['is-visible'] : ''}`}
      ref={domRef}
    >
      {children}
    </div>
  )
}
```

**Comment by thebuilder** [comment]
If you have issues with the observer not triggering as expected, then it is most likely a problem with styling.
- Is the component actually placed as expected?
- Does it actually enter/leave the viewport?

Try debugging the outer `<div>` by adding a background color/outline and setting a fixed `height`. Does the observer trigger as expected when you can visually see it enter the viewport?

Your images might need to have an actual `width/height` or aspect ratio assigned, so they position content as expected.
