### ISSUE TITLE
Bump major version for breaking changes

### ISSUE THREAD

**Issue by twiddler** [thebuilder/react-intersection-observer#652]
Hey! :wave: I noticed that [v9.5.0](https://github.com/thebuilder/react-intersection-observer/releases/tag/v9.5.0) mentions (possibly) breaking changes without increasing the major version.

I'd like to kindly suggest increasing the major version if a release (might) have breaking changes to comply with [semver](https://semver.org/). This helps dependent projects to not make false assumptions about whether an update might cause issues.

**Comment by thebuilder** [comment]
I'd normally do it, but in this case it shouldn't actually be breaking under normal circumstances. It would only break if you used the library in an unusual way. Nothing in the actually API changed - Maybe I shouldn't have written it was "Breaking changes".

If it did fail, your bundler would be the one that fails to load it, which would cause a build error. Having the reason listed in the change log should highlight the cause.
