### ISSUE TITLE
Support a ref for root

### ISSUE THREAD

**Issue by schontz** [thebuilder/react-intersection-observer#654]
I need to be able to set the root using a ref, which is not set at the time the hook is run. The desired goal is to be able to do this:

```
function Component() {
  const rootRef = useRef() // track the root
  const { ref, inView } = useInView({
    root: rootRef // pass the ref
  })

  return (
    <div ref={rootRef}>
      <div ref={ref}>Tracking me within the root</div>
    </div>
  )
}
```

I realize there may be some timing issues, but I think it's reasonable to assume that `rootRef.current` must be set when `ref` is set and the underlaying effect runs.

**Comment by thebuilder** [comment]
Hm. That should work.

**Comment by schontz** [comment]
After some testing, it does indeed work. It just feels brittle because observers can have an `undefined` root.
