### ISSUE TITLE
Add `react-dom` as a peer-dependency

### ISSUE THREAD

**Issue by tryggvigy** [thebuilder/react-intersection-observer#657]
`test-utils/` is exported as part of the public API of this module in package.json [exports](https://github.com/thebuilder/react-intersection-observer/blob/main/package.json#L9-L13). 
It imports from react-dom [`import { act } from 'react-dom/test-utils';`](https://github.com/thebuilder/react-intersection-observer/blob/main/src/test-utils.ts#L1) but `react-dom` is only declared as a `devDependency`. This can cause issues in bundlers. I think changing peerDependencies to 

```diff
"peerDependencies": {
  "react": "^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0"
+ "react-dom": "^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0"
},
```

should fix this issue

**Comment by tryggvigy** [comment]
I found this issue via script I am working on to detect how close a project is to support full ESM by analysing it's dependencies ESM support. `react-intersection-observer` results in a `resolveError` due to the above. 

Separate issue, but I'm wondering if you think we should also export a ESM version of test utils?

```diff
  "exports": {
    "./test-utils": {
      "types": "./dist/test-utils.d.ts",
-     "default": "./dist/test-utils.js"
+     "require": "./dist/test-utils.js",
+     "default": "./dist/test-utils.mjs",
    },
    ".": {
      "types": "./dist/index.d.ts",
      "require": "./dist/index.js",
      "default": "./dist/index.mjs"
    }
  },
```

to fully support consuming this library as ESM

**Comment by thebuilder** [comment]
> `test-utils/` is exported as part of the public API of this module in package.json [exports](https://github.com/thebuilder/react-intersection-observer/blob/main/package.json?rgh-link-date=2024-01-31T12%3A15%3A18Z#L9-L13). It imports from react-dom [`import { act } from 'react-dom/test-utils';`](https://github.com/thebuilder/react-intersection-observer/blob/main/src/test-utils.ts?rgh-link-date=2024-01-31T12%3A15%3A18Z#L1) but `react-dom` is only declared as a `devDependency`. This can cause issues in bundlers. I think changing peerDependencies to
> 
> ```diff
> "peerDependencies": {
>   "react": "^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0"
> + "react-dom": "^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0"
> },
> ```
> 
> should fix this issue

Good catch. I suppose it would make sense to add it - You can't really use the library without `react-dom`.

Alternatively, it could be solved by doing a dynamic import of `react-dom` instead, so it could fail gracefully if it doesn't exist.
The `act` is only [used in one place](https://github.com/thebuilder/react-intersection-observer/blob/main/src/test-utils.ts#L151), that already handles it as optional.

**Comment by thebuilder** [comment]
> I found this issue via script I am working on to detect how close a project is to support full ESM by analysing it's dependencies ESM support. `react-intersection-observer` results in a `resolveError` due to the above.
> 
> Separate issue, but I'm wondering if you think we should also export a ESM version of test utils?
> 
> ```diff
>   "exports": {
>     "./test-utils": {
>       "types": "./dist/test-utils.d.ts",
> -     "default": "./dist/test-utils.js"
> +     "require": "./dist/test-utils.js",
> +     "default": "./dist/test-utils.mjs",
>     },
>     ".": {
>       "types": "./dist/index.d.ts",
>       "require": "./dist/index.js",
>       "default": "./dist/index.mjs"
>     }
>   },
> ```
> 
> to fully support consuming this library as ESM

Makes sense. 👍  At some point it would also be nice to look into converting the project to `type: "module"`.

**Comment by tryggvigy** [comment]
> Alternatively, it could be solved by doing a dynamic import of react-dom instead, so it could fail gracefully if it doesn't exist.
The act is only [used in one place](https://github.com/thebuilder/react-intersection-observer/blob/main/src/test-utils.ts#L151), that already handles it as optional.

I guess then [triggerIntersection](https://github.com/thebuilder/react-intersection-observer/blob/main/src/test-utils.ts#L96C10-L96C29) would have to be async?

**Comment by tryggvigy** [comment]
I've seen this pattern used in several packages before:

```
"peerDependencies": { 
  "winston": "> 1.0.0 <= 1.2.10"
},
"peerDependenciesMeta": {
  "winston": {
    "optional": true
  }
}
```

and then in the CJS/ESM code:

```
try {
  require('winston')
} catch {
}
```

But I don't know how ESM friendly this is going forward in the eco-system. I haven't really seen the same pattern with `await import(...)` probably because it foces the caller to be async as well.

Yes, the code is fine when executed as ESM since the optional peer require is in a try-catch but it's kind of strange and mixes cjs and esm syntax in the same file. But rollup and other popular bundlers handle this. I think in this case they will try to evaluate the dep and if it fails to evaluate they give up and move on since they see it's in a try-catch block. They would have to know how to bundle a module that is mixing esm and cjs though. 

I think the best future-proof solution is to add react-dom as a peer dependency and import it via static import statement

**Comment by thebuilder** [comment]
It's fine makes sense - I'll make a switch to add it as a `peer`.

Outputting the test file as `.mjs` and `.cjs` is a bit more demanding. Right now it just uses `tsc` to bundle it, but that will just output the `.cjs` version.

**Comment by tryggvigy** [comment]
thanks a lot for making this improvement @thebuilder! :shipit:
