### ISSUE TITLE
test-utils failing in React 17

### ISSUE THREAD

**Issue by csantos-nydig** [thebuilder/react-intersection-observer#674]
**Describe the bug** 

I believe https://github.com/thebuilder/react-intersection-observer/releases/tag/v9.10.1 is a major breaking change and not compatible with React 17.x.

```
Named export 'act' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const { act } = pkg;

file:///Users/cesar.santos/repository/node_modules/react-intersection-observer/test-utils.mjs:2
import { act } from "react";
         ^^^
SyntaxError: Named export 'act' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const { act } = pkg;
```

**To Reproduce** 

- Go to https://codesandbox.io/p/devbox/zxqyyg?file=%2Fsrc%2FApp.test.tsx
- open terminal
- run `pnpm run test`

**Expected behavior** 

Mocks should work as expected

**Additional context** 

 "@testing-library/react": "12.1.5",
"@vitejs/plugin-react": "^4.2.1",
"happy-dom": "^14.7.1",
"typescript": "3.3.3",
"vite": "5.2.10",
"vitest": "1.5.3"
"react": "17.0.2",
"react-dom": "17.0.2",
"react-intersection-observer": "9.10.1"

**Comment by thebuilder** [comment]
You're right. React 18 has been out for so long now I didn't even consider it. Sorry about that.

**Comment by SantoJambit** [comment]
FYI, it failed on react 18.2.0 as well, as that only exported `unstable_act`, but not `act`. Not sure when exactly that changed, but the patch from 9.20.2 is working for react 18.2.0 as well.
