### ISSUE TITLE
instance.visible not set

### ISSUE THREAD

**Issue by pshev** [thebuilder/react-intersection-observer#68]
instance.visible is set to false [on instance creation](https://github.com/thebuilder/react-intersection-observer/blob/master/src/intersection.js#L52).
I see this assignment `instance.visible = inView` was removed in [this commit](https://github.com/thebuilder/react-intersection-observer/commit/5f27d59bb38af24c7d0f7041906c76cb93137c42#diff-e52648a9d9a776ebc31387e8a5a0d133L146).
So, now I struggle to find a way that property can ever be changed.
What am I missing?

**Comment by thebuilder** [comment]
Good catch - I must have missed that value was still be using. But you should still be seeing the correct behaviour, with it always set to false.

I'll look into removing it. It should be the IntersectionOberserver that's that source of truth.

**Comment by thebuilder** [comment]
Fixed in #69
