### ISSUE TITLE
Usage of `IntersectionObserverEntry.isIntersecting`

### ISSUE THREAD

**Issue by OliverJAsh** [thebuilder/react-intersection-observer#7]
Hi there,

I was looking at the code for this library and noticed that it uses `IntersectionObserverEntry.isIntersecting` if available, otherwise falling back to `intersectionRatio`: https://github.com/thebuilder/react-intersection-observer/blob/41bf482122108dd9f718e5028bb9fa79e4beca19/src/intersection.js#L73

In my tests, `IntersectionObserverEntry.isIntersecting` produced differently results to `intersectionRatio > threshold`. `isIntersecting` is true if the element intersects with the viewport regardless of the threshold. See this example, where my threshold is 0.5 but `isIntersecting` is `true` even when the `intersectionRatio` is smaller: http://jsbin.com/nuvodim/2/edit?js,console,output

Is the browser doing the right thing here? If so, is it safe to use `isIntersecting`?

**Comment by thebuilder** [comment]
Hey, looks like that could be the case. I haven't tested it extensively - Think it's only Chrome 58+ that uses it? Question is, which is the correct behavior then. 🤔

Added it in https://github.com/thebuilder/react-intersection-observer/commit/2e722c10d88af569923f1327880840fe71c5ecf9 after Chrome 58 changed how the API a bit.

**Comment by OliverJAsh** [comment]
> Question is, which is the correct behavior then.

Spec definition: https://wicg.github.io/IntersectionObserver/#dom-intersectionobserverentry-isintersecting

> isIntersecting, of type boolean, readonly
True if the target intersects with the root; false otherwise. This flag makes it possible to distinguish between an IntersectionObserverEntry signalling the transition from intersecting to not-intersecting; and an IntersectionObserverEntry signalling a transition from not-intersecting to intersecting with a zero-area intersection rect (as will happen with edge-adjacent intersections, or when the boundingClientRect has zero area).

It doesn't say anything about the the threshold…

**Comment by thebuilder** [comment]
Fixed in v.0.2.10

**Comment by thebuilder** [comment]
See demo with threshold 50%, that triggers correctly when scrolling the page:
https://thebuilder.github.io/react-intersection-observer/?selectedKind=Intersection%20Observer&selectedStory=With%20threshold%2050%25&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by OliverJAsh** [comment]
Thanks @thebuilder!
