### ISSUE TITLE
TypeScript type error with React 19 types

### ISSUE THREAD

**Issue by danielrentz** [thebuilder/react-intersection-observer#708]
**Describe the bug** 

Type error with React v19 types. The global type namespace JSX has been removed for better compatibility with other JSX libs.

https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript

**To Reproduce** Try and recreate the issue in a **Codesandbox**:

just use `@types/react` v19 and `react-intersection-observer` in a project, and run `tsc` (without skipLibChecks).

```txt
node_modules/react-intersection-observer/dist/index.d.mts:163:20 - error TS2694: Namespace 'global.JSX' has no exported member 'IntrinsicElements'.

163     as?: keyof JSX.IntrinsicElements;
                       ~~~~~~~~~~~~~~~~~
```

**Expected behavior** 

no type error

**Desktop (please complete the following information):**

- OS: Windows 11

**Comment by thebuilder** [comment]
Alright. Might need to look into having differing types to support older versions 😬

**Comment by danielrentz** [comment]
The new types (`React.JSX` instead of `JSX`) will also work with React 18 btw

**Comment by thebuilder** [comment]
Yeah, but I'm supporting down to like React 16😬

**Comment by danielrentz** [comment]
@thebuilder  Thank you!
