### ISSUE TITLE
Automatic mocking as a side-effect of importing `react-intersection-observer/test-utils` causes issues in projects using a mix of browser and non-browser test environments

### ISSUE THREAD

**Issue by philwolstenholme** [thebuilder/react-intersection-observer#711]
Hello,

I think I've found an issue with the (otherwise very helpful!) automatic mocking feature of `react-intersection-observer/test-utils` in projects with a variety of [test environments](https://vitest.dev/guide/environment).

I work on a Next.js project. Our Vitest setup uses the [`jsdom` environment](https://vitest.dev/guide/environment) by default, but some test files for API route handlers opt into using the `node` environment instead:

```typescript
/**
 * @vitest-environment node
 */

// server-side test code goes here
```

I wanted to mock the IntersectionObserver in all my _browser_ tests, so I added this to my Vitest setup file:

```typescript
if (global.window !== undefined) {
  // Only mock IntersectionObserver if we're pretending to be a browser
  // otherwise we get a 'window is undefined' error when
  // react-intersection-observer's test utils try to do their thing.
  beforeEach(() => {
    setupIntersectionMocking(vi.fn);
  });

  afterEach(() => {
    resetIntersectionMocking();
  });
}
```

However, despite the check for `global.window` I still got errors:

```
 FAIL  src/app/api/store/set/route.test.ts [ src/app/api/store/set/route.test.ts ]
ReferenceError: window is not defined
 ❯ setupIntersectionMocking node_modules/react-intersection-observer/test-utils/index.mjs:40:3
     38| }
     39| function setupIntersectionMockin…
     40|   window.IntersectionObserver = …
       |   ^
     41|     var _a, _b, _c;
     42|     const item = {
 ❯ node_modules/react-intersection-observer/test-utils/index.mjs:14:7
 ```

I think this is because by importing `setupIntersectionMocking` and `resetIntersectionMocking` from `react-intersection-observer/test-utils` the global `beforeEach` and `afterEach` were run as a side effect, and those setup the mocks – rendering my idea of only setting up the mocks if `global.window !== undefined` pointless.

I've fixed this by using `patch-package` but I think the options for fixing it at the source could include these ideas:

* Provide a way to opt-out of the automatic mocking
* Find a way to only add automatic mocking if the test environment looks like a browser one
* Provide `setupIntersectionMocking` and `resetIntersectionMocking` exports from a file with no side effects, e.g. something like `import { setupIntersectionMocking } from 'react-intersection-observer/test-utils/setupIntersectionMocking';`

The third idea (provide an export with no side effects) seems like the easiest approach to me. If you like that idea I could have a go at making a PR?

-----

This is the patch I used:

```diff
diff --git a/node_modules/react-intersection-observer/test-utils/index.js b/node_modules/react-intersection-observer/test-utils/index.js
index f189bfa..c3d7cf3 100644
--- a/node_modules/react-intersection-observer/test-utils/index.js
+++ b/node_modules/react-intersection-observer/test-utils/index.js
@@ -45,17 +45,6 @@ var act3 = (
 );
 var isMocking = false;
 var observers = /* @__PURE__ */ new Map();
-if (typeof beforeAll !== "undefined" && typeof afterEach !== "undefined") {
-  beforeAll(() => {
-    if (typeof jest !== "undefined") setupIntersectionMocking(jest.fn);
-    else if (typeof vi !== "undefined") {
-      setupIntersectionMocking(vi.fn);
-    }
-  });
-  afterEach(() => {
-    resetIntersectionMocking();
-  });
-}
 function warnOnMissingSetup() {
   if (isMocking) return;
   console.error(
diff --git a/node_modules/react-intersection-observer/test-utils/index.mjs b/node_modules/react-intersection-observer/test-utils/index.mjs
index 589c8b6..4135433 100644
--- a/node_modules/react-intersection-observer/test-utils/index.mjs
+++ b/node_modules/react-intersection-observer/test-utils/index.mjs
@@ -7,17 +7,6 @@ var act3 = (
 );
 var isMocking = false;
 var observers = /* @__PURE__ */ new Map();
-if (typeof beforeAll !== "undefined" && typeof afterEach !== "undefined") {
-  beforeAll(() => {
-    if (typeof jest !== "undefined") setupIntersectionMocking(jest.fn);
-    else if (typeof vi !== "undefined") {
-      setupIntersectionMocking(vi.fn);
-    }
-  });
-  afterEach(() => {
-    resetIntersectionMocking();
-  });
-}
 function warnOnMissingSetup() {
   if (isMocking) return;
   console.error(
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by thebuilder** [comment]
Thanks for highlighting these issues. 

Huh - Looks like it's not actually checking for `typeof window` before adding the setup. That should be added as a guard. Not sure how I haven't noticed that before. 

For your specific case - Does it make sense to mock all pages, if you aren't actually validating anything? You would need to import the `test-utils` in your test file to trigger intersections, which would then trigger the mocking.

If you set a [default fallback](https://github.com/thebuilder/react-intersection-observer#unsupported-fallback) in your global test file, that should ensure observers don't break, while still making it possible for you to trigger the observers in tests if needed.

**Comment by philwolstenholme** [comment]
My thinking behind doing the mocking globally was to avoid getting `Error: Uncaught [ReferenceError: IntersectionObserver is not defined]` errors when testing a component that uses our 'product list' component (the one with the Intersection Observer) but that doesn't actually need to test the Intersection Observer functionality and so doesn't import `react-intersection-observer/test-utils`.

I might be missing something, but I added `defaultFallbackInView(true);` to my `vitest.setup.ts` file but still get the `Uncaught [ReferenceError: IntersectionObserver is not defined]` issue. 

Our tests are _mostly_ fake browser ones rather than Node ones, and I like the idea of always having `IntersectionObserver` mocked so whenever my team adds a new component that uses our product list component they don't get errors and have to remember what causes them and copy/paste the `beforeEach` and `afterEach` from another test file.

Any better ideas gratefully appreciated though!

**Comment by philwolstenholme** [comment]
> Huh - Looks like it's not actually checking for typeof window before adding the setup. That should be added as a guard. Not sure how I haven't noticed that before.


Forgot to say, I can whip up a PR for a guard if you like?

**Comment by thebuilder** [comment]
> I might be missing something, but I added `defaultFallbackInView(true);` to my `vitest.setup.ts` file but still get the `Uncaught [ReferenceError: IntersectionObserver is not defined]` issue.

Obviously, only do this in the browser environment. 😄 
You want to throw an error if you ever try to access the `IntersectionObserver`  in Node.

**Comment by thebuilder** [comment]
> Any better ideas gratefully appreciated though!

A better solution in general - Consider using the new [Browser mode](https://vitest.dev/guide/browser/) instead of JSDom. Faster, and you don't fake browser specific API's. `IntersectionObserver` will just work as expected, and react to what's rendered in the viewport.

**Comment by philwolstenholme** [comment]
> > Any better ideas gratefully appreciated though!
> 
> A better solution in general - Consider using the new [Browser mode](https://vitest.dev/guide/browser/) instead of JSDom. Faster, and you don't fake browser specific API's. `IntersectionObserver` will just work as expected, and react to what's rendered in the viewport.

Definitely on my list for things to try in 2025! 😁 JSDOM and Node-pretending-to-be-a-browser has caused us all enough headaches over the years
