### ISSUE TITLE
Initial inView is always true

### ISSUE THREAD

**Issue by GeKorm** [thebuilder/react-intersection-observer#8]
Hello, thanks for making this nice enhancer.

I'm using v0.2.12. `inView` is initially true until the component goes out in and out of the view once. You can see an example in the storybook, where on a small viewport, the logger shows `inView` as true even though the bar is way below.

![image](https://cloud.githubusercontent.com/assets/6104345/26408771/9ed16150-4096-11e7-8c97-513f5bb55175.png)

**Comment by thebuilder** [comment]
Hey, indeed. I think this is related to me removing the isIntersecting in #7 
After Chrome 58 it always triggers the callback. I'll need to check isIntersecting exists and is true.
Looking at it.

**Comment by thebuilder** [comment]
Fixed in v0.2.13 👍
