### ISSUE TITLE
Incorrect use of babelrc

### ISSUE THREAD

**Issue by rahuljain-tt** [thebuilder/react-intersection-observer#92]
react-intersection-observer is used as a dependency in react-scroll-percentage, I am getting below issue in running jest test cases
Couldn't find preset "./.babelrc.js" relative to directory "/node_modules/react-intersection-observer"

react-scroll-percentage has a babelrc in that, which might be causing issue while transpiling the react-intersection-observer. Below link has detailed explanation of this.

https://github.com/parcel-bundler/parcel/issues/482

I am not clear if react-intersection-observer has to add babelrc in them or react-scroll-percentage has to remove its babelrc.

Note: I am facing this issue with Jest only, webpack build is running properly.

**Comment by thebuilder** [comment]
I'll remove the Babel file from the non bundle👌
